### ISSUE TITLE
dump() shortcut to return dump instead of print

### ISSUE THREAD

**Issue by amik6** [nette/tracy#100]
I think it would be nice if dump() shortcut would behave just like \Tracy\Debugger::dump, I mean that the second argument set to TRUE will make dump to return the dumped value as string instead of printing out.
However, as it would be a BC break because dump() now returns its first argument, I'm not sure if it wouldn't be a better idea to solve it another way, for example make another shortcut sdump()...
I need this quite often (dumping something to logs, in console where echo does not work etc...) and I would find such shortcut extremely useful.
And, I would willingly create a pull request if you agree here about the form of the shortcut :)

**Comment by dg** [comment]
To alter `dump()` is not possible. Why do you not create own function?

**Comment by amik6** [comment]
Yes, of course I can :) I just think  it may be useful commonly enough to have such shortcut integrated with tracy like the current dump shortcut.
