### ISSUE TITLE
Bad string in execution time

### ISSUE THREAD

**Issue by wassy123** [nette/tracy#103]
If i update on Nette 2.3, Sometimes it shows me this error http://ctrlv.cz/WLKd

**Comment by JanTvrdik** [comment]
What is in `$val` and in `$key`?

**Comment by wassy123** [comment]
"Execution time" => "2\xe2408.8\xe2\x80\xafms"

**Comment by JanTvrdik** [comment]
Thanks for reporting, this is a bug. Possible useful info: http://3v4l.org/PfO1M
