### ISSUE TITLE
Is there a way to change the red background of the firelogger messages

### ISSUE THREAD

**Issue by richtrefz** [nette/tracy#105]
When I run tracy-2.2.6/examples/firebug-dump.php or tracy-2.3.0/examples/firebug-dump.php, the three messages in the firebug logger tab have a bright red background that isn't easy to read - for me.  
Also tracy doesn't seem to take advantage of firelogger's info, warning, error, ... levels.

I just can't see where this red color is coming from.

![sc-20150303-165615](https://cloud.githubusercontent.com/assets/1500959/6473245/3beaff3e-c1c6-11e4-816e-25930c3dded8.png)

**Comment by dg** [comment]
It is red as soon as log message has call stack (ie. `+` on left side). It seems like FireLogger bug.
