### ISSUE TITLE
Tracy debugger 2.3.0 always invisible

### ISSUE THREAD

**Issue by ghazispeakserve** [nette/tracy#106]
Since the release of 2.3.0, tracy debugger is always invisible.

**Comment by dg** [comment]
I see it.

**Comment by ghazispeakserve** [comment]
I am checking out different commits to from which one my issue came. The version 2.2.6 works perfectly.

**Comment by fprochazka** [comment]
@ghazispeakserve can you define invisible? Isn't there just a fatal error that prevents the panel from rendering? Look at the bottom of the pge.

**Comment by ghazispeakserve** [comment]
I couldn't find the source of the issue. The debug bar style is "display: none;". Then when I disable this style property and try to drag the bar it gets sticky to my cursor.

**Comment by ghazispeakserve** [comment]
The issue is only present with Firefox on windows. I am using version 36.0.

And the JS console is telling me that there is an error with this line withing function ```Bar.prototype.restorePosition```
```javascript
var pos = JSON.parse(localStorage.getItem(this.id));
```

and the error I get is
```NS_ERROR_STORAGE_BUSY: ```

**Comment by ghazispeakserve** [comment]
Fixed in Firefox 36.0.1

**Comment by nakashu** [comment]
for me - tracy is invisible because of .. display: none; set on the main id in css.
