### ISSUE TITLE
PHP7 on Win32: Fatal error: Cannot use "self" when no class scope is active

### ISSUE THREAD

**Issue by george-oakling** [nette/tracy#110]
Hi! Just trying the nigtbuild of php-master (php7) with clean nette/web-project, running on internal php webserver: "php -S 0.0.0.0:88" ends up with Fatal error in Tracy. 

Fatal error: Cannot use "self" when no class scope is active in C:\Users\George\Documents\Web\web-project\vendor\tracy\tracy\src\Tracy\assets\BlueScreen\bluescreen.phtml on line 101.

**Comment by dg** [comment]
I think it is still too early to fix PHP 7 issues.

**Comment by Majkl578** [comment]
It was a bug in PHP 7, should be fixed now, see https://github.com/php/php-src/commit/16a9bc1ec20533c76ba992bfc64dd69e7b7d9001#commitcomment-11083541.
