### ISSUE TITLE
Debugger::$maxLen not working

### ISSUE THREAD

**Issue by matak** [nette/tracy#114]
If I set maxLen=1000 still truncate is set to 150.

"SELECT  `products`.`ids` as `ids`,`products`.`type` as `type`,`products`.`sku` as `sku`,`products`.`EAN` as `EAN`,`products`.`producer_id` as `produce ... " (1699)

Maybe the problem is here

https://github.com/nette/tracy/blob/master/src/Tracy/assets/BlueScreen/bluescreen.phtml#L136

that no options of truncate is set.

**Comment by JanTvrdik** [comment]
That is feature. That being sad – it may currently not be obvious for programmer to see what is affected by some options and what is not.

**Comment by dg** [comment]
It affects only function `dump()`

**Comment by JanTvrdik** [comment]
More precisely it affects `Debugger::dump()` and `Debugger::barDump()`. `Dumper::dump()` + others are unaffected. Changing Bluescreen options is currently not possible. Not sure whether that is intentional or it is just considered unnecessary.

**Comment by matak** [comment]
So how you debug longer strings if i can not see them?

**Comment by dg** [comment]
If I needed to debug longer strings, I would have it implemented, probably in BlueScreen class.

**Comment by matak** [comment]
sorry for my english

If I needed - means that you suggest me to implement it? or you want to tell me that there is no need to implement it?

if i implemented and nobody is interested to add my pull request so i would not help me

**Comment by dg** [comment]
> Jak ladíte delší řetězce, pokud je nemohu vidět?

> (Nijak.) Kdybych to potřeboval, musel bych si to naimplementovat, asi do třídy BlueScreen.

Of course, you can implement it.

**Comment by nechutny** [comment]
I 've found same "bug".  When I 'm debugging some SQL i want to view them full. Tried to set Debugger::$maxLen to bigger size, but no success. It's not only dump() function, but also function arguments at blue screen. I think, that expected behaviour is using $maxLen. So we can change src/Tracy/Dumper.php line 93 from hardcoded value (ugly!) to something like Debugger::$maxLen
