### ISSUE TITLE
Missing extension requirement in composer

### ISSUE THREAD

**Issue by MacFJA** [nette/tracy#117]
The extension `iconv` is required by: 
 - [assets/Bar/info.panel.phtml](https://github.com/nette/tracy/blob/4b29ebd227d7810faa740475d264de8f8b0b40a5/src/Tracy/assets/Bar/info.panel.phtml#L48)
 - [Dumper.php](https://github.com/nette/tracy/blob/4b29ebd227d7810faa740475d264de8f8b0b40a5/src/Tracy/Dumper.php#L410)

In composer.json, adding `"ext-iconv": "*"` in the **require** section, will do the trick

**Comment by Majkl578** [comment]
There is more missing extensions, e.g. json.

**Comment by dg** [comment]
iconv is AFAIK default extension
