### ISSUE TITLE
Update to 2.3.7 whitescreens instead of showing exception page (PHP 7 RC6)

### ISSUE THREAD

**Issue by martindilling** [nette/tracy#127]
After the update to 2.3.7 it doesn't show the exception page anymore, it just whitescreens with a 500 http status code.
It works when I roll back to 2.3.6.
And I'm running on PHP 7 RC6.

Not using the debug bar, but using the Debugger::exceptionHandler($e); to handle the exceptions globally.

I'm not really sure what is causing it, but if you have any questions just ask and I'll do my best to help :)

**Comment by dg** [comment]
Tracy expects that it will be started using method `Debugger::enable()`. In 2.3.7 it reserves some memory in `enable()` and `exceptionHandler` relies on it.

**Comment by ptoi** [comment]
I can confirm that white page is shown instead of exception page since I update to PHP 7.x
In simple project it works properly, in some bigger non-nette-based project not (some libs with thousands lines are included). The same with PHP 5.6 works. 

I am using tracy in the way:

    Debugger::enable();
    Debugger::$strictMode = TRUE;

Hard to guess what is wrong.

**Comment by dg** [comment]
Are you using Tracy 2.3.7? See version in Debug Bar.

**Comment by ptoi** [comment]
Yes, the latest one:
![image](https://cloud.githubusercontent.com/assets/16337516/11872159/2ac9feca-a4d4-11e5-8bc8-67fbc1d918fe.png)

**Comment by dg** [comment]
Can you try older versions? 2.3.6 or 2.3.5?

**Comment by ptoi** [comment]
Okay, my fault, it has nothing to do with PHP7 or tracy v2.3.7

I changed error_reporting in my sources and forgot it. But may be any explanation why ~E_NOTICE can't be used?
These does not work:

    require_once 'tracy.phar';
    use Tracy\Debugger;
    Debugger::enable();
    Debugger::$strictMode = TRUE;
    error_reporting(E_ALL & ~E_NOTICE);
    
    do error

**Comment by dg** [comment]
What do you mean by it doesnt work?

**Comment by ptoi** [comment]
The code above where 
    error_reporting(E_ALL & ~E_NOTICE); 
is used after
    Debugger::enable();
means that page with exception is not shown, the exception caused by "do error" is not caught. It is caused by ~E_NOTICE.

**Comment by dg** [comment]
`error_reporting` has not impact on catching and handling exceptions.

**Comment by ptoi** [comment]
Okay, try my sample yourself, and you will see that "do error" won't be caught by tracy because of error_reporting(~E_NOTICE); 
The same in v2.3.7 and v2.3.6 as well. 

<?php
    require_once 'tracy.phar';
    use Tracy\Debugger;
    Debugger::enable();
    Debugger::$strictMode = TRUE;
    error_reporting(E_ALL & ~E_NOTICE);
    error
?>

if you commented out error_reporting then "error" is processed by Tracy, without not.

**Comment by dg** [comment]
What exactly is `error`?
