### ISSUE TITLE
It's 2.2.9 correct version number?

### ISSUE THREAD

**Issue by OzzyCzech** [nette/tracy#128]
https://github.com/nette/tracy/releases/ 

- 2.2.9 :-)
- 2.3.7
- 2.3.6

**Comment by dg** [comment]
Is not?

**Comment by OzzyCzech** [comment]
it's smaller number than older 2.3.7 but never mind, it's just a number

**Comment by dg** [comment]
Report issue on GitHub.

**Comment by Vrtak-CZ** [comment]
Github sort releases by release (tag) time.
