### ISSUE TITLE
Caught exception page is not formatted to red style v2.3.7

### ISSUE THREAD

**Issue by ptoi** [nette/tracy#129]
Hi Dave, when I used tracy in just empty project, the exception page is not formated as usual, unformatted page is shown for tracy v2.3.7

![image](https://cloud.githubusercontent.com/assets/16337516/11871454/f4aefb00-a4cf-11e5-97ad-f1b07c4db160.png)

BTW: in footer appeared info about tracy 2.4-dev, but the my v2.3.7 relase has been downloaded from https://github.com/nette/tracy/releases/download/v2.3.7/tracy.phar (17.12.2015)

v2.2.9 works properly. 
Thank you, Petr.

**Comment by dg** [comment]
I fixed tracy.phar, could you download it again?

**Comment by ptoi** [comment]
Perfect, now it is nicely formatted, thank you!
