### ISSUE TITLE
Contenct-Security-Policy

### ISSUE THREAD

**Issue by enumag** [nette/tracy#136]
I'm currently experimenting with [Content-Security-Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) and sure enough Tracy doesn't work unless both `'unsafe-inline'` and `'unsafe-eval'` are allowed. I can enable them for development only of course but I'd like to avoid it. Enabling It could easily lead me to a situation where I miss some real CSP violation because of it and push it to production.

**Comment by dg** [comment]
For checking whether you miss some real CSP violation you can use header `Content-Security-Policy-Report-Only`.

**Comment by enumag** [comment]
@dg I'm aware except it will report Tracy violations as well and I didn't find any way to filter them out to keep only the real ones.

**Comment by dg** [comment]
Tracy bar would sometime in the future work without inline and eval #81, while Bluescreen will require unsafe-inline. This can be solved only using CSP `nonce` (in the meantime it may be used by Bar too). But IMHO nonce is not supported by any browser.

**Comment by enumag** [comment]
According to Can I use it [should](http://caniuse.com/#feat=contentsecuritypolicy2) work in Firefox and Chrome but I didn't test it yet.

**Comment by dg** [comment]
So feel free to send PR :-)

**Comment by spaze** [comment]
@dg Thanks for the fix, it's quite clever to fetch the nonce from the response headers!
