### ISSUE TITLE
does logging support firefox native developer tools ?

### ISSUE THREAD

**Issue by adrianmak** [nette/tracy#138]
Not the firebug extension

**Comment by rostenkowski** [comment]
For questions please use [forum](https://forum.nette.org/en/).

AFAIK the logging messages are being sent trough the HTTP headers and as such I doubt the native developer tools could do anything with it...

**Comment by dg** [comment]
I think that native Firefox dev tool does not support own extensions like FireLogger.

**Comment by Majkl578** [comment]
It does, using Chrome Logger protocol, but only in recent versions, see here: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Server

**Comment by hrach** [comment]
> I think that native Firefox dev tool does not support own extensions like FireLogger.

They do support own extensions like FireLogger. Not the FireLogger itself, though. As mentioned by Majk, server logging is currently supported. Example of extension of native devtools is for example [React devtools](https://addons.mozilla.org/cs/firefox/addon/react-devtools/).
