### ISSUE TITLE
White page / output buffers are cleared when used with ZF1 Page Cache on 2.3.9

### ISSUE THREAD

**Issue by holtkamp** [nette/tracy#139]
**Environment**
- PHP 7.0.3
- Tracy 2.3.9
- Zend Framework 1 application
 - pages of which the URL end with ```.html``` we have [Zend Framework Page cache](http://framework.zend.com/manual/1.12/en/zend.cache.frontends.html#zend.cache.frontends.page) enabled. This kind of cache [uses output buffering to be able to write all collected output to a file](https://github.com/zendframework/zf1/blob/fccf5d2d0cdbc5e5707159c78442fd1c7723d9e9/library/Zend/Cache/Frontend/Page.php#L289-L332), note that the ```_flush($data)``` function is used as callback, and also echo it.

**Problem**
On the pages that have the Page Cache enabled, the only content in the response is the content as generated by Tracy, rest is a white screen. When not enabling Tracy with ```Debugger::enable()```, this problem does not occur. 

**Cause: self::removeOutputBuffers()**
When commenting out the ```self::removeOutputBuffers()``` [here](https://github.com/nette/tracy/blob/v2.3.9/src/Tracy/Debugger.php#L216), the problem does not occur. It seems this functionality was introduced in ```2.3.9```? When rolling back to ```2.3.8``` everything works as expected.

I think when enabling Tracy, the ```ob_get_levels()``` returns 0, since the Page Cache has not kicked in yet```, don't think this approach is 'very' reliable...

**SemVer?**
This makes me have to ask: why was only the patch version bumped and not the minor version? This seems like new functionality, right? Or is [Semantic Version](www.semver.org) not applied so strict...

**Comment by dg** [comment]
I'm sorry if I added a BC break, this should be bug fix, but output buffering stuff is really hard to tune…

So what exactly does Zend Framework Page cache with older Tracy 2.3.8:
1. Tracy is enabled
2. output buffering is enabled
3. part of the HTML page is generated
4. error -> uncaught exception is thrown
5. Tracy catches the exception
6. Tracy generates default [error page](https://files.nette.org/git/tracy/tracy-error2.png) to output
7. output buffer _flush is called and saves to cache partially generated HTML + error page (**it is bad**)

And what should do current Tracy 2.3.9:
1. Tracy is enabled
2. output buffering is enabled
3. part of the HTML page is generated
4. error -> uncaught exception is thrown
5. Tracy catches the exception
6. **now it differs:** Tracy end output buffer via `ob_end_clean`
7. output buffer _flush is called and via second argument it can detect flag `clean` and do not save cache at all, but ZF1 ignores it, so it saves to cache partially generated HTML (**without error page**)
8. Tracy generates default [error page](https://files.nette.org/git/tracy/tracy-error2.png) to output

So Tracy 2.3.9 should fix previous incorrect behaviour, not to introduce it… Can you please try to find out how it is possible that it does not happen?

*Btw, in step 6 Tracy might also delete output buffer via ob_clean() before ob_end_clean() is called*

**Comment by holtkamp** [comment]
@dg thanks for the swift and detailed response. 

Ok, now I understand why you want to clear the output buffer. I think you already pointed out where source of the problem origins. According to the [documentation](http://php.net/manual/en/function.ob-start.php) The ```_flush()```callback function of Zend Framework Page Cache will be invoked when:
- when the output buffer is flushed (sent) or 
- cleaned (with ob_flush(), ob_clean() or similar function)

Normally our setup would use the first option. But now Tracy 2.3.9 triggers flushing in step 6 when ```ob_end_flush()``` or ```ob_end_clean()``` is invoked [here](https://github.com/nette/tracy/blob/v2.3.9/src/Tracy/Debugger.php#L394-L395) and the actual content of the buffer is discarded / not sent to the browser.

I think it is incorrect to assume that all kind of output buffers can be simply removed, maybe other people use it for specific purposes. They should be able to be used next to the *debugger*. So maybe ONLY remove them when an exception/error has occurred, something like (not sure why you got the check on the chunk size...):

```php
if($status['chunk_size']){
	if(!$result = ob_end_flush()){
		break;
	}
} else{
	if($result = ob_get_contents()){ //get content form buffer, do not 'flush' the result yet
		ob_end_clean(); // clean the buffer
		if($noError === true && $noException === true){
			echo $result; //now flush / output the buffer normally
		}
	} else{
		break;
	}
}
```

I don't think the Zend Framework Page Cache is used "a lot", but it is a very powerful approach to caching, so I prefer not to remove it ;).

**Comment by dg** [comment]
I probably understand where the problem is… if you remove this [line](https://github.com/nette/tracy/blob/3db887daa2a7a120189da73e9cf8ff415adfd70e/src/Tracy/Debugger.php#L216), will it help you?

**Comment by holtkamp** [comment]
Yes, that does work for me, as also mentioned in my initial issue description :smile: 
>
When commenting out the self::removeOutputBuffers() here, the problem does not occur.

**Comment by dg** [comment]
I am today a bit slower :-) 

Could you test this solution? https://github.com/nette/tracy/commit/e90cba4d2da7fdc3406844727baccdcfe1f39f10

**Comment by holtkamp** [comment]
Yeap, that seems to do the trick...

One could argue however
- if no error occurred, why should the Tracy Debugger flush the output buffer with ```ob_end_flush()```?
- why not leave it to default behaviour and prevent flushing the output buffer when an error HAS occurred?

**Comment by dg** [comment]
I'll try again write it in steps

Zend Framework Page cache with older Tracy 2.3.8 when no error occurred
1. Tracy is enabled
2. output buffering is enabled
3. HTML page is generated
4. Tracy generates [Debug Bar](https://files.nette.org/git/doc-2.3/tracy-bar.png) to output
5. output buffer _flush is called and stores generated HTML **+ Debug Bar** to cache

And ZF cache with Tracy 2.3.9: (ehm, 2.3.10)
1. Tracy is enabled
2. output buffering is enabled
3. HTML page is generated
4. Tracy ends output buffer via `ob_end_flush`
5. output buffer _flush is called and stores generated HTML (**without Debug Bar**) to cache
6. Tracy generates Debug Bar to output

**Comment by holtkamp** [comment]
Aah, ok, I think I understand what you are trying to explain. Even if no error / exception has occurred, you do not want to have the Tracy debug bar end up in the output buffer that is already in effect / being used for the common page output. You want to separate them. 

Ok, sorry, I am a bit slow today ;). 

Well, looking forward to the new tagged versions, thanks for the great response times and explanations!

**Comment by dg** [comment]
You're welcome

**Comment by holtkamp** [comment]
@dg any thoughts on releasing a ```2.3.10``` for this, or should we stick with ```2.3.8``` for the time being? No rush, just curious ;)

**Comment by dg** [comment]
I'd like to release 2.3.10 in few days

**Comment by holtkamp** [comment]
great :+1:
