### ISSUE TITLE
In version 2.3.9 i get a blank screen on any page trying to show the debugger

### ISSUE THREAD

**Issue by alexryderwhytewaters** [nette/tracy#145]
I haven't had a chance to investigate yet, but rolling back to 2.3.8 does fix it.

**Comment by dg** [comment]
Can you try latest v2.3 development version, ie 2.3@dev in composer?

**Comment by alexryderwhytewaters** [comment]
I used "tracy/tracy": "2.3@dev" in composer and that worked.

**Comment by dg** [comment]
I have released version 2.3.10, it should now work.

**Comment by alexryderwhytewaters** [comment]
Looks like it fixes the problem. Thanks
