### ISSUE TITLE
Add PID to BlueScreen

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tracy#152]
EasyPick Feature: add process ID (PID) to BlueScreen

[relevant line in source code](https://github.com/nette/tracy/blob/a54ad9a2cd6ffa7c382b0aa58ed7739c263387fa/src/Tracy/Helpers.php#L152)

**Comment by dg** [comment]
PR?

**Comment by JanTvrdik** [comment]
I'd like to give chance to others to implement it. I'll send it tomorrow if no one send it.

**Comment by dg** [comment]
LOL
