### ISSUE TITLE
Bluescreen: longer lines have wrong styling

### ISSUE THREAD

**Issue by greeny** [nette/tracy#156]
When an error occurs on long line of code (or developer has small screen), highlighted line is styled badly, when you scroll the code to the right:

![image](https://cloud.githubusercontent.com/assets/3734204/14243742/8781525c-fa57-11e5-85dd-23ccba465860.png)

Same screen with selected part of code:

![image](https://cloud.githubusercontent.com/assets/3734204/14243776/b3c15b1e-fa57-11e5-951d-b7ab31a8f2a1.png)

This makes it hard to debug e.g. compiled Latte templates, etc.

**Comment by dg** [comment]
It seems good in Chrome/Firefox/IE Edge

**Comment by greeny** [comment]
I am using Chromium Version 48.0.2564.116 Ubuntu 14.04 (64-bit). So it is browser thing?

**Comment by dg** [comment]
Can you try a different browser?

**Comment by greeny** [comment]
Firefox 45.0 at Ubuntu seems to have same problem:

![image](https://cloud.githubusercontent.com/assets/3734204/14244107/ab2475ac-fa59-11e5-9759-a334d8ce5988.png)

**Comment by greeny** [comment]
Tested it on most recent versions of Chrome and FF and it still does not work, when you have smaller width than width of that lane with code

**Comment by dg** [comment]
![image](https://cloud.githubusercontent.com/assets/194960/14246237/123e0fa8-fa66-11e5-866b-c3ec8323ee7b.png)

![image](https://cloud.githubusercontent.com/assets/194960/14246255/286c32a0-fa66-11e5-89a2-fef294f02a9d.png)

**Comment by greeny** [comment]
Can I send you somewhere my exception file, that was doing it? (like privately, since its more of company project). Just to clarify if that is by browser or wrong-generated exception

**Comment by dg** [comment]
You can send it to my email

**Comment by greeny** [comment]
Sent

**Comment by dg** [comment]
Hmm, it's a matter of template panel, other panels work ok.

**Comment by greeny** [comment]
Thanks :+1:
