### ISSUE TITLE
Very long TTFB with 2.4-dev

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#157]
I am seeing this on multiple servers and multiple instances of Tracy, but haven't been able to narrow it down just yet.

The total TTFB for the following three files is typically 3-5 seconds each which delays the display of the debugger bar for up to 15 seconds: 
?_tracy_bar=css&v=2.4-dev
?_tracy_bar=js&v=2.4-dev
?_tracy_bar=content.b58fcb708831a7734361b5b966546c56

As soon as I swap to 2.3 stable, the debugger bar is displayed almost instantly after the page has finished loading.

I am not sure if it's just related to the new loader.phtml approach or not.

Please let me know if there is anything else I can provide to help to debug it.

**Comment by dg** [comment]
What is your operating system?

**Comment by adrianbj** [comment]
My local dev is OSX, but I am seeing the same on a production Linux server.

**Comment by dg** [comment]
Hmm. It is still under development, so I'll try to change locking mechanism and ping you.

**Comment by dg** [comment]
@adrianbj do you have active xdebug? And xdebug session?

**Comment by adrianbj** [comment]
Yes - disabling xdebug speeds things up straight away.

**Comment by dg** [comment]
So, Tracy creates 3 more HTTP requests:
- for JS
- for CSS
- for HTML code of bar

JS and CSS has long caching time, but caching is often disabled when you use DevTools etc. Even so these request should take only few miliseconds. It is more than 0 miliseconds in 2.3, but it has another benefits.

What I don't know is why enabled xdebug makes these requests order of magnitude slower… I really have no idea.

**Comment by adrianbj** [comment]
Just tested and that has definitely taken care of the issue. Still not as fast as 2.3, but as you mentioned there are definite advantages to the approach in 2.4 and this "fix" makes it usable.

Thanks!
