### ISSUE TITLE
Lazy initialization of bar panels

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tracy#158]
Currently if I register for example [Nextras Mail Panel](https://github.com/nextras/mail-panel) in `config.neon` (see [installation](https://github.com/nextras/mail-panel#installation)), the `MailPanel` instance is created regardless of whether it would actually be used.

This behavior is both **inefficient** (panels may have non-trivial dependencies) and **potentially dangerous** (e.g. Nextras Mail Panel [handle incoming request](https://github.com/nextras/mail-panel/blob/fc4e4ca3980f928dcfd4c86b73cf665ab93225de/src/MailPanel.php#L57) in constructor).

What do you think about adding some event (similar to `Latte\Engine::$onCompile)` and updating `Tracy\Extension` to utilize such event.

Or should developers register Tracy bars only in their local configs?

**Comment by enumag** [comment]
Personally I use a debug.neon which is only included in debug mode.
