### ISSUE TITLE
Tracy not detecting ajax calls from Angularjs

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#167]
Not sure if you would consider this a bug with Tracy or whether you might be at least be able to come up with a workaround.

If you do an ajax call from Angular, like:
```
.controller('HealthController', ['$scope', '$sce', '$http', function($scope, $sce, $http) {

    //to allow Tracy to know it's an ajax call and therefore not add code to call
   $http.defaults.headers.common["X-Requested-With"] = "XMLHttpRequest";

   $http.get("/data/health-data.php?rc=" + document.getElementById("rc").getAttribute("data-name"))
   .success(function (response) {
```

you need to add the headers (not required for the call to work), otherwise Tracy adds debugger bar scripts to the bottom of the response which is not desired - especially if the returned data is in JSON format.

Here is some more info: https://laracasts.com/discuss/channels/requests/laravel-5-doesnt-behave-to-angularjs-like-ajax-request

Perhaps Tracy could detect an angular ajax call, even without the header being sent?

**Comment by dg** [comment]
How detect ajax request when there is no `X-Requested-With` header?

**Comment by adrianbj** [comment]
I honestly don't know - I can't seem to find a solution. 

Perhaps there is nothing that can be done, but maybe it should be noted in Tracy's documentation somewhere that the header needs to be sent or you will have problems?

**Comment by dg** [comment]
Yeah, that would be helpful, can you please write it here https://github.com/nette/web-content/blob/nette.org/tracy/en/homepage.texy?
