### ISSUE TITLE
rawurlencode of $file causes problems with some editors

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#172]
https://github.com/nette/tracy/blob/e0e5557bf164287ff5426a0d743eff5381e8caac/src/Tracy/Helpers.php#L51 encodes the URL, which is generally a good thing, but the Eclipse editor (and maybe others) doesn't work if the path is encoded. 

This isn't terribly critical because it can be worked around by doing something like the following in your editor protocol setup script:
```
set this_URL to replace_chars(this_URL, "%2F", "/")
```

It should probably be considered a bug in Eclipse?

I guess the question I have is whether encoding the path is really necessary in the first place? I know it is needed for spaces, but who has spaces in script folders/files?

Anyway, please feel free to simply close this if you don't think it's worth worrying about - just wanted you to know more than anything.

**Comment by dg** [comment]
Because it is URL, it really should be encoded. It seems like Eclipse bug.

**Comment by adrianbj** [comment]
Agreed - no problem!
