### ISSUE TITLE
Ability to hide panel labels

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#173]
When you have a lot of custom panels the debugger bar can become very wide. I'd like to propose a: `Debugger::$hideLabels` option. Obviously it would be up to panel authors to update to support this, but I think it would be very helpful.

I have implemented it within the code for my custom panels, but I would rather see it in the core. Here is an idea of the difference it can make:

![screen shot 2016-05-16 at 4 46 40 pm](https://cloud.githubusercontent.com/assets/871211/15307232/ef8537fc-1b85-11e6-93b6-d7eb2fbd846e.png)
![screen shot 2016-05-16 at 4 45 55 pm](https://cloud.githubusercontent.com/assets/871211/15307233/ef859800-1b85-11e6-8036-061589385899.png)

Let me know if this is something you might be interested in and I can put together a PR.

**Comment by dg** [comment]
I would like automatic label hidding when the bar is too wide for browser window.

**Comment by JanTvrdik** [comment]
@dg The following seems to work, but is a bit ugly performance-wise

~~~js
Bar.prototype.collapseLabels = function() {
	var labels = this.elem.querySelectorAll('.tracy-label');
	forEach(labels, function (label) {
		label.hidden = false;
	});

	for (var i = labels.length - 1; this.elem.clientHeight >= 40 && i >= 0; i--) {
		labels.item(i).hidden = true;
	}
};

	window.addEventListener('resize', function () {
		Tracy.Debug.bar.collapseLabels();
	});
~~~
