### ISSUE TITLE
"Search" link problem

### ISSUE THREAD

**Issue by krausv** [nette/tracy#180]
Hello,
when I click on "search" in Ajax bluescreen
![tracy](https://cloud.githubusercontent.com/assets/5638224/15427681/0e92bb6a-1e97-11e6-8ea8-7d575487b753.png)
so my page scroll down. Redirection to Google will not be executed

I using last revision of Tracy (1d8781d), Google Chrome 50

**Comment by dg** [comment]
Can you investigate it? It works to me (example ajax.php)

**Comment by krausv** [comment]
Ofcourse.

If I have form in boostrap modal (http://getbootstrap.com/javascript/#modals) and this form throw exception in ajax request, then occurs this problem.

If I render form without modal, then everything works fine.

Same problem has this arrow
![arrow](https://cloud.githubusercontent.com/assets/5638224/15461469/6c6ba910-20bb-11e6-8c41-3009dd7df77e.png)

**Comment by JanTvrdik** [comment]
Try the latest dev version, there was a [bug in escaping](https://github.com/nette/tracy/commit/b4ecf4371a5a2e406cea99061b01f33fc7393bb5) which caused JS failure.

**Comment by krausv** [comment]
Thanks for your response. 

I tried the latest version, but it still same.

EDIT:
I found, that bluescreen was opening in current modal window. So if I press escape (close modal) and then open bluescreen with 
![](https://cloud.githubusercontent.com/assets/5638224/15461469/6c6ba910-20bb-11e6-8c41-3009dd7df77e.png)
everything works fine

**Comment by dg** [comment]
Can you send somewhere example? On github etc

**Comment by dg** [comment]
ping @krausv

**Comment by krausv** [comment]
Sorry for long response :(.

I can't reproduce this error on clear sandbox. But on latest revision of Tracy this problem was disappear.

I apologize for unnecessary topic and thanks for your investigation! :)
