### ISSUE TITLE
Panel height needs to not exceed the height of the viewport

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#184]
This can easily become a problem when you have the console open and a panel has a lot of height. The panel needs to be resized to fit, which then triggers scrolling on tracy-inner.

At the moment it's impossible to see all the content as the panel just overflows off the viewport.

**Comment by JanTvrdik** [comment]
That's seems more like a problem with specific panel. Can you post more specific example?

**Comment by adrianbj** [comment]
I don't think it is panel specific - you can replicate with the System Info panel
![screen shot 2016-05-20 at 7 21 42 am](https://cloud.githubusercontent.com/assets/871211/15430773/9eb7f52a-1e5b-11e6-9b4f-434623008293.png)

Obviously I have set an extremely small viewport height for this, but for panels with more content this happens easily with the browser dev console set to a normal height.

I have quickly hacked around this by setting the height for certain custom panels and a percentage max-height which triggers the scrolling of tracy-inner. This kinda works, but it really needs a core JS solution so that the height of the panel can fit the content if there is enough viewport height.

I might find some time to work on a proper solution at some point but I haven't had a good look through  bar.js yet.

**Comment by JanTvrdik** [comment]
This sort-of fixes the problem, but it is not nice and there are likely edge cases it does not handle.

~~~js
window.addEventListener('resize', function () {
	forEach(document.querySelectorAll('#tracy-debug .tracy-mode-float'), function (panel) {
		var inner = panel.querySelector('.tracy-inner');
		var padding = panel.offsetHeight - inner.offsetHeight;
		inner.style.maxHeight = Math.min(document.documentElement.clientHeight - padding, 500) + 'px';
	});
});
~~~

**Comment by adrianbj** [comment]
Thanks - a couple of thoughts. 

1. I think a little bit of a margin top and bottom of the panel would be nice.
2. It also needs to be triggered on document ready, not just resize, because when developing you often have the console open while reloading a page. Currently you need to trigger a window resize to get the panels to fit.

**Comment by dg** [comment]
Possible solution https://github.com/nette/tracy/pull/188

**Comment by adrianbj** [comment]
Thanks - this seems to work well. My only suggestion is to prevent the bottom of the panels from being covered by the debug bar.

**Comment by adrianbj** [comment]
Just a quick follow up on this - maybe not the most appropriate place to post, but didn't think it was worth opening a new issue. The following are some additional rules I am applying that helps solve a few things. It lets panels take up as much height as needed when viewport height allows. It also prevents the horizontal scrollbar unless needed - this means that panels with logs and the like can take up the width of the viewport if needed, but still become scrollable if the viewport is narrow. The `#tracy-debug h1` declaration makes the entire width of the panel title draggable.

Anyway, I hope you find some things in here that you think are useful for the core.

```
                #tracy-debug h1 {
                    max-width: calc(100vw - 40px) !important;
                }

                .tracy-inner {
                    max-height: calc(100vh - 85px) !important;
                    max-width: calc(100vw - 40px) !important;
                    padding-right: 30px !important;
                }

                .tracy-inner p {
                    font-size:15px !important;
                }

                #tracy-debug pre.tracy-dump {
                    padding: .4em 2em .4em .7em;
                }

                .tracy-inner td {
                    word-wrap: break-word;
                }

                .tracy-inner td.tracy-force-break {
                    white-space: pre;           /* CSS 2.0 */
                    white-space: pre-wrap;      /* CSS 2.1 */
                    white-space: pre-line;      /* CSS 3.0 */
                    white-space: -pre-wrap;     /* Opera 4-6 */
                    white-space: -o-pre-wrap;   /* Opera 7 */
                    white-space: -moz-pre-wrap; /* Mozilla */
                    white-space: -hp-pre-wrap;  /* HP Printers */
                    word-wrap: break-word;      /* IE 5+ */
                }
```
