### ISSUE TITLE
$maxDepth and $maxLen not working for FireLogger

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#195]
Not sure if maybe I have something configured incorrectly, but it looks like defining these as per the docs, eg:
```
Debugger::$maxDepth = 5; // default: 3
Debugger::$maxLen = 200; // default: 150
```
doesn't populate the values for `FireLog()` calls. Not sure if they should be separately defined, like: `FireLogger::$maxDepth = 5;` or if the Debugger setting should also be used in the FireLogger class. 

Note that in the FireLogger class it is actually `$maxLength`, not `$maxLen`

A little OT, but I wonder if it might be nice to be able to define these on a per call basis, eg:
```
Debugger::FireLog($myArray, 5, 200);
```
Same goes for dump and barDump. I actually think this would be very useful - it's good to keep depth/len low by default, but sometimes you need more - it would be great to be able to do this on a case by case basis! If you think this would be worthwhile and want a new issue for it, let me know and I'll open one up.

**Comment by dg** [comment]
This are (now) defaults only for dump() and barDump()

```
Debugger::$maxDepth = 5; // default: 3
Debugger::$maxLen = 200; // default: 150
```

These are for FireLogger

```
Debugger::getFireLogger()->maxDepth = 5; // default: 3
Debugger::getFireLogger()->maxLength = 200; // default: 150
```

And I have added options for BlueScreen too https://github.com/nette/tracy/commit/e79e3dd735e5e5ff4f9602b27045f296e17d0095.

**Comment by adrianbj** [comment]
Thanks for fixing up maxLen vs maxLength and for the heads up of defining these for FireLog() calls and also adding the option for making them configurable for the bluescreen as well!

> It is not understandable that 5 and 200 in Debugger::FireLog($myArray, 5, 200); means maxDepth and maxLength.

Sure - I agree - what about:
 ```
Debugger::FireLog($myArray, array('maxDepth' => 5, 'maxLength' => 200);
```
I actually find I come across this quite often - it's too slow to have the value set high all the time, but I often want to see deeper levels in arrays.
