### ISSUE TITLE
Tracy doesn't work when packed inside a phar

### ISSUE THREAD

**Issue by mvrhov** [nette/tracy#196]
I have a tracy in my project which is distributed as phar. And whenever the exception occurs the stacktrace doesn't appear. Because tracy cannot find the templates to render them.

**Comment by JanTvrdik** [comment]
This is hopefully already fixed in master https://github.com/nette/tracy/pull/193 https://github.com/nette/tracy/commit/f44d82cd548f514021b608d8b590ed372165d161

**Comment by mvrhov** [comment]
You misread my report. I said it fails because it's unable to find the templates. Your PR fixes the generation problem of your phar builder.

**Comment by mvrhov** [comment]
This is in exception.log
> Compile Error: require(): Failed opening required 'phar:///path/to/pahar/weather.phar/lib/vendor/tracy/tracy/src/Tracy/assets/BlueScreen/bluescreen.phtml' (include_path='.:/usr/share/php:/usr/share/pear') in phar:///path/to/pahar/weather.phar/lib/vendor/tracy/tracy/src/Tracy/BlueScreen.php:66  @  CLI: /srv/weather/weather.phar cloud:weather  @@  exception--2016-05-28--10-33--432a77122e.html

**Comment by mvrhov** [comment]
Ah forget it. My phar doesn't contain those files..
