### ISSUE TITLE
Only one AJAX request displayed

### ISSUE THREAD

**Issue by patrickkusebauch** [nette/tracy#199]
Hello,
I upgraded to the latest Tracy version all excited for the new AJAX call functionality.

However it seems from testing in my application (and the example code in source), that only one bar is displayed at the time with the latest AJAX call.

It would be useful if all AJAX calls in the bar lifecycle (one full page reload) could be displayed. However I can understand that this might not be feasible for everybody. I imagine 2 camps:
1. AJAX request are used sporadically to load "time expensive" resources on the site. It might even be several of those calls are sent in parallel. There the need for "bar AJAX history" would be invaluable.
2. AJAX request are used for traversing the website. If possible traversing is not done by full page reload but by redrawing the outdated content (like Nittro). There "bar AJAX history" would unimaginably clutter the bar panel. 

Right now, the implementation favors the second camp. I am interested whether the support for the first camp is in mind or maybe that I just used the bar incorrectly.

**Comment by dg** [comment]
There is important that the man when see 10 ajax bars know which belongs to what request. Which means invent some improved interface.

**Comment by patrickkusebauch** [comment]
I can imagine that the AJAX request URL will be shown (and maybe some additional info) while hovering over the word "AJAX".

**Comment by radmax** [comment]
Request URL is in router panel, why not just add more lines, like with redirects. Max number of AJAX bars should be configurable with some good default value (~3). Bars could also be closed or collapsed.

**Comment by patrickkusebauch** [comment]
I am still open to actually implementing something if we can agree upon how it should look like.

**Comment by dg** [comment]
closed by #341
