### ISSUE TITLE
Production mode with strict mode enabled catch an notice or warning, application won't die

### ISSUE THREAD

**Issue by Reemoncs** [nette/tracy#202]
When production mode with strict mode enabled catch an notice or warning, application won't die only log those notices and warnings.

**Comment by dg** [comment]
In production mode has strict mode no effect.

**Comment by Reemoncs** [comment]
Ok, thanks for reply, but would it be possible to add some feature like that? I kind of rely on the fact that no warnings or notices can happen, so when some occure It would be preferable for my app to die rather than just log.

**Comment by dg** [comment]
It is IMHO more appropriate solve it via converting errors to exceptions: 

```php
Tracy\Debugger::enable();

$prev = set_error_handler(function ($severity, $message, $file, $line) use (& $prev) {
	if (($severity & error_reporting()) === $severity) {
		throw new ErrorException($message, 0, $severity, $file, $line);
	}
	return call_user_func_array($prev, func_get_args());
});
```
