### ISSUE TITLE
CSS styles rewrite by website

### ISSUE THREAD

**Issue by JanGalek** [nette/tracy#206]
Tracy debug bar content is rewrited by styles css of website, for example I have h background orange, and System info h have too orange, it looks bad, here is preview: 
![tracy_css](https://cloud.githubusercontent.com/assets/13171542/16374986/5a4f90b6-3c59-11e6-8870-2cc509cbe647.jpg)

When I will have some time, I can fix it if you want.

**Comment by dg** [comment]
FIx is welcomed.

**Comment by JanGalek** [comment]
Ok, fast test for this is add to style this:

`h1 {
    background: orange !important;
}`

fix will be soon ;)
