### ISSUE TITLE
BlueScreen does not survive error in panels

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tracy#208]
Errors caused when rendering custom panels are handled in Bar but not in BlueScreen.

**Comment by dg** [comment]
I do not understand what you mean.

**Comment by JanTvrdik** [comment]
[with error suppression](https://github.com/nette/tracy/blob/836121d8f179fafdcfec18f389f4c4fd9f3a57e1/src/Tracy/Bar.php#L139)
[without error suppression](https://github.com/nette/tracy/blob/836121d8f179fafdcfec18f389f4c4fd9f3a57e1/src/Tracy/assets/BlueScreen/content.phtml#L62)

---

BlueScreen template does not wrap `call_user_func($panel, $ex)` with try-catch, therefore any exception thrown by a penl will prevent the bluescreen from beeing rendered.

**Comment by JanTvrdik** [comment]
Thank you!
