### ISSUE TITLE
ajax requests are not recorded when the request url is "//test.com/" and the location.origin is "http://test.com" 

### ISSUE THREAD

**Issue by wppd** [nette/tracy#209]
as the title says,

when the ajax request url is `//test.com/some-ajax-url` and the location.origin is "http://test.com", it won't be working.

https://github.com/nette/tracy/blob/master/src/Tracy/assets/Bar/bar.js#L393

    if (window.TracyAutoRefresh !== false && arguments[1].indexOf('//') < 0 || arguments[1].indexOf(location.origin + '/') === 0) {
				this.setRequestHeader('X-Tracy-Ajax', header);
			}

it'll be working if change to `arguments[1].indexOf('//') <= 0`

**Comment by patrickkusebauch** [comment]
Can you please write a PR for it if you already know the fix for the issue?
