### ISSUE TITLE
Tracy is unexpectedly dependent to php-xml extenstion

### ISSUE THREAD

**Issue by jakubboucek** [nette/tracy#212]
From PHP 7 is Tracy **unexpectedly** dependent to `php-xml` extenstion (is [using](https://github.com/nette/tracy/blob/master/src/Tracy/Dumper.php#L424) function `utf8_decode()`. 

It is [probably problem only with](https://lists.debian.org/debian-devel/2016/04/msg00168.html) @oerdnj 's [PPA packages](https://launchpad.net/~ondrej/+archive/ubuntu/php). Really i don't know if is that _fskutečnosti_ relevant to Tracy, but that PPAs are very popular (only one trust source for builded & updated PHP on Ubuntu) and Nette should be verify availability of extension in [composer.json](https://github.com/nette/tracy/blob/master/composer.json).

I can send PR, please only confirm I am thinking right.

**Comment by dg** [comment]
Isn't it better to fix PPA package?

**Comment by jakubboucek** [comment]
I mean it's not a bug but feature (make it basic package lighter). Maybe similar reason why you splitted Nette to few packages.

Or exists anywhere list of packages standardly turned-on in a base PHP build? If is, it can be good argument for @oerdnj to add distinct note about differences compared to the standard.

**Comment by oerdnj** [comment]
There's nothing to fix in the PPA.

**Comment by Majkl578** [comment]
By the way, this also applies to next Debian, not only the mentioned PPA.
Also ext-json is undeclared by nette/tracy. Also there is hidden dependency in required nette/di package on ext-tokenizer.

**Comment by dg** [comment]
PHP extension `session` is disabled in PPA too?

**Comment by jakubboucek** [comment]
Thanks!
