### ISSUE TITLE
ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#214]
I get this error when PHP's output_buffering is set to 0, which seems to be quite common on shared hosts.

I think it is likely related to this: http://php.net/manual/en/function.ob-get-level.php#109001 and the fact that `ob_get_level` returns one at the beginning of the script.

The error comes from this line: https://github.com/nette/tracy/blob/master/src/Tracy/Debugger.php#L436

Let me know if you have any trouble reproducing - it may only be occurring because I am manually calling `Debugger::shutdownHandler()` from another script.

**Comment by dg** [comment]
There is @, so it should not produce rror.

**Comment by adrianbj** [comment]
Sorry for the delay in replying - I was on vacation last week.

It doesn't produce the error with the @, but the problem is that it still results in a blank page being returned. I can fix it by replacing:
```
while (ob_get_level() > self::$obLevel) {
```
with
```
while (ob_get_level() > 1) {
```
here: https://github.com/nette/tracy/blob/master/src/Tracy/Debugger.php#L430

I am not sure if that is the correct/appropriate solution, but it is the only way I can seem to prevent a blank screen from being returned in certain situations.

Is there any other info I can provide?

**Comment by dg** [comment]
Can you describe in which situations is returned blank screen? Because setting output_buffering = 0 is fine.

**Comment by adrianbj** [comment]
Ok, I have tracked it down (I think), although it may be a little tricky for you to replicate. The problem only occurs when I manually call `Debugger::shutdownHandler()` which I have do for a specific situation - can explain more if you want. Now the other thing required to cause the blank screen is to do a header location redirect and call `exit` on the line after the header call. If I remove that `exit`, then it works fine.

Does that give you enough insight to work from? If not, let me know and I'll set up a site so you can test.

Thanks!

**Comment by adrianbj** [comment]
@dg - would you consider adding:
```
if(!ob_get_level()) ob_start();
```

just before this line:
https://github.com/nette/tracy/blob/577c63b947c9b97ecbe6698999d06c28fc6bd12c/src/Tracy/Debugger.php#L149

This is in line with what is suggested here: http://php.net/manual/en/function.ob-get-level.php#109001

It seems to fix everything at my end. Can you see any possible side-effects?

**Comment by dg** [comment]
`ob_start()` is not good idea, because it blocks server output until connection is closed. 

Simply, I don't understand where is problem, so I am unable to solve it.

**Comment by adrianbj** [comment]
> ob_start() is not good idea, because it blocks server output until connection is closed.

Good point!

OK, I'll try to explain in more detail. It all relates back to this issue: https://github.com/nette/tracy/issues/185

In my last comment you'll see that I am now calling `Debugger::shutdownHandler()` before my script shuts down so I can get the AJAX bar to work. Without that, the AJAX bar doesn't show. The side-effect of calling `Debugger::shutdownHandler()` however is the problem described in the issue where I get a blank page because of the `Debugger::removeOutputBuffers` method.

Maybe manually calling `Debugger::shutdownHandler()` messes with the integrity of `self::$obLevel`? 

I do know that if I add 1 to the value of `self::$obLevel` then everything works just fine.

**Comment by adrianbj** [comment]
I am getting:

before enable: 0
after enable: 0
before shutdown: 1
after shutdown: 0

**Comment by adrianbj** [comment]
```
    [0] => Array
        (
            [name] => default output handler
            [type] => 0
            [flags] => 112
            [level] => 0
            [chunk_size] => 0
            [buffer_size] => 16384
            [buffer_used] => 0
        )
```

**Comment by dg** [comment]
So after `enable()` you code started an output buffer, `shutdownHandler()` flushes and closes it (via `ob_end_flush()`). 

This should not produce `ob_end_flush(): failed to delete and flush buffer.`. because buffer existed and was closed.

At the same time, it should not result in a blank page, because it is flushed.

So I'm stuck :-)

For what purpose do you use the buffer? Page cache? 

You can try to render Bar this way instead of calling shutdownHandler:

```php
Debugger::getBar()->render();
Debugger::$showBar = FALSE;
```

**Comment by adrianbj** [comment]
> For what purpose do you use the buffer? Page cache?

I believe the issue is starting here: https://github.com/processwire/processwire/blob/50f2834a0ae2a9f9f2ac53439184ebdc04db2f54/wire/core/admin.php#L89

Removing that ob_start() does fix things, but it also seems like your solution of:
```
Debugger::getBar()->render();
Debugger::$showBar = FALSE;
```
instead of calling the shutdown handler also works, so thank you very much for that!

Just an FYI - as I think I mentioned in that other issue, all of this is only problem when using that SessionHandlerDB module: https://github.com/processwire/processwire/blob/50f2834a0ae2a9f9f2ac53439184ebdc04db2f54/wire/modules/Session/SessionHandlerDB/SessionHandlerDB.module

**Comment by adrianbj** [comment]
Sorry to bring this up again @dg - maybe I should have started a new issue, but since it only seems to affect me, I thought it better to add here. I just noticed that even though:
```
Debugger::getBar()->render();
Debugger::$showBar = FALSE;
```
gets the AJAX bar working, it doesn't get the Redirect working. Again this is only an issue with that SessionHandlerDB module. 

It might be good to note that I am having to add:
```
if(ob_get_level() == 0) ob_start();
```
before those two lines, otherwise php header redirects don't work at all unless php.ini has output_buffering on by default.

Any thoughts on what might be preventing the Redirect bar from working?

Here is what a dump of $_SESSION['_tracy'] looks like:

with SessionHandlerDB off:
![screen shot 2017-02-13 at 11 54 29 am](https://cloud.githubusercontent.com/assets/871211/22900445/3a75e034-f1e3-11e6-8cea-eb3e0d40e835.png)

and with it on:
![screen shot 2017-02-13 at 11 53 50 am](https://cloud.githubusercontent.com/assets/871211/22900444/3a74053e-f1e3-11e6-8d5c-c7950cd0c0f7.png)

These are on exactly the same page after the same redirect. I don't know why the redirect index is NULL and the bar index has three items.

I don't want to take up anymore of your time on this, but if you have any quick ideas of why it might be happening, that would be greatly appreciated.

Thanks!
