### ISSUE TITLE
Debug bar breaks Xdebug session when redirect occurs

### ISSUE THREAD

**Issue by richard-ejem** [nette/tracy#216]
Scenario:
* use Tracy\Debugger::enable() and place it after a possible redirect (i.e. to a language-specific url, like http://example.com/ -> http://example.com/en; should not happen in Nette application with standard bootstrap, happened to me in Drupal project using Tracy)
* the redirect occurs when loading Tracy assets (like http://example.com/?_tracy_bar=js&v=2.4.2&XDEBUG_SESSION_STOP=1&XDEBUG_PROFILE=0&XDEBUG_TRACE=0 is redirected to http://example.com/en?_tracy_bar=js&v=2.4.2&XDEBUG_SESSION_STOP=1...
* problem: header_remove('Set-Cookie') is not called from Bar.php when the redirect occurs and the cookie XDEBUG_SESSION=deleted gets into browser

I've proposed a simple solution printing at least console warning to confused developers like me, who would be investigating for hours why XDEBUG stops after first request, will pull request it in a second :)

**Comment by richard-ejem** [comment]
Thanks to @JanTvrdik for commenting original pull request, I just found even simpler way to detect and fixed the pull request with a single simple commit :)

**Comment by dg** [comment]
What about this 6a24bb67ce63a072c81a906b13014131e6458fd2?

**Comment by richard-ejem** [comment]
@dg unfortunatelly not helping, tested on my project :( I will provide some minimal case to reproduce the problem soon

**Comment by dg** [comment]
It closes XDEBUG session, but it should close it only once.

**Comment by richard-ejem** [comment]
Take a look at this MWE: https://github.com/richard-ejem/tracytest
try debugging it in browser, debugger stops working after removing the XDEBUG_SESSION_START argument from URL.

**Comment by dg** [comment]
I see, dispatchContent() is not loaded…

**Comment by richard-ejem** [comment]
ok so maybe please re-open the issue?
My suggested fix was just to notify users about the problem, as any redirect before Debugger::enable() when XDEBUG_SESSION_STOP is passed will cause this problem.
Just checked sources of Xdebug, there seems to be no way to stop Xdebug for a single request without destroying the cookie.
Other solution would be to create pull request for Xdebug to add something like XDEBUG_SKIP=1 which would disable Xdebug just for the single request, but it will take long to be merged and downloaded by most users.

**Comment by richard-ejem** [comment]
But there is still one edge case where it can cause problems, see current https://github.com/richard-ejem/tracytest .
In short:

* I do a state-changing action on some URL (add stuff to cart)
* it happens before Debugger::enable()
* I forget to redirect after that action

Would be my bad, that I didn't place a redirect on state-changing URL, but I will really wonder why 4 items are added to my cart instead of 1.

This is merely hypothetical, but maybe should still be considered as a debug tool should cause minimum possible side effects.

**Comment by dg** [comment]
This tool must be simply called first in script, otherwise it is not used correctly. I really dont know how handle these cases.

**Comment by dg** [comment]
I'm thinking that might be a better solution is yours, just write out a warning.
