### ISSUE TITLE
Debugger::enable regex change for Amazon S3 storage

### ISSUE THREAD

**Issue by poliak9** [nette/tracy#220]
Is there a specific reason why the regex `#([a-z]+:)?[/\\\\]#Ai` that is checking if `$logDirectory` is a valid dir doesn't have numbers in the protocol part?

When on AWS using the [AWS SDK for PHP](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/index.html), you can use [S3 stream wrapper](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-stream-wrapper.html) for accessing files in S3 via built in functions of PHP (`fopen`, `file_get_contents`, ...). This is needed in order to save logs from an app running on Elastic Beanstalk, since your app can be placed on new VM anytime and thus the local storage on your current VM isnt really "persistent". But this way of storing log files isn't possible, because the location "s3://<bucket>/log" isn't valid by the regex that is checking whether it is a valid location.

So what about changing the regex to accept numbers as well?

Clarification: can't use native logging from Tracy

**Comment by poliak9** [comment]
So even if I change it manually (so Tracy accepts it as legit location), logging doesn't work. I can write to the bucket with fpc etc., but Tracy just doesn't log.

**Comment by dg** [comment]
Why it doesn't log?

**Comment by poliak9** [comment]
I have no idea.
The stream wrapper is working and the app creates files in that bucket just fine, only Tracy doesn't make log files.
