### ISSUE TITLE
Ajax bar not working since #9dd9ebf90df

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#228]
https://github.com/nette/tracy/commit/9dd9ebf90dff48366a0c958c5311dc42e80eef68 breaks it for me. Any thoughts on why it would have stopped working? As soon as I revert to the previous commit it works as expected.

Thanks.

**Comment by dg** [comment]
Browser, version, any error in console?

**Comment by adrianbj** [comment]
I have tested Chrome and Safari - no console / network errors and the css and js files are showing up in Local Storage and everything on the non-ajax bar is working correctly so those files must be being used.

**Comment by dg** [comment]
Has anything changed in the headers/content of requests and responses, which it sends for AJAX bar?

**Comment by dg** [comment]
(I have tested it IE 11, IE Edge, Chrome, Firefox and it works correcty, so I have no ideas whats wrong).

**Comment by adrianbj** [comment]
I have discovered that it's not all ajax requests - some still work fine with the new version of Tracy. Will see if I can figure out why some work and some don't.

**Comment by adrianbj** [comment]
Ok, I just did a little investigation and it's a problem with $contentId being set. Obviously not the correct solution, but changing: https://github.com/nette/tracy/blob/9dd9ebf90dff48366a0c958c5311dc42e80eef68/src/Tracy/assets/Bar/loader.phtml#L36

from: `<?php if ($contentId): ?>` to `<?php if (!$contentId): ?>` gets the AJAX bar working again for all calls, so I think this is probably similar in nature to: https://github.com/nette/tracy/issues/185 but this time I am not using the database session handler and still having the problem.

Still there must be some session start/close issue that wasn't a problem prior to the mentioned commit.

**Comment by dakorpar** [comment]
I have the same problem, not sure which commit caused it but since I upgraded to 2.4.3 I mostly don't get bar at all, when on 2.4.2 I always get bar....

**Comment by dg** [comment]
@dakorpar are you talking about AJAX bar, or about whole bar?

@adrianbj if I understand you see all AJAX bars when Tracy is initially loaded via code `Tracy.Debug.init(…)` and is only some of AJAX bar when is loaded via code `create('script', {src: "?XDEBUG_SESSION_STOP=1&_tracy_bar=content.***"});
`, right?

**Comment by dakorpar** [comment]
@dg bar is not displayed at all for me on several project on most of the pages in 2.4.3, it works good in 2.4.2, also I noticed it's showed more often in IE then in Chrome, but still not always
I'm using newest version of nginx, php 7.0.11...

**Comment by dg** [comment]
@dakorpar  Wrong configuration? https://github.com/nette/tracy/issues/229#issuecomment-251109539

**Comment by dakorpar** [comment]
@dg nope, doesn't work for me even in root of domain (homepage), and I don't have error there.
Also I've set vhost try_url to your proposal, doesn't fix the problem (I restarted nginx ofc...)
this code is visible on end of the page:
![screenshot_5](https://cloud.githubusercontent.com/assets/9303856/19163744/7e7d4aa2-8bfd-11e6-842d-ba270b9be928.png)

this is ajax request data, response is empty: 
![screenshot_5](https://cloud.githubusercontent.com/assets/9303856/19163687/450e5e78-8bfd-11e6-8348-0d8040f23650.png)

In console there are only error for missing images since images are only on production server...

Maybe I should open new issue or is this maybe same problem?
All works perfectly as soon as I downgrade to 2.4.2, but in 2.4.3 does not work...
In two projects for me, in third it works...

**Comment by dg** [comment]
Both pictures are the same.

**Comment by dg** [comment]
You should see this:

HTML code a)
![image](https://cloud.githubusercontent.com/assets/194960/19164464/5b0c4ec6-8c00-11e6-8fb6-271f37c40400.png)

or HTML code b)

![image](https://cloud.githubusercontent.com/assets/194960/19164505/8597be64-8c00-11e6-9cf1-dbdc7452732c.png)

These requests that returns javascript code (`_tracy_bar=assets` is cached in localStorage, so it is present only first time)

![image](https://cloud.githubusercontent.com/assets/194960/19164597/f11297d6-8c00-11e6-9619-fe658047f9f3.png)

These additional requests on AJAX calls:

![image](https://cloud.githubusercontent.com/assets/194960/19164696/5656bcc6-8c01-11e6-9f15-102ae832aa39.png)

**Comment by dakorpar** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/9303856/19165427/088cec6a-8c04-11e6-9798-cf02c1b3d379.png)
sorry wrong picture selected... this is the other one on end of page I don't have this init...

**Comment by dg** [comment]
@dakorpar @adrianbj Have you found a reason why it does not work?

**Comment by dakorpar** [comment]
I believe it's working now for me, although I'm not sure why.

**Comment by dg** [comment]
So can I close it?

**Comment by adrianbj** [comment]
Sorry for the silence here - been busy and then away on vacation. Just catching up with things now. I'll try to update in the next couple of days, but I do think there is still a problem - I will try to narrow it down to something reproducible for you.

**Comment by adrianbj** [comment]
It seems like it's an issue of the scripts not being loaded from local storage in time for document ready. All user initiated ajax calls work fine, but not those called automatically.

If I add a timeout of about a second then ajax calls made inside `$(document).ready` also start working, eg:

```
$(document).ready(function() {
	setTimeout(function(){
		ProcessPageListInit();
	 }, 1000);
});
```

but without the timeout, the AJAX bar (and the redirect bar) don't ever load.

Hope that helps.

**Comment by adrianbj** [comment]
@dg - is that extra info enough for you to track down, or do you need more? I have to admit I don't really understand why the main bar is loading and the ajax one isn't, but that delay makes all the difference. The version prior to that https://github.com/nette/tracy/commit/9dd9ebf90dff48366a0c958c5311dc42e80eef68 works fine without the delay.

**Comment by dg** [comment]
Currently I don't have free time, I'll look at it later.

**Comment by dg** [comment]
So problem is related to ajax calls called inside document-ready, now I understand. In this the previous and current versions are really different, I'll try to find a solution.
