### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by andering** [nette/tracy#229]
Hello,
since [this commit](https://github.com/nette/tracy/commit/b0845f5a9ef014fdbdd6bcc912a295bdf7fa87e1) I'm getting this `Uncaught SyntaxError: Unexpected token <` error. When i'm not in root of the domain.

it occurs in this function:
```
	function create(name, props) {
		var el = document.createElement(name);
		for (var id in props) {
			el[id] = props[id];
		}
		document.head.appendChild(el);
	}
```

if this is called :
```
create('script', {src: "?_tracy_bar=content.b50ec4f179"});
create('script', {src: "?_tracy_bar=assets&v=2.4.3", onload: start});
```

it's fixed if i change in Bar.php file this line:
`$baseUrl = extension_loaded('xdebug') ? '?XDEBUG_SESSION_STOP=1&' : '?';` 
to this line
`$baseUrl = extension_loaded('xdebug') ? '/?XDEBUG_SESSION_STOP=1&' : '/?';`

But i guess i could miss something in configuration what's make this tracy "script src urls" accessible only from root domain. (i don't use xdebug)

Thanks for fix or help.

**Comment by dg** [comment]
It seems like wrong server configuration. Do you use Apache or nginx?

**Comment by andering** [comment]
nginx

**Comment by dg** [comment]
If there is something like 

```
try_files $uri $uri/ /index.php;
```

it should be 

```
try_files $uri $uri/ /index.php$is_args$args;
```

**Comment by andering** [comment]
Thank you, it fixed problem.

**Comment by dg** [comment]
How to check that server is configured properly:

1) put `<?php var_dump($_GET);` in beggining of script (index.php etc)
2) open in browser URL with parameters, **not** in root of the domain, ie `http://myweb.dev/subdir/?a=1&b=2`
3) check if parameters are dumped

**Comment by PSzabo** [comment]
I have same problem with tracy in new Nette version.

**Comment by dg** [comment]
And solution didn't work?

**Comment by AlmightyOatmeal** [comment]
What worked for me was editing my nginx config and changing:
```
        location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|swf)$ {
            try_files $uri /index.php$uri$is_args$args;
            access_log off;
        }
```

To:
```
        location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|swf|js)$ {
            try_files $uri /index.php$uri$is_args$args;
            access_log off;
        }
```

Note that I added `|js` to the location expression.

**Comment by the-last** [comment]
@dg 666

**Comment by mskocik** [comment]
@AlmightyOatmeal Could you post whole your whole config? It seems I'm missing something to make it work.

**Comment by ansh1221** [comment]
Hi Sir,

I have been configuring my Keyrock with nginx since long time and am not able to do so,

My Nginx conf is as follows:
I wanted to access keyrock idm using nginx reverse proxy. But while doing so, nginx is unable to load the css and js files.

    location /idm/{

    proxy_pass           https://keyrock-host:keyrock-port/;
    proxy_set_header   X-Forwarded-Host    $host;
    proxy_set_header    Host                $host;
    proxy_set_header    X-Real-IP            $remote_addr;
    proxy_set_header    X-Forwarded-For        $proxy_add_x_forwarded_for;
    }

I am facing the following issues:
![image](https://user-images.githubusercontent.com/39158645/55014769-92daf500-5011-11e9-8440-91981b7f54b4.png)

----------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/39158645/55014825-aab27900-5011-11e9-97bc-29bdc8989cc9.png)


I would request you guys can help me out for integrating keyrock with nginx.
Thank you so much!
