### ISSUE TITLE
Big session file

### ISSUE THREAD

**Issue by Trejjam** [nette/tracy#231]
Hi,

I search time bottle-neck of our application. I found, that Tracy store panel in session (session loading is 20% of run time). Is it necessary?

**Comment by JanTvrdik** [comment]
This should not happen in production mode. Are you talking about speed on localhost?

**Comment by Trejjam** [comment]
Yes, I test it on localhost. On production it could occurs if you use client certificate for detect developer(s). Of course they can live with that.

**Comment by JanTvrdik** [comment]
@Trejjam Speed of debug bar on localhost mostly depend on the number and complexity of panels you have enabled. Do you really need to see all of them all the time?

If session loading on localhost is slow, use faster storage than disk.

**Comment by Trejjam** [comment]
I think about it. Thank you for support

**Comment by JanTvrdik** [comment]
@Trejjam Can we close this issue then? Or how else can we help you?
