### ISSUE TITLE
Notices from ajax calls being captured/suppressed

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#233]
I have an ajax image upload script that should fail because of a PHP notice which is returned, but when Tracy is enabled, it is capturing / suppressing the notice which means that the response of the AJAX call is the json without the notice. It might be ok if the notice was reported in the Errors panel, but it's not even doing that.

Btw, this is not specific to my server setup/install - it was reported to me from someone else on a completely different site.

Let me know if you are having troubles reproducing and I'll give you access to a site that demonstrates it in action.

BTW, this is not related to https://github.com/nette/tracy/issues/228 because I am using the version of Tracy from before that commit.

**Comment by adrianbj** [comment]
A little more info on this - the notice is being sent to the browser console which is nice, but I would expect it to trigger the AJAX bar and populate the Errors panel, but it isn't doing this.

**Comment by dg** [comment]
If you could prepare example, that would be great.

**Comment by adrianbj** [comment]
> Is error logged in log file?

No, it's not logged.

This simple test case shows the issue for me:
```
$( document ).ready(function() {
	$.getJSON( "test.php", function(data) {
		console.log( "success" );
		console.log(data);
	})
	.done(function() {
		console.log( "second success" );
	})
	.fail(function() {
		console.log( "error" );
	})
	.always(function() {
		console.log( "complete" );
	});
});
```

where test.php contains:
```
<?php
// code for including and enabling Tracy debug bar
// I am not including here because I set this up through my module so it won't relevant for you,
// but it is critical that Tracy is enabled in the file called via ajax

//simple json response with triggered notice as an example
header('Content-type: application/json');
trigger_error("Test Notice", E_USER_NOTICE);
echo json_encode(array('one' => 'test', 'two' => 'this'));
exit;
```

This will result in successful output of the json in the console. If Tracy is not instantiated and enabled in the ajax called file, then it returns an error in the console as expected. In this example, the notice is actually shown in the AJAX bar Error panel as well, but in my full application I have a couple of instances where it isn't. 

The key thing is that because Tracy is hijacking that notice, it is resulting in "success", rather than "error" being returned, which I don't think it correct behavior.

Does that help to explain the situation better?

**Comment by dg** [comment]
From my point of view the current behavior is correct. The notice should not break output and result to 'error'. It is consistent with notices in common html page: they don't break output and are shown in debug bar.

**Comment by adrianbj** [comment]
I see your point, but I guess I think a little differently. I don't think Tracy should allow something to work without error when it wouldn't is Tracy wasn't running. In the case of an AJAX call that is expecting a JSON response, if Tracy isn't running, the response would not be successful because of the PHP notice/warning and the script relying on the JSON data would not be able to proceed as expected. The way things stand if you have Tracy running everything will work correctly, but for users without access to Tracy (or when moving from dev to production), the script will fail. This seems like a bad situation to me because I can't trust my AJAX calls when Tracy is running.

Does that make sense?

**Comment by dg** [comment]
Notice is not fatal error and should not completely break response (whether it is JSON, image or HTML). So Tracy tries to prevent it, if there is another way to show it.

> if Tracy isn't running, the response would not be successful because of the PHP notice/warning and the script relying on the JSON data would not be able to proceed as expected.

Yes, but it is PHP "fail". Because on production it is successful. Successfulness should not be a matter of running environment.

> if you have Tracy running everything will work correctly

You should see big red label in debug bar which means that everything is not correct.

**Comment by adrianbj** [comment]
> Notice is not fatal error and should not completely break response (whether it is JSON, image or HTML). So Tracy tries to prevent it, if there is another way to show it.

I know a notice is not a fatal error, but when the notice is returned along with the json from an AJAX response, it can often break a script. This is different to a non-AJAX notice where it won't affect the completion of a script.

> Yes, but it is PHP "fail". Because on production it is successful. Successfulness should not be a matter of running environment.

I agree it shouldn't matter the environment. The problem is that when you change environment Tracy is no longer intercepting the notice from being included with the json response. Now that notice is again causing the script which consumes the json to fail.

> You should see big red label in debug bar which means that everything is not correct.
In my example above it does, but I have a more complex scenario (ajax image upload) where this doesn't show. This is the key problem. If the AJAX Error panel was completely reliable, it would be ok, but when it's not we start to have a problem because there is no obvious indication that Tracy has intercepted (and removed) the notice. 

Would a screencast be useful so you can see the problem in action - showing that the Errors panel does not get triggered and the AJAX response does not contain the notice anymore?

**Comment by dg** [comment]
Is possible that it is related to sessions stored in db?

**Comment by adrianbj** [comment]
> Is possible that it is related to sessions stored in db?

No, I don't have that enabled - it's just using normal PHP sessions

**Comment by adrianbj** [comment]
OK, so the problem is that the AJAX call in question is not using jquery and not manually sending the:
```
"X-Requested-With", "XMLHttpRequest"
```

request header. That is why the AJAX bar isn't being updated. Since I don't have control over the code that is sending this AJAX call, I think I am stuck at the moment. 

Is there any way Tracy can intercept notices/warnings without removing them from the response?

**Comment by adrianbj** [comment]
Oops - actually it is sending that request header. I am guessing the problem is that it isn't calling:
`getAllResponseHeaders()`

**Comment by dg** [comment]
As a workaround you can `unset($_SERVER['HTTP_X_TRACY_AJAX'])`

**Comment by adrianbj** [comment]
> As a workaround you can unset($_SERVER['HTTP_X_TRACY_AJAX'])

Thanks, but of course that kills the AJAX bar altogether which I don't want. 

I am going to see what I can do about getting the: `xmlhttp.getAllResponseHeaders();` added into those calls in the ProcessWire core. I just checked and with those in place, the AJAX bar Errors panel is triggered as expected. I still think it's unfortunate that the notice is removed from the AJAX response, but at least now there is some indication that the AJAX called script has a notice that needs fixing.

**Comment by dg** [comment]
This daded6c301e04c6bbd69440a65832e5ae513460f should solve problem with missing getAllResponseHeaders()

**Comment by adrianbj** [comment]
> This 4a00380 should solve problem with missing getAllResponseHeaders()

Thanks @dg - that seems to work great here!

I still think it is strange that the AJAX call now returns a "success" response, instead of "failure" just because of Tracy, but I am guessing there is nothing that can be done about retaining warnings/notices in the AJAX response as well as populating the Errors panel so I will close this issue. 

Thanks again for the fantastic support - much appreciated!
