### ISSUE TITLE
BUG - bad rendering of route panel in 2.4.5

### ISSUE THREAD

**Issue by petrparolek** [nette/tracy#242]
Bad rendering of route panel in Tracy 2.4.5
![tracy 1](https://cloud.githubusercontent.com/assets/6066243/22186777/8259a3f2-e0fb-11e6-9490-616df5cb874b.jpg)

**Comment by JanTvrdik** [comment]
Should be fixed in master https://github.com/nette/tracy/commit/9a85c210bd1d7ad8a8743af6afe26112cc329834

**Comment by petrparolek** [comment]
thanks,. it's working.
