### ISSUE TITLE
Tracy should not affect existing error handlers

### ISSUE THREAD

**Issue by jakubdibala** [nette/tracy#245]
I'm trying to use Tracy as additional PHP error handler, but Tracy is not restoring old error/exception handler. When `Tracy\Debugger::enable()` is called, error and exception handler are set, but previous error handlers are ignored. So when error occurs, Tracy is invoked, but previous error handler is not.

Thanks.

**Comment by adrianbj** [comment]
Even though I just closed it, I wonder if my suggestion here: https://github.com/nette/tracy/issues/279  would be useful?

It's related specifically to the shutdown handler, but maybe it's still a similar issue / need?
