### ISSUE TITLE
Speed / order of loading debug bar much slower than with 2.3

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#247]
This is part bug report and part feature request

### Description
I have noticed for a while that the loading of the debug bar is quite slow. Looking through a few of my sites, it takes 2-3 seconds after the DOM has loaded before it is displayed. It also prevents any document.ready JS on the site from being applied until after the debug bar is loaded.

The problem seems to only occur when I am loading some of my custom panels, but if I switch to the 2.3 branch of Tracy (with no other changes) the bar loads virtually immediately as the DOM finished loading. I thought it might be related to the lazy loading of panels not working anymore, but that wasn't introduced until 2.4.

So is it possible to speed it up back to at least close 2.3 speeds, and also is it possible to load it after other JS on the page so at least if there is a delay in loading, it doesn't affect page rendering.

Please let me know if you can't observe it at your end and I'll give you access to a site showing the problem.

### Steps To Reproduce
Switch between 2.3 and 2.4

**Comment by dg** [comment]
I don't use Tracy with as many panels as you, so I see no differences in speed. It can be caused by a lot of things. You can try this https://github.com/nette/tracy/issues/246#issuecomment-280949262

**Comment by adrianbj** [comment]
Unfortunately I don't see any improvement with that new method. I'll send you details for a site so you can see the difference between 2.3 and 2.4.

**Comment by JanTvrdik** [comment]
My very random guess is that the bottleneck is the speed of sessions, which are usually not designed to store large amount of data. Is is slow only on production server or on localhost as well?

**Comment by adrianbj** [comment]
Good point @JanTvrdik - the issue does only seem to appear on my production server. My local dev setup seems to be fine. Although I have seen and heard of issues on some user's local dev setups, but not many.

**Comment by dg** [comment]
Problem is that it takes ~7 seconds to load Tracy bar from server:

![image](https://cloud.githubusercontent.com/assets/194960/24075762/d35349ce-0c21-11e7-835a-562905a0cdda.png)

**Comment by adrianbj** [comment]
Yeah, I know it's taking a long time to load from the server. Do you have any thoughts on how we can have the speed of 2.3 with the other advantages of 2.4? I see that you played around with 2.3 so you have seen just how dramatic the difference is.

**Comment by jkuchar** [comment]
Soulution would be to not depend on php sessions in debug bar.

**Comment by dg** [comment]
@jkuchar it is not so easy https://github.com/nette/tracy/issues/154#issuecomment-200932863

**Comment by adrianbj** [comment]
@dg  - I wonder if it might be possible to have an optional reliance on $_SESSION. Maybe if you don't rely on another server / proxy it could use the old non session mechanism?

I am sometimes seeing up to 9 versions (with different contentIds) of the bar in $_SESSION['_tracy']['bar'] which in some cases is a huge amount of data.

Thanks for any thoughts on how this might be improved.

**Comment by dg** [comment]
@adrianbj this https://github.com/nette/tracy/commit/df51ad8e6dd6c7275483af57d3a7cd18d521296c may help, ie. `Debugger::$useSession = false;`

**Comment by adrianbj** [comment]
Thanks @dg - maybe, but disabling session breaks the AJAX bar (the main and redirect bars are fine). 

The other catch with that change is the setting `Debugger::$useSession = true` has the same effect as `Debugger::$useSession = false` because you are checking for null (instead of true/false) here: https://github.com/nette/tracy/commit/df51ad8e6dd6c7275483af57d3a7cd18d521296c#diff-5e7f8ef27b3f38a6ca4c9bd52cb9ed37R221

**Comment by dg** [comment]
Yes, AJAX is dependent on session and I do not know how to handle it differently.

`Debugger::$useSession` is initialized only when is null, I think it is correct.

**Comment by adrianbj** [comment]
> Yes, AJAX is dependent on session and I do not know how to handle it differently.

How does Tracy handle the redirect bars? - sometimes I see a couple of different ones show. Even if the AJAX bar needs sessions, perhaps the other ones could not use them which would keep the size of the session variable down?

The other option might be better cleanup of the session - perhaps performance would be better if multiple versions of the main bar never accumulated in the session variable. I don't actually know what results in multiple versions being stored, but when they are is when things really slow down.

**Comment by adrianbj** [comment]
> Debugger::$useSession is initialized only when is null, I think it is correct.

I thought it should be possible to explicitly set to true if you wanted, which isn't possible currently - setting to true is the same as setting to false.

**Comment by dg** [comment]
I see now. Repushed.

**Comment by adrianbj** [comment]
Thanks for the true/false fix. 

I have been testing on my live server where things were really slow with sessions and it's made a huge difference so thanks for that. The catch is that I am really going to miss the AJAX bar so not really sure what to do. I could maybe add a toggle to the debug bar so I can easily enable when I want it, but there's always the chance that I'll miss warnings/notices in AJAX requests which is one of the awesome things about that bar - you see things that would often never get displayed.

I see the issue with the AJAX bar now vs the redirect one, but trying to think of a better solution :)

**Comment by dg** [comment]
@adrianbj can you try this solution 9199ace26feb131aa43e201a59d2430904231f5b?

**Comment by adrianbj** [comment]
> @adrianbj can you try this solution 9199ace?

So far this looks to be brilliant - everything seems to be loading really quickly  - great job!

Even if there was a delay with the ajax bar loading, I don't think it would matter much because it isn't triggered on each page load, or even if there is an ajax request onload it loads the bar after the page has finished so you can interact with it before the bar is finished.

I'll monitor this for a little while longer and then close this issue if I don't see any side-effects.

Thanks again!

**Comment by dg** [comment]
Great. 

I just have to rename `useSession` to something else, because that session always uses. Perhaps `preferSession` or something similar.

**Comment by adrianbj** [comment]
What about `forceSession` ?

If I understand correctly the only reason you'd want to force session use is if you're dealing with content from another server/proxy - is that correct?

**Comment by dg** [comment]
Can you try last commit? It can be enabled via `Debugger::getBar()->preferSession = false;`

The difference is only if the initial Bar is rendered through the session or not.

**Comment by adrianbj** [comment]
New version also seems to be great!

I don't know all the factors here, but I would also think that having the default as `false` makes sense. It really does make a huge difference to page load times on some servers.

Thanks again for this - really awesome improvement :)

**Comment by dg** [comment]
I tried to make behavior similar to `preferSession = false;` as the default (the variable `preferSession` doesn't exist) and we will see if there is someone who does not suit it.

**Comment by adrianbj** [comment]
> I tried to make behavior similar to preferSession = false; as the default (the variable preferSession doesn't exist) and we will see if there is someone who does not suit it.

Sounds good - I am testing the latest version now and so far so good!
