### ISSUE TITLE
AJAX bar not working with document.ready() since commit cdd9777

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#250]
- bug report? yes
- feature request? no
- version: https://github.com/nette/tracy/commit/cdd9777066cda7be3193edc82720a75a55624a45

### Description
This seems to be very similar to this old issue: https://github.com/nette/tracy/issues/228 where the AJAX doesn't display when AJAX call is within document.ready()

As soon as I revert to the previous commit it works fine again.

**Comment by repli2dev** [comment]
This bug is interconnected with #246 as the Tracy is as of the cdd9777 commit loaded asynchronously (which is later in your case then document.ready()).
