### ISSUE TITLE
environment auto detection

### ISSUE THREAD

**Issue by jmbelloteau** [nette/tracy#251]
- bug report? no
- feature request? no
- version: 2.4.6

### Description

Actually I load manually a **dev.php** or a **prod.php** configuration file depending on the environment.

Tracy have a very nice environment auto detection feature and I would like too use it to load **dev.php** or a **prod.php** automatically.

Does someone have an idea?

Thank you  😄

**Comment by adrianbj** [comment]
If you have already loaded Tracy before you load dev.php or prod.php, you could check: `Debugger::detectDebugMode()`

If not, you could always copy the detectDebugMode function to your loading script.

**Comment by jmbelloteau** [comment]
Great !! Thanks for you rapid answer :)

**Comment by jmbelloteau** [comment]
I've found also this solution:

`$environment = $_SERVER['SERVER_ADDR'] === $_SERVER['REMOTE_ADDR'] ? 'dev' : 'prod';
`

But I'm not sure it will be has good for detection as Tracy?
