### ISSUE TITLE
Dumper::COLLAPSE_COUNT

### ISSUE THREAD

**Issue by Nix-id** [nette/tracy#252]
- bug report? no
- feature request? yes

### Description
Add ability for changing default value 7 for Dumper::COLLAPSE_COUNT

**Comment by dg** [comment]
Just pass own value to `Dumper::dump($val, [Dumper::COLLAPSE_COUNT => 10])`.

**Comment by Nix-id** [comment]
on each call?
useless

**Comment by dg** [comment]
Create your own function.
