### ISSUE TITLE
Tracy “hello world”

### ISSUE THREAD

**Issue by fabswt** [nette/tracy#257]
Hi there,

I'm new to Tracy. I'm confused as to how to get the debugger bar to show.

Here is what I've got:

	<!DOCTYPE html>
	<html>
	<head>
	<?php

	ini_set( "display_errors", 1 );
	require('vendor/autoload.php');
	use Tracy\Debugger;
	Debugger::enable();

	?>
		<title>Tracy: Hello, world</title>
	</head>

	<body>
	uhm-hum…

	<?php //bs(); ?>

	</body>
	</html>

The page renders just fine, sure, but I've got nothing there besides my own text. 

What am I missing?

Best –

**Comment by JanTvrdik** [comment]
You need to enable Tracy before any output is sent to browser, i.e. the following should work
~~~php
<?php
ini_set( "display_errors", 1 );
require('vendor/autoload.php');
use Tracy\Debugger;
Debugger::enable();
?>
<!DOCTYPE html>
<html>
<head>

	<title>Tracy: Hello, world</title>
</head>

<body>
uhm-hum…

<?php //bs(); ?>


</body>
</html>
~~~

**Comment by fabswt** [comment]
Thanks. 

What am I supposed to see?

This is all the output I get:

	<!DOCTYPE html>
	<html>
	<head>
		<title>Tracy: Hello, world</title>
	</head>

	<body>
	uhm-hum…



	</body>
	</html>

**Comment by JanTvrdik** [comment]
@fabswt That means that Tracy is running in production mode and for security reasons does not output anything. By default Tracy auto-detects whether it is running in production or in development mode.

You can manually change the mode by passing value to the first parameter of `enable()` method. You may force Tracy to run in development mode by passing the `Debugger::DEVELOPMENT` constant, i.e.

~~~php
\Tracy\Debugger::enable(\Tracy\Debugger::DEVELOPMENT);
~~~
