### ISSUE TITLE
Custom JS file?

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#265]
- bug report? no
- feature request? yes

### Description

Hi @dg - after you added `Debugger::$customCssFile` today, it got me thinking about JS assets.
What about a `Debugger::$customJsFile` that is added to `renderAssets()`. I add some custom JS to the bar itself which doesn't work on a bluescreen page - this would fix this problem.

Another possibility here - what do you think about adding the ability to easily load custom js files for each panel. I have found that I have to use a dynamic JS loader in case an exception occurs which causes normal loading to fail.

**Comment by dg** [comment]
I would divide it into four things:

1) custom JS for Bluescreen stored in log file
2) custom JS for displayed Bluescreen 
3) custom JS for Bar
4) custom JS for specific Bar panel

I assume that 1) is not needed (it is a little bit complicated to implement), and from the point of view of modularity seems 4) to me better than 3).

**Comment by adrianbj** [comment]
1. I don't personally care about the bluescreen in the log file.
2. I don't specifically add any JS to the bluescreen - it's just that JS added to the bar doesn't get loaded when on a bluescreen page (without using a dynamic loader approach) - that is what I would like to fix. Although perhaps others would like custom JS on the bluescreen?
3. This would fix my needs for the bar on the bluescreen I think.
4. Yes, this would be great although I don't see it as a replacement for 3.

**Comment by adrianbj** [comment]
PS - as one example of 3, I replace the `x` with a minimize/maximize button:

See the new button at the bottom right?
![screen shot 2017-10-09 at 10 21 23 am](https://user-images.githubusercontent.com/871211/31350363-b77c25c6-acdb-11e7-94c0-f4b71e817b01.png)

After clicking it, the bar and all panels are hidden (like the close), but now you have the option to restore with this button:
![screen shot 2017-10-09 at 10 21 35 am](https://user-images.githubusercontent.com/871211/31350362-b77bcbf8-acdb-11e7-85e4-e02744e61917.png)

**Comment by dg** [comment]
I added $customJsFiles for that can be used for 2) and 3)

The 4) is usually solved via `<script>` embedded in panel code.

**Comment by adrianbj** [comment]
Thanks - that should be great. 

I do embed `<script>` in the code for panels, but there are times when I have had issues with this. I need to look into this again when I have a little more time. Will get back to you later on this.

Thanks again!
