### ISSUE TITLE
DI container not cache after update to Tracy 2.4.10 ?

### ISSUE THREAD

**Issue by misaon** [nette/tracy#266]
- bug report? no
- feature request? no
- version: 2.4.10

Its a bug, feature or server problem?
After update from 2.4.9 to 2.4.10 DI container not cache. Its possible to turn cache on again?
Thanks a lot for reaction.

**Comment by dg** [comment]
Can you find out why this is happening?

**Comment by misaon** [comment]
Yes i find problem part...

I have little bit own directory structure in **app** dir.

**Nette/sandbox struct:**
- app
  - presenters
  - ...
  - router
  - bootstrap.php
- ....

**My struct:**
- app
   - presenters
   - ...
   - **system** (i create dir for "system" part of app code)
      - bootstrap.php (In this file i changed paths for composer autoload file, log, temp, neon configs, and robot loader dir [__DIR__ . '/../'])
    - router
- ....
- www
   - **index.php** (here i changed bootstrap.php path)

I tested this on blank sandbox and bug is steel here.
When i using same struct in **previous** tracy version, it **works fine**.

**Comment by dg** [comment]
Can you upload it somewhere? Minimal skeleton where this problem exists?

**Comment by dg** [comment]
ping @misaon
