### ISSUE TITLE
all:unset breaking font awesome

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#270]
- bug report? yes
- feature request? yes
- version: 2.4.10

### Description
Because of:
```
#tracy-debug *:before,
#tracy-debug *:after {
	all: unset;
}
```
it is impossible to use FontAwesome icons in panels. The reason is because these icons are SVG applied to `:before` and because `cx`, `cy`, `d`, `fill`, etc are presentation attributes (https://svgwg.org/svg2-draft/styling.html#PresentationAttributes) and so are overwritten by the `all: unset`. Any chance you'd consider adding a `:not` to exclude this from breaking SVGs used in this way please? 

### Steps To Reproduce
Try to insert a Font Awesome icon in a panel

**Comment by dg** [comment]
I don't use fonts. How can they be excluded?

**Comment by adrianbj** [comment]
This seems to work:

```
#tracy-debug:before:not(svg),
#tracy-debug:after:not(svg),
#tracy-debug *:before:not(svg),
#tracy-debug *:after:not(svg) {
	all: unset;
}
```

**Comment by dg** [comment]
Are you really sure? I couldn't find an example of any SVG element on the https://fontawesome.com/ whose display would depend on `::before`. Also, attributes like `fill` usually do not have SVG elements…

**Comment by adrianbj** [comment]
This explains how FA uses ::before
https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

**Comment by dg** [comment]
Here is example https://codepen.io/fontawesome/pen/WVEobv but I see no SVG::before…

**Comment by adrianbj** [comment]
Take a look here: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.0/css/font-awesome.css notice how each of the defined icons looks something like this:
```
.fa-heart:before {
  content: "\f004";
}
```

I also know that the icons don't show in a Tracy panel with that `unset` rule in place and as soon as I remove it, or add the `:not` in, they display properly again.

**Comment by dg** [comment]
Which HTML elements are used with class `fa-heart`? It seems that usually I. `<i class=fa-heart>`

**Comment by adrianbj** [comment]
I guess that is usually the recommended approach, but there are places I use them on a `<span>` as well. If it helps, I can covert those to `<i>` though if it helps.

Is there a problem with the `:not(svg)` approach? Seems like the unset rule has the potentially to affect other SVG files as well, not just those from FontAwesome.

**Comment by dg** [comment]
I simply need to understand the code I add to Tracy. And here I am not able to understand how will fix FontAwesome icons in panels when `all: unset` will not be applied to SVG elements.

**Comment by adrianbj** [comment]
I feel like we are having communication challenges today (this and the other issue). Fontawesome uses the `:before` pseudo element to add its icons to the element (usually `<i>`). If you apply `all:unset` to this, then it unsets `cx`, `cy`, `d`, `fill` because as I linked in the first post, these are presentation attributes in the SVG file and as such are affected by CSS. It might help to read that doc: https://svgwg.org/svg2-draft/styling.html#PresentationAttributes

Don't worry too much about this - I am already hacking the bar.css file anyway because I don't want all those rules applied to `tracy-debug`, so I always change to `tracy-debug-bar` anyway (we talked about this in another issue ages ago). I am happy to keep hacking in a fix for this issue as well.

**Comment by dg** [comment]
So I researched it and it works for the following reason: `#tracy-debug *:before:not(svg)` is invalid rule. You can change `svg` to anything else and it "will work", because this rule never matches. It must be written as `#tracy-debug *:not(element):before` and in this case it works when element is `i` but not if element is `svg`.

**Comment by adrianbj** [comment]
> So I researched it and it works for the following reason: #tracy-debug *:before:not(svg) is invalid rule.

I thought it might have been, as I mentioned (https://github.com/nette/tracy/issues/270#issuecomment-611139186). I have actually just been doing:

```
#tracy-debug-bar *:before,
```

because that suits my needs better, but I was trying to figure out an option that would work for others who also want to use FA icons in their panels.

Please feel free to ignore this issue - happy to keep hacking it :)

**Comment by dg** [comment]
OK :-)
