### ISSUE TITLE
Please tag a new version

### ISSUE THREAD

**Issue by mvrhov** [nette/tracy#278]
Is there any chance that the new version could be tagged. There is a long time since last version was tagged and I also need the from #264.

**Comment by dg** [comment]
Done

**Comment by mvrhov** [comment]
Thanks, but it seems that this new version didn't propagate to the packagist. Maybe your webhook is broken.

**Comment by dg** [comment]
Hmmm, it is because SPDX fucked up names of licenses :-/ https://github.com/composer/spdx-licenses/pull/17
