### ISSUE TITLE
Option to disable Tracy shutdownHandler

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#279]
- bug report? no
- feature request? yes

### Description
Just wondering if you'd be willing to add this to the top of the `shutdownHandler()` function:

```
		// allows defining an alternate shutdown handler
		// set TRACYSDHANLDER to false before calling your alternate handlder
		if (defined('TRACYSDHANDLER') && TRACYSDHANDLER === false) {
			return false;
		}
```

As the comments note, this allows you to specify your own function for `register_shutdown_function` by doing:

```
define('TRACYSDHANDLER', false);
register_shutdown_function('mySpecialShutdownHandler');
```

Maybe you have an idea for a different way to do this, but this works well in my tests.

Thanks for considering.

**Comment by adrianbj** [comment]
Actually a cleaner option is probably this:

```
	/** @var bool whether to disable the shutdown handler in development mode */
	public static $disableShutdownHandler = false;
```

```
	public static function shutdownHandler()
	{
		if (self::$disableShutdownHandler) {
			return false;
		}
```

Then you can simply set:
```
Debugger::$disableShutdownHandler = true;
```
before you want to register your own shutdown handler. 

If you're happy adding this, let me know if you'd like a PR.

**Comment by dg** [comment]
What's the purpose? Shutdown handler is required to catch fatal error and render bar, which can be disabled using $showBar.

**Comment by adrianbj** [comment]
Hi @dg - `$showBar = false` doesn't work in this situation. I have a PHP console panel that runs code via an ajax request. I want this request to be able to update the AJAX bar, but I don't want fatal errors to trigger the bluescreen - I want to handle them myself for this panel. 

If it would help you understand I could post a screencast showing the difference in user experience with and without the ability to use my own shutdown handler.

**Comment by dg** [comment]
You can handle fatal errors by own this way:

```php
register_shutdown_function(function () {
	// handle error 
	error_clear_last();
});

Debugger::enable();
```

**Comment by adrianbj** [comment]
`error_clear_last()` is php 7 only.

**Comment by dg** [comment]
You can "clear" last error in PHP 5 using something like `@trigger_error('', E_USER_NOTICE);`.

I don't like `$disableShutdownHandler` because it reveals internal implementation, as a result, it turns off the Bar etc. So it would be more appropriate disable only fatal-error handler. 

I think it is such an extraordinary requirement that it is better to use the above mentioned "workaround" than directly it incorporate to Tracy.

**Comment by adrianbj** [comment]
> You can "clear" last error in PHP 5 using something like @trigger_error('', E_USER_NOTICE);.

Unfortunately this doesn't seem to work with the `@` operator. If I remove it, it does do the job, but then of course you also need to deal with this dummy notice.

> I don't like $disableShutdownHandler because it reveals internal implementation, as a result, it turns off the Bar etc. So it would be more appropriate to only disable fatal-error handler.

Unless I am misunderstanding you, the way I have implemented it. it only disables the fatal-error handler - see:
https://github.com/adrianbj/TracyDebugger/blob/42f7e23297ac905efc2be64a539ecd00fc8d3be2/tracy-master/src/Tracy/Debugger.php#L273-L275

**Comment by dg** [comment]
It also disables rendering of Bar on line 291. 

It is strange that it does not work with operator `@`, I'll try to find out why.

**Comment by adrianbj** [comment]
> It also disables rendering of Bar on line 291.
 
Of course - sorry, that hasn't affected me because I am only setting `$disableShutdownHandler` when processing an AJAX call from my Console panel at which point the bar is already rendered.

Perhaps there's a simple workaround there in logic though to allow disabling the shutdown handler while still loading the bar?

**Comment by dg** [comment]
I tried it and `@trigger_error('', E_USER_NOTICE);` works really great for me.

```php
register_shutdown_function(function () {
	@trigger_error('', E_USER_NOTICE);
	var_dump(error_get_last()); // dumps array(4) { ["type"]=> int(1024) ["message"]=> string(0) "" 
});

Debugger::enable();
```

**Comment by dg** [comment]
Other way is to override `exceptionHandler()` and handle ErrorException with E_ERROR, E_CORE_ERROR, E_COMPILE_ERROR, E_PARSE, E_RECOVERABLE_ERROR, E_USER_ERROR own way.

**Comment by adrianbj** [comment]
> I tried it and @trigger_error('', E_USER_NOTICE); works really great for me.

I think it might be a PHP 5 vs 7 issue. For me it works OK on 7, but not on 5.6.

I wonder if the idea to override the exceptionHandler() might be similarly problematic on 5?

I must admin I love the improved error handling in 7.

I think I am going to be going round in circles on this one - I think I'll probably just have to stick with adding my `$disableShutdownHandler` on each upgrade, but thanks for your time looking into this.

**Comment by adrianbj** [comment]
Just to close this issue out - I am sticking with my hack to add the `$disableShutdownHandler` option.
