### ISSUE TITLE
Leaking passwords in production error pages

### ISSUE THREAD

**Issue by zdenekdrahos** [nette/tracy#288]
- bug report? maybe
- feature request? maybe
- version: 2.3.12

### Description

Production passwords, configs are leaked in error pages.

- [x] disable "Nette Aplication" panel - `nette.application.debug: false` in config.neon
![screen shot 2018-03-29 at 07 26 41](https://user-images.githubusercontent.com/7994022/38239393-d9cbf49a-372c-11e8-9e69-aed5166f100f.png)
- [ ] live data in [`Tracy.init`](https://github.com/nette/tracy/blob/master/src/Tracy/assets/BlueScreen/page.phtml#L53)
    * not visible in browser (_error page works with `Tracy && Tracy.Dumper.init();`_)
    * visible when page source is displayed
      ![screen shot 2018-04-03 at 10 55 21](https://user-images.githubusercontent.com/7994022/38239633-95214542-372d-11e8-91e8-79b4e95b8d3c.png)

### Steps To Reproduce

1. Download some production error page
1. Find password, secret configuration in page/source code

**Comment by dg** [comment]
You should disable debug mode on production. https://doc.nette.org/cs/2.4/bootstrap#toc-vyvojarsky-rezim

**Comment by zdenekdrahos** [comment]
@dg: debug mode is disabled, but`Tracy.init` shows presenter in json format

![screen shot 2018-04-03 at 13 05 37](https://user-images.githubusercontent.com/7994022/38245776-c9bc7ed6-373f-11e8-83ed-eb5a247481a1.png)

In that code I can see passwords etc.

_[`Tracy.Dumper.init(<?php echo json_encode(Dumper::fetchLiveData()) ?>);`](https://github.com/nette/tracy/blob/v2.3.12/src/Tracy/assets/BlueScreen/bluescreen.phtml#L366) calls [fetchLiveData](https://github.com/nette/tracy/blob/v2.3.12/src/Tracy/Dumper.php#L388). Live data are saved in [toJson](https://github.com/nette/tracy/blob/v2.3.12/src/Tracy/Dumper.php#L334)._

**Comment by JanTvrdik** [comment]
There should be no Tracy JavaScript when Tracy debug mode is disabled.

**Comment by zdenekdrahos** [comment]
I don't see such condition in source code:

* https://github.com/nette/tracy/blob/v2.3.12/src/Tracy/assets/BlueScreen/bluescreen.phtml#L366
* https://github.com/nette/tracy/blob/master/src/Tracy/assets/BlueScreen/page.phtml#L53

User sees an error page. But html log file in `app/runtime/log` contains `Tracy && Tracy.Dumper.init({"01"` (_tracy 2.3.12, nette 2.3.3_).

![screen shot 2018-04-03 at 13 18 13](https://user-images.githubusercontent.com/7994022/38246261-84c934e8-3741-11e8-9e75-4a4313096c65.png)

**Comment by dg** [comment]
So are you talking about *error pages* or about *logs*?

Logs of course contain sensitive informations.

**Comment by zdenekdrahos** [comment]
Ok. I don't agree that displaying sensitive information is useful feature _(especially if page works with `Tracy.Dumper.init([])`)_. I don't understand why should I see secret configuration in error log like:

```
[2018-03-29 09-09-18] Nette\Application\BadRequestException: 
No route for HTTP request. in /vendor/nette/application/src/Application/Application.php:117  
@@  exception--2018-03-27--05-41--06e27246ef.html
```

But I see that it's Tracy feature, not a bug. Thanks for your time.

**Comment by dg** [comment]
Logging is not displaying. Only administrator has access to logs.

**Comment by zdenekdrahos** [comment]
Just in case somebody else doesn't like leaking [passwords in logs](https://docs.sentry.io/learn/sensitive-data/). 
You can hide passwords with following bash script:

```bash
#!/usr/bin/env sh

set -e
FILE_PATTERN=${1:-"app/runtime/log"}

run () {
    echo "Removing sensitive data in $FILE_PATTERN..."
    for FILE in $(find_html_logs)
    do
        echo "- $FILE"
        normalize_html_log $FILE
    done
}

find_html_logs () {
    find $FILE_PATTERN -maxdepth 1 -type f -name "*.html"
}

normalize_html_log () {
    FILE=$1
    TEMP_FILE="$FILE.normalized"
    cat $FILE \
        | delete_live_data \
        | hide_sensitive "password" \
        | hide_sensitive "secret" \
        > $TEMP_FILE
    mv $TEMP_FILE $FILE
}

delete_live_data () {
    sed 's/.*Tracy \&\& Tracy\.Dumper\.init.*/Tracy \&\& Tracy\.Dumper\.init\(\[\]\)/'
}

hide_sensitive () {
    sed "s/.*$1.*/__SENSITIVE_LINE_WITH_$1__/"
}

run
```

_Notes:_

1. I would disable `nette.debugger.email`, otherwise passwords are leaked if the email has been compromised
1. It might cause some errors in html page, but it should be good enough in most cases

![screen shot 2018-04-03 at 15 01 27](https://user-images.githubusercontent.com/7994022/38250755-ed2d871a-374f-11e8-8e4b-eeae8c5d398c.png)
