### ISSUE TITLE
LocalStorage position/size/toggle status consistency

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#289]
- bug report? no
- feature request? yes
- version: 2.5-dev

### Description

I am curious what you think about the current behavior as it seems a little inconsistent to me. Panel positions and size (using new resize handle) is stored between page reloads while a panel is open, but once closed, these are removed. However, the toggle status of a section is retained even after a panel is closed.

I am not sure the best UX here, but I think that it should at least be consistent. I think in reality sometimes the user would like the size/position to remain and other times they would like them reset. Maybe a button in the system info panel to reset them manually? Probably not ideal - just trying to come up with options :)

I think the key thing is that users with particularly small or large screens will likely make good use of the panel resizing and would probably like to have their settings remembered, but at the same time if they were to expand a particular panel because for a certain instance its content was larger than normal, they would like a way to reset to the original size.

**Comment by dg** [comment]
> Panel positions and size (using new resize handle) is stored between page reloads while a panel is open, but once closed, these are removed. 

The position of the panel is forgotten when it is closed, so it seemed reasonable to forget its size too. 

> However, the toggle status of a section is retained even after a panel is closed.

You are right that the toggle status of closed panels should probably be forgotten as well.

> I am not sure the best UX here,

Me too :-) I guess it turns out in practice. If it's annoying or expectant. I would prefer not to add the icon for resetting the panel (ie. keep the interface as simple as possible) until it turns out that the current behavior is not good.

**Comment by adrianbj** [comment]
Maybe everything should be remembered, but using sessionStorage rather than localStorage. I can imagine wanting a complex panel open with a section toggled open and positioned in an area of the screen and have that remembered between page loads. I don't know :)

**Comment by dg** [comment]
I'll try to experiment with it.
