### ISSUE TITLE
debugInfo can return empty object when extending class that implements __debugInfo

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#292]
- bug report? no
- feature request? yes
- version: 2.5-dev

If you dump an object in a derived class with no `__debugInfo()` method, but which extends a class that does have a `__debugInfo()` method, it can sometimes return an empty object. I think it would be nice if Tracy automatically reverted to the full object in these cases.

Not sure the best approach, but replacing: https://github.com/adrianbj/TracyDebugger/blob/93fe130026244fe727e5553b82183a85b78e2c9f/tracy-master/src/Tracy/Dumper.php#L460 with:

```
return count((array) $obj->__debugInfo()) ? $obj->__debugInfo() : (array) $obj;
```

seems to work ok, although I am not sure if it's the most elegant/performant solution. I don't think it's as simple as checking if the `__debugInfo` method exists for the current class vs the parent it's extending, because I think in many cases the parent implementation will work. That's why I went for the `count()` approach, but would definitely like to hear your thoughts on this.

Thanks!

**Comment by dg** [comment]
That's a very odd behavior. In what cases does this happen?

**Comment by adrianbj** [comment]
Conversation starts here: https://processwire.com/talk/topic/12208-tracy-debugger/?do=findComment&comment=165588

I'll ask Bernhard to join this conversation as well.

**Comment by adrianbj** [comment]
Hey is extending the `Wire` class. Here is it's `__debugInfo()` method:
https://github.com/processwire/processwire/blob/341342dc5b1c58012ae7cb26cffe2c57cd915552/wire/core/Wire.php#L1755-L1761

And here is the `WireDebugInfo` class:

https://github.com/processwire/processwire/blob/master/wire/core/WireDebugInfo.php

**Comment by dg** [comment]
It seems like problem with __debugInfo() implementation. `static` variable is bound to instance class, so object in a derived class has a different variable.

```php
class A
{
	function method()
	{
		static $x;
		$x++;
		echo $x, "\n";
	}
}

class B extends A
{
}


$a = new A;
$a->method();  // prints 1
$a->method();  // prints 2


$b = new B;
$b->method();  // prints 1 again

```

**Comment by adrianbj** [comment]
Thanks @dg - I'll bring it up with @ryancramerdesign and get his thoughts on the `debugInfo()` implementation he set up.

**Comment by adrianbj** [comment]
Just to clarify, I assume it's this line that you are referring to:
`static $debugInfo = null;`

**Comment by dg** [comment]
Yes. Class static properties behave different than static variables, maybe this is the source of the problem.

**Comment by adrianbj** [comment]
Thanks @dg - I don't think Tracy need to do anything differently. Sorry about this issue!
