### ISSUE TITLE
Bar position when dynamically adjusting panel icon labels

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#294]
- bug report? yes
- feature request? no
- version: 2.5-dev

### Description
If you dynamically modify a tab / panel icon label (or somehow otherwise adjust it's width), then the bar needs to have `reposition()` called on it. This is because if the bar is on the right side of the viewport, this results in the bar getting narrower and now the coords are top/left this is a problem.

This could be dealt with by the author of panels that can cause this situation by simply calling:
```
Debug.bar.reposition();
```
after making changes to the tab/panel icon in the bar, but I think it would be nicer to deal with it in the core. The trouble is, I am not sure if there is an easy way to achieve this without using a `MutationObserver`. I can put together a PR using that approach if you're interested, but thought you might have another solution you'd prefer.

Thanks!

### Steps To Reproduce

Note the change of the "truck" icon from red with "2" after it, to green with no number. This is what changes the width.

![bar-resizing-issue](https://user-images.githubusercontent.com/871211/39078414-cd7ab434-44be-11e8-9b10-c7144bf140e4.gif)

**Comment by dg** [comment]
What about call `Debug.bar.savePosition()` before change and `Debug.bar.restorePosition()` after change? It better enforces bar to stay on original position.

**Comment by adrianbj** [comment]
Yeah, probably a more reliable solution. If I understand correctly, you are suggesting that the panel should have to take care of this, rather than the Tracy core? Obviously it's not a huge deal, but I would prefer to see the core handle this. I haven't looked into it, but would it be possible to revert the debug bar's coordinates to bottom / right while keeping the panels at the new top / left. Wouldn't that fix this?
