### ISSUE TITLE
Bar shifting to top left after close modal iframe and reloading page

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#295]
- bug report? yes
- feature request? no
- version: 2.5-dev

### Description

Just found another issue. I can look into this further if you need, but I think it might all be quite problematic while the debug bar's coordinates are top/left. Like I mentioned in the related issue, could the bar be bottom/right and still have the panels top/left?
![modal-reposition](https://user-images.githubusercontent.com/871211/39132229-35a19fba-46c6-11e8-8cfe-eafcc364143d.gif)

**Comment by dg** [comment]
Is it a iframe?

**Comment by adrianbj** [comment]
> Is it a iframe?

Yep!

**Comment by adrianbj** [comment]
Also, just to note that this was definitely not an issue before the change to the coordinates system.

**Comment by dg** [comment]
Bar is in the left-top corner because this position is stored in localStorage (default is right-bottom corner). 

To force iframe to respond to a location change in the main window, it can help to call savePosition in reposition:

![image](https://user-images.githubusercontent.com/194960/39133751-3b8d98c6-4715-11e8-9f53-a6105d9c716b.png)

**Comment by adrianbj** [comment]
It doesn't seem to help here at all unfortunately.

The other issue of course with an iframe like this is that positions are pixels from corners which can result in different locations in the iframe (which is smaller).

I wonder if the bar actually needs exact positioning. Have to considered just 4 options; top/left, bottom/left, top/right, bottom/right (set by a config setting) as the starting point on page load. It can still be manually dragged out of the way, but will always reset to the config position on page load. Would that simplify a lot of this?

**Comment by dg** [comment]
Position should be stored like this:

![image](https://user-images.githubusercontent.com/194960/39135154-98cf3654-4718-11e8-85ea-82e8e55f0dca.png)

ie pixels from right/bottom corner. So it should show bar in the right/bottom corner even if the iframe is smaller or greater.

(When there is not position, it should put bar in right/bottom corner too https://github.com/nette/tracy/blob/b7fa113a41887742a6f64fd36bb948905e278e49/src/Tracy/assets/Bar/bar.js#L332)

Can you please try to find out why does it behave differently?

**Comment by adrianbj** [comment]
Sorry, no time right now - I can try to debug more later, but maybe this is a help for now.

This shows the output of a `console.log(coords);` at the top of the `setPosition` function.

![modal-reposition-2](https://user-images.githubusercontent.com/871211/39139233-315f5bf8-46d6-11e8-89dc-7b41f076c547.gif)

**Comment by adrianbj** [comment]
Sorry for the silence on this. Anyway, it looks like this is no longer an issue - I think the new mutationObserver logic has fixed this as well.

Thanks!

**Comment by adrianbj** [comment]
Unfortunately it looks like the MutationObserver didn't actually fix this. I haven't investigated why yet, but I think for most people having the bar fixed at the bottom right is actually probably fine. Do you think this might actually be the best/easiest solution?

**Comment by dg** [comment]
Did you try the master?

**Comment by adrianbj** [comment]
Yeah, I just grabbed the current master to be sure and it's still definitely an issue.

**Comment by dg** [comment]
Maybe I do not understand what the problem is. Do you want to have bar located elsewhere than the bottom right?

**Comment by adrianbj** [comment]
The problem is shown in the first post. When an iframe based modal is opened this seems to mess with the positioning of the bar on the main page once it is reloaded. I have worked around this with a new "Fixed Position" setting which locks it to bottom right. This is fine for me, but it obviously prevents the ability to drag the bar should you want to.

**Comment by dg** [comment]
I am not able to simulate this situation:

- bar is at bottom right corner
- I'll open iframe and bar appears at left top corner
