### ISSUE TITLE
Wrong remote adddress on app running in docker behind reverse proxy

### ISSUE THREAD

**Issue by misaon** [nette/tracy#297]
- bug report? yes
- feature request? maybe
- version: 2.4.13

I found a problem when I use the Nette application in the Docker. The Docker Container has its own IP address (172.x.x.x), which is also featured in the HTTP header under **REMOTE_ADDR**. 80 ports are allowed to output. 
There is a problem that Tracy is unable to get the real IP address of the visitor.

Sample Problem:
```
...
$configurator->setDebugMode('88.110.31.12');
```
If you run app, tracy dev mode is not started because client IP is not 88.110.31.12 but 172.0.0.10 (docker container IP).

Obtaining a real IP address for a visitor is no problem. Just run Nette application in the Docker for (example Nginx) reverse proxy and let **X-Forwarded-For** or X-Real-IP real IP header be sent.

https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

Now i must use ugly solution like this (example):
```
const DEBUG_MODE_ENABLE_IP = [
	'43.109.198.126',
];
...
$remoteAddress = $_SERVER['HTTP_X_FORWARDED_FOR'] ?? null;
if ($remoteAddress && \in_array($remoteAddress, DEBUG_MODE_ENABLE_IP, true)) {
      $configurator->setDebugMode(true);
}
```
I think Tracy is comparing the HTTP attribute REMOTE_ADDR, which is bad in this case.

Any ideas how to eliminate this deficiency?

What about add option to set second parameter of the function setDebugMode? 
Parameter will be string of real IP address.

Thanks for reply.

**Comment by milo** [comment]
The problem is that content of `HTTP_X_FORWARDED_FOR` is not secure. In some cases, an attacker can send own contents and enable development mode.

There was already a discussion on this topic, but I cannot find it now. Maybe in https://github.com/nette/bootstrap/ repo.

**Comment by f3l1x** [comment]
@milo Link attached. 

https://github.com/nette/bootstrap/issues/54

**Comment by f3l1x** [comment]
@misaon At this moment I think you can enable debug mod by `nette-debug` cookie. But only if you're 💯 sure what are doing, go this way:

```
$configurator->setDebugMode('ultra-secret-token@' . $_SERVER['REMOTE_ADDR']);
```

And then, set the `ultra-secret-token` into your `nette-debug` cookie.

**Comment by dg** [comment]
Don't know how to solve it.
