### ISSUE TITLE
SQL queries are not logging

### ISSUE THREAD

**Issue by bhumiradixweb** [nette/tracy#298]
- bug report? yes
- feature request? no
- version: latest
### Description
How to log my sql queries? I don't have pdo.

### Steps To Reproduce
... If possible a minimal demo of the problem ...

**Comment by milo** [comment]
Which SQL library do you use with Tracy? Dibi, Nette Databse, other one?

**Comment by bhumiradixweb** [comment]
Hello,

I am using EzSQL currently but i think it is not supported by tracy.
