### ISSUE TITLE
Undefined variable skipError

### ISSUE THREAD

**Issue by Mark53CZ** [nette/tracy#306]
Version: 2.5.0

### Bug Description
Notice: Undefined variable: skipError in /<path_to_project>/vendor/tracy/tracy/src/Tracy/assets/BlueScreen/content.phtml on line 34

**Comment by dg** [comment]
Are you sure? There is no skipError https://github.com/nette/tracy/blob/v2.5.0/src/Tracy/assets/BlueScreen/content.phtml#L35

**Comment by Mark53CZ** [comment]
Sorry, it was my fault. PHPStorm incorrectly uploaded this file after composer update :)
