### ISSUE TITLE
tracy - editor settings from neon config is not taken

### ISSUE THREAD

**Issue by elcheco** [nette/tracy#310]
Version: "v2.5.0-RC"

### Bug Description
I am using Nette Framework and I set up tracy params in the config. If I will use:
tracy:
    # link format to open in the editor
    editor: "phpstorm://open?file=%file&line=%line"

It looks like the editor specified here is not taken further and when exception is thrown the code is showing the normal "editor://..."

**Comment by mkoula** [comment]
If I use the bdump with showLocation, then it's showing the proper URL "phpstorm://...", but in Exception Page, it's showing the above mentioned...

**Comment by dg** [comment]
Can you find out why this is happening?

**Comment by mkoula** [comment]
Sorry to be that late, but I missed somehow this message. I needed to downgrade some libraries because of composer dependencies and now it seems to be fine, I will try to create a sample project and investigate it soon...
