### ISSUE TITLE
Incompatible return types

### ISSUE THREAD

**Issue by Lumeriol** [nette/tracy#312]
Version: 3.0-dev

### Bug Description
Fatal error: Declaration of Nette\Bridges\DatabaseTracy\ConnectionPanel::getPanel(): ?string must be compatible with Tracy\IBarPanel::getPanel(): string in vendor\nette\database\src\Bridges\DatabaseTracy\ConnectionPanel.php on line 20

Fatal error: Declaration of Nette\Bridges\SecurityTracy\UserPanel::getTab(): ?string must be compatible with Tracy\IBarPanel::getTab(): string in vendor\nette\security\src\Bridges\SecurityTracy\UserPanel.php on line 19

### Steps To Reproduce
After update Tracy from version 2.5.x to 3.0 (dev-master). Other Nette components are dev-master.

### Possible Solution
Possible IBarPanel.php - return type should be ?string instead string

**Comment by dg** [comment]
Fixed
