### ISSUE TITLE
Multiple panels with `tracy-focused` class

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#316]
Version: 2.5.2

### Bug Description
Not sure if this is expected behavior, but it seems that once a panel has been focused, it never loses the `tracy-focused` class when other panels are clicked, bringing them to the top of the stack. A panel has to be closed to lose the class.

### Steps To Reproduce
Open more than one panel and click on one and then the other so that they are focused and their `z-index` adjusted so that they are on top. Look at the inspector and notice that `tracy-focused` is not removed.

### Expected Behavior
Only one panel at a time should have the `tracy-focused` class.

### Possible Solution
Adjust the bar.js `blur()` method to remove the `if (this.is(Panel.PEEK)) {` conditional. 
Is there a reason for this condition?

**Comment by dg** [comment]
Thanks, fixed

**Comment by adrianbj** [comment]
Thanks for the fix, but would you mind adjusting to something like this:
```
for (var id in Debug.panels) {
    if(id !== elem.id) Debug.panels[id].elem.classList.remove(Panel.FOCUSED);
}
```
so that it isn't removed and then added back again.

I have a MutationObserver that is checking for addition of the `tracy-focused` class to a panel. Because you are now removing it and then adding it again the observer notes a change which really isn't the case.

I don't think there would be any side-effects to that change?

Do you think this would be ok?

Thanks.

**Comment by dg** [comment]
I tried to fix it.

**Comment by adrianbj** [comment]
Thanks, that seems to work and also plays nicely with my MutationObserver.
