### ISSUE TITLE
Dumping DOMDocument doesn't really work

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#319]
Version: 2.5.2

### Bug Description

Dumping a DOMDocument object results in basically an empty dump

### Steps To Reproduce

Notice the difference in output for a Tracy dump call vs a `print_r`

![image](https://user-images.githubusercontent.com/871211/45885521-86789580-bd6b-11e8-9e38-140884e002f2.png)

### Expected Behavior

I would expect to see a nested dump of object properties

### Possible Solution

Sorry, I haven't investigated :)

**Comment by dg** [comment]
It is PHP problem (related to this https://bugs.php.net/bug.php?id=48527) and I don't know how to solve it.

**Comment by adrianbj** [comment]
Interesting that in the linked issue: https://bugs.php.net/bug.php?id=65565 it is mentioned that it has been fixed. I am running 7.2 here and it's still an issue.

Oh well, not a big deal. Thanks for the link.

**Comment by dg** [comment]
It seems that only var_dump() was fixed.

**Comment by chaotic-pan** [comment]
My workaround ...
```
Tracy\Dumper::$objectExporters[\DOMNode::class] = function ($obj) {
	$dump = print_r($obj, 1);
	preg_match_all('~^\s*\[([^\]]+)\]\s+=>\s*(\S*)\s*$~m', $dump, $aMatches);
	return array_combine($aMatches[1], $aMatches[2]);
};
```
