### ISSUE TITLE
Opening files in PHPStorm

### ISSUE THREAD

**Issue by paddelboot** [nette/tracy#324]
Trying to open files from the debug screen in PHPStorm following [this](https://tracy.nette.org/en/open-files-in-ide) info.

My open-editor.sh file:

    #!/bin/bash
    declare -A mapping

    $editor='phpstorm --line "$LINE" "$FILE"'
    ....

When I run `~/bin/install.sh` I get:

> Error: it seems like you have not set command to run your editor.
Before install, set variable `$editor` in file `open-editor.sh`.

How to fix this? Thanks.

**Comment by jiripudil** [comment]
Dollar signs in bash are only used for reading the variable values. Declarations are dollar-free:

```patch
- $editor='phpstorm --line "$LINE" "$FILE"'
+ editor='phpstorm --line "$LINE" "$FILE"'
```

**Comment by paddelboot** [comment]
Thanks.
