### ISSUE TITLE
Logging directory 'C:\MAMP\htdocs\mywebsite/mylog' is not found

### ISSUE THREAD

**Issue by cedtin** [nette/tracy#326]
Hello,

Thanks for reading!

Attempting to create a log file according to the following:
```Debugger::enable(Debugger::DETECT, __DIR__ . '/mylog');```

mylog is indeed in the directory! I have no idea why it isn't working. No idea! Is this a bug???

Thank you

**Comment by milo** [comment]
Strange. This is the only check
https://github.com/nette/tracy/blob/871c079e54a96f83cafbf0582f4c55b015690430/src/Tracy/Debugger.php#L168

**Comment by dg** [comment]
I dont know what to do…
