### ISSUE TITLE
Clicking tab icon when panel already open but unfocused

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#327]
Version: 2.5.3

### Bug Description
If you have two or more panels open and one is unfocused and fully obscured by the focused one it is natural to want to click the tab icon for the hidden(unfocused) one so that it is focused and comes to the top, but because it's already open, this action actually closes it so you have to click again which then opens and focuses it on top.

### Steps To Reproduce
In this screencast see how the Console panel is initially behind the API Explorer panel so to access it I go to the debug bar, initially hovering over the Console panel icon (which brings the panel to the top), but once I click on it, it closes the panel. Then I click on it again and it reopens it and brings it to top.
![aqhce5jew9](https://user-images.githubusercontent.com/871211/47529143-52ecd600-d8ea-11e8-8a35-8c4f33824307.gif)

### Expected Behavior
I would like to see an unfocused tab brought to the top and focused when clicking on its tab icon the first time, rather than being closed and having to click again to reopen it.

**Comment by adrianbj** [comment]
@dg - It looks like in recent commits you have fixed this by having mouseover on the tab icon make an already floated (but unfocused) become focused and still in float mode. At least it seems to work consistently like that now. Is that correct? Seems like I can close this now, do you agree?

**Comment by dg** [comment]
No, it is not (IMHO) fixed. I do not know what to do about it at all.

**Comment by adrianbj** [comment]
Well at least it is much better now - no need to click the tab icon to bring to top, focus and float.

![az51ko0o8d](https://user-images.githubusercontent.com/871211/47686130-d894ae00-db96-11e8-84dc-e49fbbf397a9.gif)

Admittedly, clicking on the tab icon will still close it, which isn't ideal, but still much better than it was. I guess the problem is that once you mouseover it focuses the panel so you can't check for `Panel.FOCUSED` on the `click` EventListener because it will always be focused by the time a click is registered.

**Comment by dg** [comment]
I'm glad it helped, though it's a little mystery to me :-)

**Comment by adrianbj** [comment]
> I'm glad it helped, though it's a little mystery to me :-)

How so? Can you not reproduce, or are you not understanding what I think has improved, or what change I would actually like to see, or just no idea on how to actually fix it fully?

No reply necessary unless you want extra info from me :)

**Comment by dg** [comment]
>  no need to click the tab icon to bring to top, focus and float.

This IMHO did not change…

**Comment by adrianbj** [comment]
> This IMHO did not change…

I think you're right :)

Not sure whether something was just buggy before, or maybe I just didn't notice exactly what was going on properly, but I just tested an older version and it does seem the same. Oh well, I think it's good enough. Feel free to close if you want.

Sorry for all the unnecessary chatter!

**Comment by dg** [comment]
:-D
