### ISSUE TITLE
Wrong github tag version for tag 2.5.4

### ISSUE THREAD

**Issue by geniv** [nette/tracy#331]
Version: 2.5.4

### Bug Description
Current master branch has composer required for PHP 7.1+, this is correct, but current tag 2.5.4 has only PHP>=5.4.4

### Possible Solution
Re-tag master version.

**Comment by mabar** [comment]
Seems like every tag from 2.4.0 to 2.5.4 have same problem (I have not checked previous versions)
https://github.com/nette/tracy/blob/v2.4.0/composer.json#L18
https://github.com/nette/tracy/blob/v2.5.4/composer.json#L18

**Comment by mabar** [comment]
Sorry, too much work today. It is not wrong. 2.5.4 is just tagged from 2.5 branch https://github.com/nette/tracy/tree/v2.5

php 7.1 will be required by tracy:3.0

**Comment by mabar** [comment]
So problem is not in tags but in that one return type. Other files in 2.5 branch are not using php 7 typehints

**Comment by geniv** [comment]
Yes, problem is in return type, but this return type is support from PHP 7.1 version, then composer.json with version PHP 5.4.4+ is wrong

**Comment by dg** [comment]
Fixed b3eea83a0e58b200910b0d485f5830ade11257b5
