### ISSUE TITLE
PHP7 return types in 2.5 version

### ISSUE THREAD

**Issue by ricco24** [nette/tracy#332]
Version: 2.5.4

### Bug Description
tracy/src/Bridges/Nette/Bridge.php has PHP7 declare(strict_types=1) and void return from initialize method

### Steps To Reproduce
Update composer to version 2.5.4 and run PHP < 7.1

### Expected Behavior
No exception

### Possible Solution
Remove return types and strict_type

**Comment by dg** [comment]
fixed 1aa9a142fea4f552e2ef3b26466a129065fa472f
