### ISSUE TITLE
Tracy\Bridges\Nette\Bridge::initialize() results in TypeError in PHP 7.0

### ISSUE THREAD

**Issue by chrudosvorlicek** [nette/tracy#333]
Version: 2.5.4

### Bug Description
Tracy returns TypeError in Tracy\Bridges\Nette\Bridge::initialize() when usin PHP 7.0 because return type void is supported since PHP 7.1. In previous Tracy version (2.5.3) everything worked correctly.

### Possible Solution
remove expected return type from Tracy\Bridges\Nette\Bridge::initialize()

**Comment by dg** [comment]
#331 #332
