### ISSUE TITLE
Debugger::log | Add custom prefix to filename

### ISSUE THREAD

**Issue by inovek** [nette/tracy#339]
The title explains itself already. A additional parameter for `Debugger::log` would be nice, which allows to add a custom prefix to the filename. This would allow the developer to use the Log-Feature itself to add strings or other useful information in front of the filename like a string with class, date, methods and so on.

**Examples**
```
2018-01-31_info.txt
navigate_route_nodes_2018-01-31_debug.txt
2018-01-31_prod_frontend_catch_js_error.txt
```

**Comment by dg** [comment]
Just use `Debugger::log($var, '2018-01-31_prod_frontend_catch_js_error');`
