### ISSUE TITLE
New live dumps puts location before dump

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#343]
Version: 2.6

### Bug Description

![image](https://user-images.githubusercontent.com/871211/53131237-0bd1c300-3521-11e9-9396-e200e26bd5a6.png)

### Expected Behavior

If I change this line https://github.com/nette/tracy/blob/118e3839368eb55edd9e92078fe6d33f201013d0/src/Tracy/Debugger/Debugger.php#L548 to false, then it looks as expected:

![image](https://user-images.githubusercontent.com/871211/53131308-45a2c980-3521-11e9-8a6a-a6558c8bf83c.png)

so it's got something to do with the way live dumps render.

**Comment by adrianbj** [comment]
Just wanted to mention that this is not new to 2.6. Live dumps in 2.5 also caused this.

Replacing: https://github.com/nette/tracy/blob/a82086ac0bfee25672d11b40086d25925f3549b3/src/Tracy/Dumper/assets/dumper.js#L36

with:
```
el.insertBefore(build(JSON.parse(el.getAttribute('data-tracy-dump')), snapshot, el.classList.contains('tracy-collapsed')), el.firstChild);
```
seems to fix it, but I have a feeling that might be reversing the order of snapshots or something else. I haven't looked into it thoroughly yet.

**Comment by dg** [comment]
Yes, it is right fix.
