### ISSUE TITLE
Can not mark first dumped text by mouse in bluescreen arguments

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#345]
Version: 2.6.0

### Bug Description
If arguments in bluescreen view contain only one argument, I can not mark some text (for example I want search bad string in PhpStorm).

I think problem is new automatic sorting feature, because If I mark some text in first table `<td>`, table will be sorted automaticly and marked area is dropped.

### Steps To Reproduce
Open any Tracy bluescreen dump with only one argument and try mark string like this:

![snimek obrazovky 2019-02-21 v 10 32 55](https://user-images.githubusercontent.com/4738758/53158674-7a1b9180-35c4-11e9-9550-4c1099f6bd75.png)

### Expected Behavior
Enable marking text in single arguments table.

### Possible Solution
Disable sorting in single arguments table.

**Comment by dg** [comment]
fixed
