### ISSUE TITLE
Bardump vs showLocation: true styling 

### ISSUE THREAD

**Issue by Gappa** [nette/tracy#347]
Version: 2.6.0

### Bug Description
Location, where from the bardump was called, used to be below the dumped variable - now they are both on the same line, unnecessarily widening the whole "Dumps" box.

#### Previous behaviour:
![correct](https://user-images.githubusercontent.com/749981/53390496-a30c9f80-3993-11e9-9024-7b41a926ea0a.png)

#### Current behaviour in 2.6.0:
![wrong](https://user-images.githubusercontent.com/749981/53390510-ad2e9e00-3993-11e9-8578-41705a33e80a.png)

### Steps To Reproduce
Dump something using Bardump with `showLocation: true`.

### Expected Behavior
Location is shown above or below the dumped variable.

### Possible Solution
Previously it was dependent on a linebreak inside a `<pre>` element, which now seems to be missing.
Or it can be done by setting `display: block` on one of the elements, probably on `div.tracy-toggle`.

**Comment by adrianbj** [comment]
@Gappa - this was fixed by: https://github.com/nette/tracy/commit/442b907eef00ad7c74c09bdec42ab459ccbd7012
