### ISSUE TITLE
Another sorting problem (nette database tracy bar)

### ISSUE THREAD

**Issue by lulco** [nette/tracy#349]
Version: 2.6.0

### Bug Description
Using sorting in nette database tracy bar table cause reorder of the whole table (inner tables are merged with outer table). See screenshots below.

Default view:
https://screenshots.firefox.com/Guu5aLXQgjsKX8YZ/gisellis.localhost.sk

After first click to Time ms:
https://screenshots.firefox.com/91ISntB1H1lLkZ3x/gisellis.localhost.sk

After second click to Time ms:
https://screenshots.firefox.com/0Za3R2AqK7zHP4m9/gisellis.localhost.sk

### Steps To Reproduce
Use nette database tracy bar in you project and you will see it

### Expected Behavior
Table is just sorted. No reorder of columns and inner tables is done.

### Possible Solution
Do not sort nette database tracy bar table - sort only tables marked with some class (e.g. sortable).

**Comment by dg** [comment]
It should be fixed in master.
