### ISSUE TITLE
Ambiguous class Test resolution

### ISSUE THREAD

**Issue by slownet** [nette/tracy#350]
Version: 2.6.1

### Bug Description
PhpStan:
In RobotLoader.php line 208:

Ambiguous class Test resolution; defined in 
%my_project%\vendor\tracy\tracy\examples\dump-snapshot.php and in %my_project%\vendor\tracy\tracy\examples\dump.php.

Probably it's error from this commit:
commit a1fb838648e1b840c5a23bfba2adc780258ec7d9

### Possible Solution
Change class name

**Comment by JanTvrdik** [comment]
you have incorrectly configured phpstan, it should have no need to scan `vendor` with RobotLoader
