### ISSUE TITLE
null coalescing operator and $_SERVER['REQUEST_URI']

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#351]
Version: 2.6.1

### Bug Description
Sometimes `$_SERVER['REQUEST_URI']` returns false rather than the URL or `NULL`. This causes a `Uncaught TypeError: explode() expects parameter 2 to be string, boolean given` error in `/src/Tracy/Bar/assets/loader.phtml:16`

### Possible Solution
Not sure but maybe in this case the null coalescing operator won't work and it needs to be reverted to an `isset` check like in 2.5.

More info here: https://github.com/adrianbj/TracyDebugger/issues/32

**Comment by mabar** [comment]
Null coalescing operator should act exactly like isset, [see example](http://sandbox.onlinephpfunctions.com/code/3004eb6e5a1c5f244aa35e8904854106923d54d5)

**Comment by adrianbj** [comment]
@mabar - yeah, I was just thinking about this actually and I guess even the `isset()` used in v2.5 wouldn't work if the server is returning `false` because `isset` would return `true` in this case also.

Perhaps this is an unusual situation - maybe it's an idiosyncracy of nginx/1.15.8 (via Laravel Valet)
 being used (as per the referenced issue). So maybe the check needs to check if it's set and also a string to rule a `false` value?
