### ISSUE TITLE
Tracy always starts a session

### ISSUE THREAD

**Issue by jkufner** [nette/tracy#356]
Version: 2.4.0+, introduced by 5c46e989a61fd2594db6eda0f0da4f904ccad4c7

### Bug Description

Tracy always starts a session because https://github.com/nette/tracy/commit/5c46e989a61fd2594db6eda0f0da4f904ccad4c7#diff-be100a67d872789dffa3bfba6144122dR89

### Steps To Reproduce
Don't start a session, enable Tracy.

### Expected Behavior
Session does not start.

### Possible Solution

Remove the start() call from DI container and don't be lazy to check if there is a started session. Such a code don't belong to DI container anyway.

See https://github.com/nette/tracy/commit/5c46e989a61fd2594db6eda0f0da4f904ccad4c7#diff-be100a67d872789dffa3bfba6144122dR89

**Comment by dg** [comment]
Can you send PR?

**Comment by jkufner** [comment]
Maybe. It depends on how deep the session goes. I will give it a try.

**Comment by milo** [comment]
@jkufner It starts in debug mode only, doesn't? https://github.com/nette/tracy/blob/92b97ca42bde7bf40cdf9fcc090ee20ff4951a11/src/Bridges/Nette/TracyExtension.php#L106-L123

**Comment by jkufner** [comment]
@milo Yes, the following line causes the issue:

    $initialize->addBody('$this->getService(?)->start();', [$name]);

**Comment by milo** [comment]
@jkufner Sorry, my point is: Is it a problem to always start session in debug mode? Tracy "always" needs. Usually it is a session for developer on local machine.

**Comment by jkufner** [comment]
@milo If there are no errors to report, then there is no reason to have a session stored and a cookie sent to a client. Tracy <2.4 behaves this way.

Always starting a session prevents us from implementing a state-less API and pollutes the server with useless sessions as every request creates a new session because non-browser clients ignore cookies.

**Comment by milo** [comment]
@jkufner Your server does not run in a production mode?

**Comment by jkufner** [comment]
@milo Of course not; it is a development server.

**Comment by forrest79** [comment]
Hi, we have a similar problem and we would appriciate Tracy without session. I prepared PR - just a concept.
