### ISSUE TITLE
DI bar

### ISSUE THREAD

**Issue by petrparolek** [nette/tracy#358]
Version: 2.5.7

### Bug Description

If I focus to DI container, bar size of window is too big and if I click for persist window and refresh page window is hidden.

Version 2.5.6 is OK

**Comment by petrparolek** [comment]
bug  is in 9b406bd579ab441c5178fba93fb9a4bc3d7c18b8. If I revert this commit, all is OK

**Comment by petrparolek** [comment]
ping @dg

**Comment by dg** [comment]
should by fixed by #359

**Comment by petrparolek** [comment]
great, it is fixed, thanks
