### ISSUE TITLE
Shift dumped function arguments on Error

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#360]
Version: 2.6.1

### Bug Description

When Tracy return error: `Call to a member function xxx() on null` dumped function parameters will be shifted one back.

Real example:

<img width="767" alt="Snímek obrazovky 2019-04-01 v 10 58 13" src="https://user-images.githubusercontent.com/4738758/55316425-a6051f00-546e-11e9-9f5b-57afbf57baf0.png">

Argument `$name` on Call stack `#1` can not be `"_NULL"`, because this string will be created on `getCartHash()`, but Tracy display false information.

### Steps To Reproduce
Throw error `Call to a member function xxx() on null`.

### Possible Solution
Move dumped arguments one position.

**Comment by milo** [comment]
Not 100% sure but it looks like a PHP bug. Tracy renders stack arguments [here](https://github.com/nette/tracy/blob/422bff731b3398615d900fce2bd5fec0517b82cd/src/Tracy/BlueScreen/assets/content.phtml#L97) and does not any shifting.

Which PHP do you use?

**Comment by JanTvrdik** [comment]
This is expected behavior since PHP 7. See https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.func-parameter-modified

**Comment by janbarasek** [comment]
@milo in this case I used PHP `7.1.1`:

![Snímek obrazovky 2019-04-01 v 13 09 15](https://user-images.githubusercontent.com/4738758/55323436-5c710000-547f-11e9-8db9-7ec257c25428.png)

@JanTvrdik ok, but wtf! I think Tracy should mark arguments as "maybe false".

**Comment by JanTvrdik** [comment]
> @JanTvrdik ok, but wtf! I think Tracy should mark arguments as "maybe false".

That should already be done since Tracy 2.6.0 (see https://github.com/nette/tracy/commit/4f7b6add0919e6ffc51226c030e14caccef22c7e). Maybe the warning is not clear enough?

**Comment by milo** [comment]
Oh, I see. So it is only Tracy rendering style.

**Comment by janbarasek** [comment]
@JanTvrdik Oh, thank you! I thought the message is only default rendering style.

The expected behavior is that in this case Tracy strongly emphasizes the argument (for example, in color).

**Comment by dg** [comment]
What you mean by „in this case”. Arguments are unreliable always.

**Comment by janbarasek** [comment]
@dg Ok, but I thought for example Tracy in case `throw new \Exception();` show always true values of arguments. 

Sorry for my english, Czech translation:

Ok, myslel jsem si, že Tracy například v případě `throw new \Exception();` zobrazí vždy reálné hodnoty předávaných argumentů. Problém se týká jen specifických chyb přímo z jádra PHP.

**Comment by dg** [comment]
Unfortunately, arguments are always *wrong*. PHP 7 is broken in this. https://twitter.com/geekovo/status/615890794038325249
