### ISSUE TITLE
Tracy\IBarPanel::getTab() returning non-string breaks Tracy silently in hard to debug way

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tracy#361]
Version: 2.6.1

### Bug Description
Tracy\IBarPanel::getTab() returning non-string breaks Tracy silently in hard to debug way due to 

1) `declare(strict_types=1)` in `bar.phtml`
2) `bar.phtml` uses `trim()` which requires `string`
3) `bar.phtml` is rendered in a way which suppresses all errors and does not catch `TypeError`.

There are actually two issues:

1) broken support for `Nette\Utils\Html`
2) failing in way which makes it hard to debug.

The second one being far more important.

### Steps To Reproduce
Return `Nette\Utils\Html` from `Tracy\IBarPanel::getTab()`

### Expected Behavior
Tracy bar should not silently stop working without any information from user.

**Comment by JanTvrdik** [comment]
`bar.phtml` is executed outside of the `try` block and `getTab()` does not declare `string` return type in Tracy 2.6.1. https://github.com/nette/tracy/commit/df4d933f1b4c5e22620148ed6787b4ebacb08806 fixes the biggest issue.

**Comment by JanTvrdik** [comment]
Thank you!

**Comment by dg** [comment]
you're welcome
