### ISSUE TITLE
Dumper show some values in array when array is empty

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#367]
Version: 2.6.2

### Bug Description
If array contain 0 items Tracy show ilustration `[ ... ]` which means `some data`. I think it's bug and it's confused.

![Snímek obrazovky 2019-05-14 v 15 19 25](https://user-images.githubusercontent.com/4738758/57701662-bb1fc100-765c-11e9-9de4-17c969c1d119.png)

### Steps To Reproduce
Dump some array with 0 items.

### Possible Solution
Show only `array (0)` without `[ ... ]` section.

Thank you.

**Comment by smuuf** [comment]
I'm unable to reproduce this. Can you provide some code snippet demonstrating this?

**Comment by dg** [comment]
Fixed
