### ISSUE TITLE
Call logger with appropriate severity in production mode

### ISSUE THREAD

**Issue by Ekimik** [nette/tracy#370]
Tracy `v2.5.8`
PHP `7.0.33`

I have set custom logger to Tracy by `\Tracy\Debugger::setLogger` method in my bootstrap file. My logger extends `Tracy\Logger` and overrides method `log`. This method calls its parent implementation and it logs message to Elasticsearch in addition. In production, even if message, which I want to get logged, is notice or warring, `error` is passed to `$priority` argument in `log` method. I have field `logLevel` in Elasticsearch to be able distinguish different types of errors (warnings/notices/...), but `error` is stored for all messages.

I definitely agree, that warning and notices should be treated like errors in production, but I wonder if correct severity (or priority in Tracy terminology) can be passed to logger, so I will be able to store message to Elasticsearch with correct `logLevel` (and don't have to make message text filtering on ES side)? I believe code, which causes this is [here](https://github.com/nette/tracy/blob/v2.5.8/src/Tracy/Debugger.php#L427) (or at least XDebug claims it).

Thanks for any reaction.

**Comment by JanTvrdik** [comment]
> don't have to make message text filtering on ES side

You can make the message text filtering in your logger which extends `Tracy\Logger`.

**Comment by Ekimik** [comment]
Yes, I definitely can, but it seems to me like workaround and unnecessary effort, when I have an argument in method which should serve for exactly this purpose.

**Comment by JanTvrdik** [comment]
> which should serve for exactly this purpose

This an incorrect assumption. The meaning of logger priorities is different to PHP error levels.

**Comment by Ekimik** [comment]
Ok, then it is really up to me to filter messages. Thanks for clarification
