### ISSUE TITLE
Dumper should render string key as string with quotes

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#375]
Version: 2.6.3

### Bug Description
I know when I define array like:

```php
$array = [
	'1' => 'hello',
	'02' => 'hi',
	3 => 'how are you?',
];
```

String key `'1'` will be converted to integer automatically. More info: https://php.net/manual/en/language.types.array.php

> A key may be either an integer or a string. If a key is the standard representation of an integer, it will be interpreted as such (i.e. "8" will be interpreted as 8, while "08" will be interpreted as "08").

But in case of `\stdClass` I can defined key as string:

```php
$trick = new \stdClass;
$trick->{'12'} = 37;

dump($trick);

foreach ($trick as $key => $value) {
	dump([
		'key' => $key,
		'value' => $value,
	]);
}

$trick = (array) $trick;

foreach ($trick as $key => $value) {
	dump([
		'key' => $key,
		'value' => $value,
	]);
}

dumpe($trick);
```

and Dumper render it like this:

<img width="317" alt="Snímek obrazovky 2019-07-11 v 15 52 03" src="https://user-images.githubusercontent.com/4738758/61056565-db1cf800-a3f3-11e9-910a-9fbb7d05a1c0.png">

It means Tracy knows `\stdClass` key is string. Why render like integer? It feels confused.

### Steps To Reproduce
Use code:

```php
$trick = new \stdClass;
$trick->{'12'} = 37;
dump($trick);
```

### Expected Behavior
Replace render:

```
stdClass
   12 => 37
```

to:

```
stdClass
   "12" => 37
```

when key is string and data type is iterable object.

Thanks.

**Comment by dg** [comment]
As you can see, it renders each key without quotes.

**Comment by janbarasek** [comment]
@dg In my personal opinion, it is not good, because I can't recognize a string from and integer key in dump.

Why Dumper render all types without quotes? In case of string key looks like integer Dumper should render key in quotes.

**Comment by dg** [comment]
> because I can't recognize a string from and integer key in dump.

You don't need to distinguish it. It's just always a string. And they are rendered without quotes for better readability.
