### ISSUE TITLE
Hardcoded error_reporting(E_ALL)

### ISSUE THREAD

**Issue by bacinsky** [nette/tracy#385]
What about this line https://github.com/nette/tracy/blob/master/src/Tracy/Debugger/Debugger.php#L192
when I want to use Debugger in production mode but without deprecated errors logged. I want to have error_reporting set by PHP INI configuration but there is that hard-coded line which overrides it. Any ideas?

**Comment by JanTvrdik** [comment]
Why do you want to ignore deprecated errors instead of logging them?
You can override Tracy logger to customize its behavior.
You can override the `error_reporting` directive after `Tracy\Debugger::enable()` was called.

**Comment by bacinsky** [comment]
For me, deprecated errors are useful in development mode only, in production they are messing my logs. I know that I can override it, but I will more like something less dirty, like ignore that line when production mode is enabled, or something more clever. Thanks.

**Comment by dg** [comment]
It is not a good idea to rely on php.ini settings, it is better to override it by default value.
