### ISSUE TITLE
Do not strict report deprecated and user notices

### ISSUE THREAD

**Issue by bacinsky** [nette/tracy#386]
I do not understand how to set Tracy to not red-screen report E_DEPRECATED & E_USER_DEPRECATED & E_USER_NOTICE in development environment with strict mode enabled, without Debugger code changed. Thanks.

https://github.com/nette/tracy/blob/master/src/Tracy/Debugger/Debugger.php#L395

**Comment by JanTvrdik** [comment]
@bacinsky `Tracy\Debugger::$strictMode` can be also set to integer. So you can probably do sth like

```php
Tracy\Debugger::$strictMode = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED & ~E_USER_NOTICE
```

**Comment by bacinsky** [comment]
It's working, thanks, I guess this should be mentioned in the Tracy guide, or am I missing something?
