### ISSUE TITLE
Dead code or autoloading mechanism?

### ISSUE THREAD

**Issue by holtkamp** [nette/tracy#389]
Maybe I am missing the point, but what is the functional justification of this snippet: 

https://github.com/nette/tracy/blob/eb2e7728a867f57938f8aed35a7ad097a1a14835/src/Tracy/Debugger/Debugger.php#L202-L203

Is it to ensure these classes are "autoloaded"? If so, what would be the point of that?

**Comment by jelen07** [comment]
I think that the primary aim of this code is that ensures, that Tracy will work properly. It's better to know earlier, that Tracy won't work in `Debugger::enable()` method, than later - ie. logging and so on.

**Comment by dg** [comment]
This is because the errors that occurs in the autoloader.

**Comment by holtkamp** [comment]
>This is because the errors that occurs in the autoloader.
ok, so it is intended to "capture" any error that might occur during autoloading. But it does not ensure that class exists... `class_exists('unexistingClass');` simply returns `false`...

>For questions please use the forum https://forum.nette.org/en/f46-tracy

Ok, sorry. Thought this was more a "issue" than a question 😉 

Closing for now, but I think the code does not do what it suggests it does... 🤔

**Comment by dg** [comment]
It is just fix for very specific problem. It can be replaced with `require_once ...`.
