### ISSUE TITLE
Specify more than one email in Nette 3 extension 

### ISSUE THREAD

**Issue by martenb** [nette/tracy#395]
Version: 2.7.2

### Bug Description
How can I specify more than one e-mail in Nette extension?

### Steps To Reproduce
In previous versions of nette/di you can specify it like this:
```
tracy:
	email:
		- xxx@xxx.com
		- yyy@xxx.com
```
Now it throws an exception:
```
Nette\DI\InvalidConfigurationException
The option 'tracy › email' expects to be email or Nette\Schema\DynamicParameter, array given.
```

**Comment by dg** [comment]
Fixed
