### ISSUE TITLE
Tracy bar not showing in PHP 7.3.12

### ISSUE THREAD

**Issue by OndraTakacs** [nette/tracy#396]
Version: 2.7.2

### Bug Description
Tracy debug bar is not shown using XAMPP v7.3.12 for Windows

There are two errors in js console:
- GET http://localhost/tracy/examples/barDump.php?_tracy_bar=js&v=2.7.2&XDEBUG_SESSION_STOP=1 net::ERR_ABORTED 500 (Internal Server Error)
- barDump.php:14 Uncaught ReferenceError: Tracy is not defined
    at barDump.php:14

Following error is shown after accessing the file at http://localhost/tracy/examples/barDump.php?_tracy_bar=js&v=2.7.2&XDEBUG_SESSION_STOP=1
- src\Tracy\Debugger\Debugger.php:220 LogicException: Tracy\Debugger::dispatch() called after some output has been sent. Try Tracy\OutputDebugger to find where output started.
- full error in attachment: [Tracy-bug.zip](https://github.com/nette/tracy/files/3996289/Tracy-bug.zip)

### Steps To Reproduce
1. Use PHP v7.3.12
2. Run localhost/tracy/examples/barDump.php
3. Ctrl+shift+R for full reload
4. Tracy debug bar is missing

### Expected Behavior
Tracy debug bar is shown

### Possible Solution
Switch to PHP v7.1.33, it works OK

**Comment by dg** [comment]
In your Tracy-bug file I see errors like 

```
Warning: Header may not contain NUL bytes in  C:\xampp\htdocs\tracy\examples\barDump.php on line  3
```

and 

```
Warning: Header may not contain NUL bytes in C:\xampp\htdocs\tracy\src\Tracy\Debugger\Debugger.php on line 357 
```

However, on line 357 no header is sent:

https://github.com/nette/tracy/blob/v2.7.2/src/Tracy/Debugger/Debugger.php#L357

What's in your file?

**Comment by OndraTakacs** [comment]
Thank you for your answer David. I checked the file and the content is exactly the same as on GitHub, so there is no header sent on line 357. I test this on latest version of Tracy from Git.

**Comment by dg** [comment]
Could it be caused by a PHP extension, like an opcode cache? Because otherwise it doesn't make sense to me.
