### ISSUE TITLE
Heart emjoi encoding issue breaks bluescreen on ajax calls when using DB session storage

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#397]
Version: 2.5.8+

### Bug Description
If you're using DB instead of file based session storage and the table doesn't use `utf8mb4`, the heart emoji at the end of the donation link at the bottom of the bluescreen breaks the bluescreen completely with a `Uncaught SyntaxError: Unexpected token <` error.

### Steps To Reproduce
Use a DB session handler and make a call to a PHP script with an exception via AJAX.

### Expected Behavior
Should work as normal

### Possible Solution
Remove the heart emoji from the end of this line: https://github.com/nette/tracy/blob/35b98e11b8374ccbf71f957d4275c70248b65bc2/src/Tracy/BlueScreen/assets/content.phtml#L361

Thanks for considering and Happy New Year!

**Comment by JanTvrdik** [comment]
Aren't session in general binary? Meaning that `utf8mb4` is wrong as well? For this one 💙️ case we can replace it with HTML entity but your session handler will remain broken.

**Comment by adrianbj** [comment]
The session handler seems to work fine otherwise. Are you suggesting it should use `utf8mb4_bin` or `utf8_bin` instead of `utf8mb4_unicode` / `utf8_unicode` ?

**Comment by adrianbj** [comment]
FYI - the session data is being stored serialized

**Comment by JanTvrdik** [comment]
> The session handler seems to work fine otherwise

Try sth like `$_SESSSION['test'] = "\xFF\xED\xA0\x80"`.

**Comment by dg** [comment]
Replacing the heart emoji with HTML entity is easy, but it does not solve the problem in general. Because emoji can be inside dumped variable, source code etc. So it may be better to add note to the readme that DB storage must meet some requirements.

Perhaps now the situation is better because in fails every time and the error is detected immediately.

**Comment by adrianbj** [comment]
> Perhaps the current situation is better because it fails every time and the error is detected immediately.

Unfortunately that's not really the case because it requires an AJAX call that has an exception before you really notice the issue and even then it might actually remain hidden because it's possible that everything will appear fine unless you look in the browser dev tools. 

I have been discussing changes to the DB session handler with ProcessWire's developer to see if he will force the DB to always support these. 

I think in reality this is probably something that needs to be handled at the ProcessWire end, rather than by Tracy so I think I'll close this. Thanks for your input though.
