### ISSUE TITLE
Tracy bar and Firefox browser

### ISSUE THREAD

**Issue by Lumeriol** [nette/tracy#398]
Version: 2.7.2 and earlier (do not know first version)

### Bug Description
Not a really bugs, mainly visual problems - on Firefox v70 (69) and Developer edition.
- all SVG icons are black, not colorized
- list of Composer packages (hover of execution time) is not toggleable, arrow is changing, but list of packages is still visible.
- same problem is with all other collapsible content - after show is not possible to hide content (i.e. in Sessions after show content of array is not possible to hide it).

### Steps To Reproduce
Latest Tracy on project in Firefox.

### Expected Behavior
Same behavior as on another browsers (Edge, Chromium based).

**Comment by dg** [comment]
Thanks, fixed.

This only affects the @dev version because I'm testing `all:revert`, which only works in Firefox. 

(related to #394)
