### ISSUE TITLE
Call to undefined method Tracy\Bar::dispatchContent()

### ISSUE THREAD

**Issue by petrknap** [nette/tracy#405]
Version: 2.7.2

### Bug Description
Call to undefined method Tracy\Bar::dispatchContent()
https://github.com/nette/tracy/commit/bde75ac91a823e29fd8a7ce46c711eb3164ea2d4

### Steps To Reproduce
1. Install and use Tracy 2.4.4
1. Update to 2.7.2
1. Try to run

### Expected Behavior
Public signature must be constant (can be expanded, not changed or reduced) in major version

### Possible Solution
Mark major changes as major changes.

**Comment by dg** [comment]
It should have been marked as `@internal`, sorry.

**Comment by petrknap** [comment]
`@internal` means "private, internal to the software project" https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.internal.pkg.html

But this method was necessary if you needed to insert bar into page (like our wrapper and Nette does). `Tracy\Bar` becomes dead code if this method (or its successor `dispatchAssets`) will be marked and used as internal.

**Comment by dg** [comment]
It's alright. Describe the situation you need to solve, you can also send a test, and there will be some official solution with an official api.

**Comment by petrknap** [comment]
We have an old wrapper which simply wraps any PHP code and inserts Tracy into the output - https://github.com/netpromotion/tracy-wrapper/blob/master/src/helpers.php - the problem is, that projects which updates Tracy crashes due to this change.

The simplest solution from our side is to fix Tracy version to `2.4.4`, release new/old version, increase minimal Tracy version to `^2.7`, change usage of `Tracy\Bar` and release new/new version.

But better solution will be to return this method as dummy (keep signature), mark it as deprecated and remove it in version 3.

**Comment by dg** [comment]
I meant what you need for `dispatchAssets()` and why it should be public. I do not want to return `dispatchContent()`, because it existed four years ago for a short time (for Tracy were at that time 2.3, 2.4 etc something like major versions).

**Comment by petrknap** [comment]
We can speculate why we need this public method which was necessary for previous minor version in current minor version with same signature and behavior, but why? It's expected behavior of minor version update.

You need constant API across at least major version. It does not depends on names, purposes, old wrong decisions, etc. Every standalone package must be usable from outside like black box, otherwise it's unusable.

If "for Tracy were at that time 2.3, 2.4 etc something like major versions" then why you don't release version 3 instead of 2.7 to stop this versioning problem?

**Comment by dg** [comment]
Because before it was fashionable to version differently than today.
