### ISSUE TITLE
Ability to add/prepend custom shutdown handler

### ISSUE THREAD

**Issue by mskocik** [nette/tracy#408]
**Problem:**

I have a situation where I would need different `shutdown_handler` instead of default 'Server error error 500'.  

_Example:_ 
- Ajax request generating huge download bundle and in some edge cases it timeouts. I don't really want to increase timeout limit for various reasons, but I would like to provide user response he can act upon. Like request it again but with increased timeout or whatever.

**Possible solutions:**

1. provide static methods:
    -  `registerShutdownHandler($name, $callback)` for adding callback to handler array;
    - `unregisterHandler($name)` - remove named handler from `handler` array
2. provide method:
    - `prependShutdownHandler` - which will enable adding new handler before default Tracy shutdown_handler. Which would catch all fatal errors it they won't be catched by our custom handler

Solution **(2)** is better IMHO because it keeps default error handling, but extending it a little bit. It is similar what @dg is suggesting in #279 but dynamically.

> You can handle fatal errors by own this way:
> 
> ```
> register_shutdown_function(function () {
> 	// handle error 
> 	error_clear_last();
> });
> 
> Debugger::enable();
> ```

Thoughts on this? I can implement it if it will get merged.

**Comment by dg** [comment]
This should work, or doesn't?
```
register_shutdown_function(function () {
	// handle error 
	error_clear_last();
});

Debugger::enable();
```

**Comment by mskocik** [comment]
But this doesn't solve the issue, when handler needs to be added 
**dynamicaly**. I am mentioning it above, maybe you missed it.

**Comment by mskocik** [comment]
Fortunately I found that `$onFatalError` is enough for my use-case.
