### ISSUE TITLE
Tracy panel missing with nginx/fpm

### ISSUE THREAD

**Issue by andrei-dascalu** [nette/tracy#410]
Version: 2.7.3

### Bug Description
I've run into a rather strange issue with Tracy panel.

I have a small legacy application (think <?php echo “<html>”; ?> kind of stuff). I've added Tracy mainly to get some real time insights into queries.
All goes fine when using the application in a classic Apache + php module with mpm prefork. However, after switching the exact same application with same php.ini and same everything on to an nginx + fpm setup, the panel doesn't show anymore.

I've done some debugging, in that I saw that the panel is added with a register_shutdown_function handler, which seems to trigger as expected.

Under Apache, there's some content appended after the </html> tag, but the same content isn't returned by nginx. I am not entirely sure if there's an nginx setting that I overlooked (I've used nginx for years, reason why I want to move away from Apache – but I've never been in a situation to need content after closing the html of a page).

Has anyone had this issue before? Is there something I'm missing?

### Steps To Reproduce

I am working to setup a repo with some basic configuration to showcase what I'm talking about

### Expected Behavior
have the panel with nginx/fpm as well

### Possible Solution
- not so much a full solution, but I trying to figure out a way to capture the full output in the shutdown function and ensure that the Tracy panel is inside the html tags rather than outside. I'm just assuming this has something to do with it.

**Comment by dg** [comment]
Did you try this https://github.com/nette/tracy/issues/229?

**Comment by andrei-dascalu** [comment]
Hello,

I have looked at it but dismissed it since I didn't see the error mentioned, though the effects seem similar so I will have another look.

**Comment by andrei-dascalu** [comment]
Hello,

So I've had another look, but the issues seem unrelated. In my case, on the Apache application, I get this content appended to the HTML output sent to browser:

```php
<!-- Tracy Debug Bar -->
<script src="/index.php?view=consument.login&amp;_tracy_bar=js&amp;v=2.7.3&amp;XDEBUG_SESSION_STOP=1" data-id="b5565c2d53"></script>
<script>
Tracy.Debug.init("<div id=tracy-debug-bar>.....
```

Which works fine. However, when the same app runs with FPM, this content is not sent and therefore the debug bar is not initiated. In the other ticket, the issue seems to be that the script part was generated, but the URL in the src wasn't properly handled.

While I am at a loss as to why this happens (the script tag seems generated in a shutdown handler that does run => when I do a file_put_contents or log in that function, it seems ok, just that no output from it makes it in the response) I no longer thing this is related to Tracy itself as no output handlers are able to create output.

On the other hand, if I manually exit immediately after the handler is registered, then I do get the output, which is more confusing.

**Comment by andrei-dascalu** [comment]
closing, since I'm sure it's not related to Tracy.
