### ISSUE TITLE
BlueScreen: Function highlight_string() can throw error in case of unexpected character in input

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#412]
Version: `2.7.3`

### Bug Description

Hello,

sometimes BlueScreen can throw this error:

```
[2020-04-07 16-41-50]
PHP Compile Warning: Unexpected character in input:  '' (ASCII=28) state=0 in /Applications/MAMP/htdocs/baraja/sandbox/vendor/tracy/tracy/src/Tracy/BlueScreen/BlueScreen.php:290
@  CLI (PID: 37485): /usr/local/bin/composer dump 
```

Broken file can be Composer.phar for example:

![Snímek obrazovky 2020-04-07 v 16 51 05](https://user-images.githubusercontent.com/4738758/78685434-09335800-78f2-11ea-9c14-41b6b6494316.png)

Return of current `highlight_string()`:

<img width="1668" alt="Snímek obrazovky 2020-04-07 v 16 53 17" src="https://user-images.githubusercontent.com/4738758/78685468-16504700-78f2-11ea-8aae-e236e2b710d3.png">

I think this error should be catched and generated next BlueScreen with it. I couldn't figure out how to detect the error. I tried the `Callback::invokeSafe()`, but it does not detect this error.

My suggested fully works example, how to detect:

```php
$source = str_replace(["\r\n", "\r"], "\n", $source);
$lastErrorMessage = error_get_last()['message'];
$highlightedCode = highlight_string($source, true);
$currentErrorMessage = error_get_last()['message'];
if (\is_bool($highlightedCode) || $lastErrorMessage !== $currentErrorMessage) {
	// Can be logged?
	Debugger::log('Broken file: ' . $currentErrorMessage);
}
$sourceLines = explode("\n", $highlightedCode);
$out = $sourceLines[0]; // <code><span color=highlight.html>
$source = (string) str_replace('<br />', "\n", $sourceLines[1]);
$out .= static::highlightLine($source, $line, $lines);
```

I am not sure, how to implement to Tracy.

**This error is very tricky because it can stop executing Composer commands/tasks and stop the entire application.**

### Possible solution

Source can be hightlighted only to special character like this:

```php
$source = str_replace(["\r\n", "\r"], "\n", $source);
$source = explode(chr(28), $source)[0] ?? '';
```

Because original error message is: `Compile Warning: Unexpected character in input: '\x1c' (ASCII=28) state=0`

![Snímek obrazovky 2020-04-07 v 17 20 14](https://user-images.githubusercontent.com/4738758/78687056-0cc7de80-78f4-11ea-9eb9-9970d564ff01.png)

Thanks.

**Comment by dg** [comment]
Why do you think it is necessary to detectd and process/log this error separately and not simply silent it away, because it is an expected error?

**Comment by dg** [comment]
I removed part after __halt_compiler() from source code 260ebf90eb1d304d886e3267a9f0a961e9a63125

**Comment by janbarasek** [comment]
@dg Thanks for remove it.

I think function `highlight_string()` should render code without special characters. What do you think about add some helper for fix encoding in case of rendering code snippet?

**Comment by dg** [comment]
But such a thing should not happen, except in the case of __halt_complier, or should?

**Comment by janbarasek** [comment]
@dg Thanks! Now is ok.

Last:

![Snímek obrazovky 2020-04-08 v 14 00 11](https://user-images.githubusercontent.com/4738758/78781841-44d92b00-79a1-11ea-8000-df3dbf58d3b4.png)

Now:

![Snímek obrazovky 2020-04-08 v 14 00 25](https://user-images.githubusercontent.com/4738758/78781870-4d316600-79a1-11ea-98dc-5f81beee0431.png)

**Comment by dg** [comment]
👍
