### ISSUE TITLE
Tracy not rendering toolbar via Twig

### ISSUE THREAD

**Issue by MilanRajcevic** [nette/tracy#418]
Version: 2.7

### Bug Description
I'm using Klein with Twig templating engine. While Tracy does work, it stops rendering the floating toolbar then Twig is plugged into the system.
There are no errors, no additional HTML is being injected the output.
Tracy debugging works as expected, however.

### Steps To Reproduce
Install Tracy and Twig, render a sample Twig template.

### Expected Behavior
Expecting to see a floating Tracy debug toolbar while the debug mode is on.

**Comment by jelen07** [comment]
It works for me 😉 

```bash
$ mkdir tracy-twig
$ cd tracy-twig
$ composer require tracy/tracy
$ composer require twig/twig
```

create and edit the `index.php`

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

\Tracy\Debugger::enable(\Tracy\Debugger::DEVELOPMENT);

$loader = new \Twig\Loader\FilesystemLoader(__DIR__);
$twig = new \Twig\Environment($loader, [
    'cache' => __DIR__ . '/var/cache',
]);

$template = $twig->load('demo.html.twig');
echo $template->render(['name' => 'Jon Doe']);
```

create the template `demo.html.twig`
```html
<h1>Hello {{ name }}!</h1>
```

Start native PHP server
```bash
$ php -S localhost:8000 -t . 
```

Visit the page in your browser http://localhost:8000/ 🎉 
<img width="471" alt="Snímek obrazovky 2020-04-28 v 15 30 30" src="https://user-images.githubusercontent.com/2346295/80493161-53de4800-8965-11ea-91f4-42787206441e.png">

Do you have the debug environment set properly?
```php
\Tracy\Debugger::enable(\Tracy\Debugger::DEVELOPMENT);
```

**Comment by MilanRajcevic** [comment]
Thank you for the quick response, this prompted me to debug it a bit (ha, pun intended).
It wasn't injecting because it didn't think the app processing ended, for some reason.
**adding an exit()** after the $twig->render fixed it!

**Comment by jelen07** [comment]
You should debug first, ask questions last. Glad to help anyway.

**Comment by MilanRajcevic** [comment]
There's no need to be smug.
You've never had an unrelated response prompt a solution to a problem you've been struggling before? If you deem this irrelevant I urge you to please remove the issue, I'll attempt to determine why exactly this little quirk solves this particular bug at a later date.

Thanks for the banter! :)
