### ISSUE TITLE
Open panel stay blocked in browser when I close it

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#423]
Version: 2.7.5

### Bug Description

Sometimes when I close Tracy panel and refresh the page or click to link, this same panel stays opened.

I recorded this behavior to a short video (non-public): https://www.youtube.com/watch?v=Z7WBt7A-uZ0

Browser: Safari 13.1.1 (15609.2.9.1.2).

### Possible Solution

When I close all panels, invalid Tracy local storage cache.

**Comment by dg** [comment]
Can you find out if the unload event is triggered?

https://github.com/nette/tracy/blob/6d06dc115eee68db32dc0d6f3a466f1ead45a060/src/Tracy/Bar/assets/bar.js#L460

**Comment by janbarasek** [comment]
It was very difficult to simulate, but in case of a jam, it is called in this order (step by step):

<img width="1030" alt="Snímek obrazovky 2020-06-04 v 14 45 42" src="https://user-images.githubusercontent.com/4738758/83758269-1199dc00-a672-11ea-8c1b-c917255ccd2f.png">

Next step:

<img width="1057" alt="Snímek obrazovky 2020-06-04 v 14 46 02" src="https://user-images.githubusercontent.com/4738758/83758284-1d859e00-a672-11ea-931c-40679264e82f.png">

Next step:

<img width="1032" alt="Snímek obrazovky 2020-06-04 v 14 46 30" src="https://user-images.githubusercontent.com/4738758/83758315-2d9d7d80-a672-11ea-82f8-006994eeace5.png">

And now Tracy's javascript has ended. Other functions are called in my user code, which does not affect Tracy.

Unfortunately, I can't investigate the problem further. The same problem sometimes occurs in Chrome.

**Comment by janbarasek** [comment]
I tried to save the status of the panels with this code:

`localStorage.setItem('tracy-panels-debug', JSON.stringify(Debug.panels));`

![Snímek obrazovky 2020-06-04 v 14 55 10](https://user-images.githubusercontent.com/4738758/83759209-86b9e100-a673-11ea-8095-a477936f12df.png)

And my local storage value is:

![Snímek obrazovky 2020-06-04 v 14 56 48](https://user-images.githubusercontent.com/4738758/83759286-9fc29200-a673-11ea-8ec6-c3f8e569d8bf.png)

**Comment by dg** [comment]
`Debug.panels[id].savePosition()` should remove all `tracy-debug-panel-***` keys from local storage (meaning: panels are closed) and they should be removed after refresh. Is it true?

**Comment by janbarasek** [comment]
In Safari `14.0 (15610.1.28.1.9, 15610)` it has been fixed.
