### ISSUE TITLE
Is it possible to override the "Server Error" message with a custom html page?

### ISSUE THREAD

**Issue by FatherFil** [nette/tracy#424]
Whenever our production instance hits a bug we get the standard "Server Error" page from Tracy. I was wondering whether there was a way of overriding that for production, and sending the user to a standard 500.html page?

Apologies if I've missed it on any other issues or on the forum. I did check but nothing came in the searches.

**Comment by mabar** [comment]
`\Tracy\Debugger::$errorTemplate = __DIR__ . '/path/to/500.html'`

**Comment by FatherFil** [comment]
Thank you @mabar - that's great!
