### ISSUE TITLE
Log slow requests

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#435]
Hello,

sometimes I solve the problem that some requests are slow. This is usually caused by high traffic or some slow pages.

I think it would be good if Tracy could log slow requests and possibly send alerts.

Letting the PHP script crash as a timeout is not a good solution, because a request that evaluates, for example, 5 seconds should be returned to the user, but at the same time the administrator should know that something like this has happened.

What do you think? Thanks.

**Comment by JanTvrdik** [comment]
Seems out of scope and you can write it yourself with just few lines of code. Not sure how Tracy could really help here.
