### ISSUE TITLE
Setting content-length header strips debugger output

### ISSUE THREAD

**Issue by urugator** [nette/tracy#436]
While it makes sense, it's not immediately obvious why the tracy bar isn't showing up.
I think it would be beneficial to mention this in docs.
 
What are the possible solutions?
Currently I simply ignore the content-length header when debugger is enabled:
```php
private function emitHeaders(ResponseInterface $response) : void {
    $statusCode = $response->getStatusCode();
    foreach ($response->getHeaders() as $name => $value) {
      $normalizedName = self::normalizeHeaderName($name);
      // The additional output generated by debugger is stripped by client/server when content-length is set
      if (Debugger::isEnabled() && $name === 'content-length') {
        continue;
      }
      header("$normalizedName: $value", true, $statusCode);
    }
    foreach ($response->getCookies() as $cookie) {
      header($cookie->toHeader(), false, $statusCode);
    }
}
```
But clearly it's not ideal and possibly problematic when using a 3rd party lib/framework.
Can omitted content-length header cause any trouble (considering usual http clients)?

Is it perhaps possible to intercept/capture the debugger's output, so it can be added to response manually?
However that would limit the "scope" of what the Debugger is able to capture, so probably not the best idea either...?

Related #255

**Comment by dg** [comment]
fixed 9540b1007aacc8fa18aa3d8aa1655c842057e35c
