### ISSUE TITLE
Missing response body on (not just) AJAX

### ISSUE THREAD

**Issue by urugator** [nette/tracy#437]
Version: 2.7.5

### Bug Description
The response body is missing when there is an error during ajax request, no matter whether the user is actually able to see the error with BlueScreen, leaving him clueless in case he can't.
Possibly the problem (only) occurs when the page is loaded without starting the session, but the session is started later in some ajax call, dunno, but this is my case.

### Expected Behavior
The response body contains an error in plain text (either always or at least when it's not displayable)

### Possible Solution
Either use different heuristic to detect whether the error is displayable or always output the error to reponse body in simplified form.

**Comment by urugator** [comment]
I've realized it's not just AJAX. Similar problem occurs when content-type isn't `text/html` (guess it's due to `isHtmlMode()` impl).
Consider having `<script src="generated.js">` inside the page (the *generated.js* is not a file, but executes php).
Then if server throws the tracy catches the error and returns 500 with empty body, so the original error message is lost and again the user have no clue what happened.

**Comment by dg** [comment]
Is the error message not even in the log?

**Comment by urugator** [comment]
Well I suppose it is, if it's enabled...
But the point is that just by enabling tracy, I get worse debugging experience (in case of ajax/non html requests), because normally I would see the error in the response, but tracy basically swallows it and I don't think there is a reason for doing so?

**Comment by dg** [comment]
"Error in response" - do you mean the panel in Chrome Dev Tool? Isn't there a problem with it? When you open the file `generated.js` directly, do you see anything?

**Comment by urugator** [comment]
Good lord ... you're right ... chrome tools ignore/don't show the body on 500; wtf...
I am sorry for false alert and thank you for investigating.
