### ISSUE TITLE
Property with password is sometimes inaccurate or broken

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#441]
Version: 2.7.5

### Bug Description

Password hiding behavior varies and sometimes displays incorrect information.

For example:

Password length is different next to parameter and dumper:

![Snímek obrazovky 2020-10-08 v 17 32 15](https://user-images.githubusercontent.com/4738758/95480990-ca5b8900-098c-11eb-869b-75191f3a5c82.png)

The parameter type was changed to string in case of null:

![Snímek obrazovky 2020-10-08 v 17 33 02](https://user-images.githubusercontent.com/4738758/95481124-f24aec80-098c-11eb-8bc2-72c08b411011.png)

But in the case of array is the parameter type correct:

![Snímek obrazovky 2020-10-08 v 17 34 04](https://user-images.githubusercontent.com/4738758/95481209-0a227080-098d-11eb-9026-1ebf3432cc67.png)

But in case of parameter name is `password` and value is array it is changed to string too:

![Snímek obrazovky 2020-10-08 v 17 34 44](https://user-images.githubusercontent.com/4738758/95481299-22928b00-098d-11eb-92c3-d57508f86a2d.png)

In the real log it can be very funny:

![Snímek obrazovky 2020-10-08 v 17 29 11](https://user-images.githubusercontent.com/4738758/95481365-350cc480-098d-11eb-9709-2dfeb3af89cb.png)

### Steps To Reproduce
Try invoke method with arguemnts.

### Expected Behavior
Unify the behavior of all listings. Always display data type. Never lie about the length of the password (it is better not to display anything in the case of a string).

Thanks.

**Comment by dg** [comment]
fixed

**Comment by janbarasek** [comment]
Thanks!
