### ISSUE TITLE
table-sort.js cannot sort by custom data

### ISSUE THREAD

**Issue by midlan** [nette/tracy#442]
Imagine table where I put to one of the columns timing in miliseconds.
![95674950-fe64c300-0bb3-11eb-926c-6a82efcd5ea6](https://user-images.githubusercontent.com/4263992/95686221-d057a100-0bfc-11eb-9d76-09e8f9837720.png)

I would like to sort that column (find some of the slowest queries). Currently it sorts the column like a string, so it leads to not sort the data properly.

Solution would be to support some dataset value to help with the proper sorting. E.g. `data-position` HTML attribute.

**Comment by dg** [comment]
I added data-order attribute
