### ISSUE TITLE
Dumped object do not include uninitialized properties

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#448]
Version: 2.7.5

### Bug Description
In case of PHP 7.4 entity with required scalar properties Tracy do not show required properties without value.

For example imagine simple object `OrderInfoAddress`:

```php
<?php

declare(strict_types=1);

namespace Baraja\Cart;


final class OrderInfoAddress
{
	private string $street;

	private string $city;

	private string $zip;

	private string $companyName = '';

	private string $ic = '';

	private bool $buyAsCompany = false;

	private bool $invoiceAddressIsDifferent = false;
}
```

In case of simple dump like:

```php
bdump(new OrderInfoAddress)
```

Tracy show initialized properties with value only:

![Snímek obrazovky 2020-11-09 v 19 30 31](https://user-images.githubusercontent.com/4738758/98581612-09e5ff80-22c2-11eb-9604-6f92565c4a0e.png)

### Steps To Reproduce
Use my test object.

### Expected Behavior & Possible Solution
Tracy should show all properties, but instead, value shows information property is uninitialized.

This settings can be detected by `\ReflectionProperty` by simple logic: `$property->isInitialized($instance)`.

Current behavior is confusing. In the case of inheritance of multiple classes, it is not possible to unambiguously determine whether the property was inherited or just has no value.

Thanks!

**Comment by dg** [comment]
Look, I'm not sure if it should work as you write. Should this dump show property `$foo`?

```php
class X 
{
  public $foo;
}

$x = new X;
unset($x->foo);
dump($x);
```

**Comment by janbarasek** [comment]
@dg I don't think the property `$foo` should be displayed in this case.

However, it should be displayed when it is physically defined in a class so that the developer knows that its value may exist in some cases.

What do you think?

**Comment by mabar** [comment]
I prepared example with all variants - var_dump displays typed properties every time, not-typed properties only if they were not unset() and the dynamic properties.
Tracy could ideally show all properties and show the differences like uninitialized / unset / dynamic

http://sandbox.onlinephpfunctions.com/code/64b434282c03f8ce7a12987ebd6fc2e4b6a4bd83

**Comment by dg** [comment]
@janbarasek but now you are contradictory. `$foo` is physically defined in a class

**Comment by mabar** [comment]
So I made a working implementation which includes class-only defined properties. Needs changes, because uninitialized / unset modifiers are rendered as values, but good enough for demonstration.

Here is the commit: https://github.com/mabar/tracy/commit/88f3f456f154caa201ed835ded34b9f7b42e5555

Testing code:
```php
class Test
{

	public int $typed = 123;
	public $untyped = 123;
	public int $typedNoValue;
	public $untypedNoValue;
	protected $prot = 'prot';
	private $priv = 'priv';

	public function doUnset(): void
	{
		unset($this->typed);
		unset($this->untyped);
		unset($this->typedNoValue);
		unset($this->untypedNoValue);
		unset($this->prot);
		unset($this->priv);
	}

}

$t = new Test();
bdump($t);

$t->doUnset();
$t->dynamicallySet = 'foo';

bdump($t);
```

This is before:
![before](https://user-images.githubusercontent.com/20974277/99125784-14c3cb80-2605-11eb-867c-c647d8e605b7.PNG)

And this is after:
![after](https://user-images.githubusercontent.com/20974277/99125818-273e0500-2605-11eb-87d5-a7735bbe42f4.PNG)
