### ISSUE TITLE
When rendering a multiline string, Tracy should show where the string begins

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#453]
When dumping a multiline string, such as:

```php
dump("Abcd\n    efgh.");
```

Tracy displays the indented first character on the first line and indents the next lines with solid spaces.

However, you can't see where the individual lines start and how many spaces to remove in the indent.

<img width="150" alt="Snímek obrazovky 2020-12-27 v 12 17 41" src="https://user-images.githubusercontent.com/4738758/103169656-0ee51b00-483e-11eb-9f82-2bfb6907dbfb.png">

The solution could be like a line (in the case of an array dump):

<img width="177" alt="Snímek obrazovky 2020-12-27 v 12 18 43" src="https://user-images.githubusercontent.com/4738758/103169658-13a9cf00-483e-11eb-9002-feb3831b399f.png">

Thanks!

**Comment by dg** [comment]
That makes sense. I'm considering whether to include ('a') or not ('b') quotation marks in the case of multiline strings.

![image](https://user-images.githubusercontent.com/194960/103177574-06abd080-487c-11eb-8bba-9816c410b8b7.png)
