### ISSUE TITLE
E-mail report subject should contain critical error level

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#455]
Hello,

I think e-mail subject like `PHP: An error occurred on the server baraja.cz` should contain log level keyword (the level name instead of `error`) for better sorting in an e-mail inbox.

For example: `PHP: An critical error occurred on the server baraja.cz` is more helpful subject. I can set mail filter for subjects containing `critical`, `warning`, `info` or more.

Thanks.

**Comment by dg** [comment]
And how do you send those emails?

**Comment by dg** [comment]
@janbarasek ping

**Comment by janbarasek** [comment]
@dg Pong! :)

**Comment by janbarasek** [comment]
@dg I use default Mailer directly in Logger: https://github.com/nette/tracy/blob/37c238d08db44f2cd6f21f7d97e5cea11d631fae/src/Tracy/Logger/Logger.php#L193

I am not sure how to change the subject safelly.

**Comment by dg** [comment]
Logger::log() sends an email only when the level is error/exception/critical. So I don't understand how warning/info etc. could appear there.

**Comment by janbarasek** [comment]
Ok, I think subject should contain word `critical` in case of critical error (for example generated from critical user payment tasks).

**Comment by dg** [comment]
In my opinion, all three cases are critical. I will stay to a simpler solution.
