### ISSUE TITLE
Bar doesn't show up when using proxy

### ISSUE THREAD

**Issue by mskocik** [nette/tracy#465]
Version: 2.8.0+

### Bug Description
When running local vhost through proxy (through browser-sync for example). Tracy bar is not shown. Following error is shown in console, which is triggered by `Tracy.Debug.init()` call:
```
Uncaught SyntaxError: missing ) after argument list
```

### Steps To Reproduce
- create nette project like in tutorial (project accessible on localhost/www/nette-blog)
- install browser-sync package (nodejs required) `npm install browser-sync --save-dev`
- <details><summary>create proxy script <code>proxy.js</code></summary><div class="highlight highlight-source-js"><pre>const bs = require("browser-sync").create();
  bs.init({
   proxy: 'localhost/nette-blog/www'
  });</pre></div></details>
- run command `node proxy.js`

### Expected Behavior
Tracy bar is visible when using proxy

### Possible Solution
With version 2.7.7 it works OK. Also on different project (see image below for package versions details) helped to hide Tracy panel for DI. But with clean sandbox it wasn't enough. 
<details><summary>Package versions</summary><img src="https://user-images.githubusercontent.com/25513620/106733910-b9591680-6612-11eb-8fbe-694f9351689d.png"></details>

💡 It seems the hostname is not correctly escaped due to `:` in hostname

**Comment by dg** [comment]
Tracy Bar is downloaded from the server using AJAX. What does the HTTP response look like?
