### ISSUE TITLE
Render exception message with monospace font

### ISSUE THREAD

**Issue by mabar** [nette/tracy#466]
Sometimes error messages are space-sensitive. Usage of monospaced font should prevent misinterpretation

e.g. with nextras dbal pointing on invalid part of query:

![before](https://user-images.githubusercontent.com/20974277/106755625-9dfc0480-662e-11eb-961f-cb01a338f2e7.PNG)
![after](https://user-images.githubusercontent.com/20974277/106755630-9f2d3180-662e-11eb-826d-a4aaa0199fe8.PNG)

**Comment by dg** [comment]
This is a matter for `Debugger::$customCssFiles` I think.
