### ISSUE TITLE
A dumped class without a namespace should start with a slash

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#468]
Hello,

I think when dumping a class that doesn't contain a namespace, Tracy should put a leading slash.

For example, in this case I want to write DateTime in the property:

![Snímek obrazovky 2021-02-12 v 10 05 08](https://user-images.githubusercontent.com/4738758/107748724-cb753c00-6d19-11eb-84d1-8ff6b73db32e.png)

But is it `DateTime` directly from PHP, or what? If Tracy specified `\DateTime`, then the class type is certainly clear that there is no namespace in the `class-name`.

Thanks.

**Comment by dg** [comment]
Ehm, and what else could DateTime be?

**Comment by janbarasek** [comment]
In this particular case, nothing else.

For example, for classes that do not have a namespace, PhpStorm inserts a slash at the beginning so that it is immediately apparent.

What do you think?

**Comment by dg** [comment]
Can it be turned off somewhere? That's something I hate on PhpStorm.
