### ISSUE TITLE
ext-ds support

### ISSUE THREAD

**Issue by enumag** [nette/tracy#472]
Instead of arrays I much prefer using specialized data structures from ext-ds extension:

- https://github.com/php-ds/ext-ds
- https://www.php.net/manual/en/book.ds.php
- https://pecl.php.net/package/ds

Unfortunately Tracy dumper seems unable to show me the contents of the data structures which often leads to important info to be missing on the exception screen.

If I understand Tracy correctly then this should be possible using [`\Tracy\Dumper::$objectExporters`](https://github.com/nette/tracy/blob/c0f21d61bec95984470eeceee7d3e4496f3dee7f/src/Tracy/Dumper/Dumper.php#L74).

**Comment by dg** [comment]
Yes

**Comment by enumag** [comment]
Code snippet for myself, I'll try to work on it later.

```
\Tracy\Dumper::$objectExporters[\Ds\Vector::class] = function (\Ds\Vector $obj, Value $value, Describer $describer): void {
	foreach ($obj as $objectKey => $objectValue) {
		$describer->addPropertyTo($value, (string) $objectKey, $objectValue, Value::PROP_PRIVATE, null, \Ds\Vector::class);
	}
};
```

**Comment by enumag** [comment]
My related PR to Symfony (might need it for inspiration): https://github.com/symfony/symfony/pull/30311
