### ISSUE TITLE
Ability to remove some tab on tracy bar

### ISSUE THREAD

**Issue by milsorm** [nette/tracy#474]
I am looking for possibility to remove original UserPanel from tracy bar because I have prepared better one which improve behaviour for my project (temporary changing identities, showing current login in tracy bar etc.).

I am able to create new tracy panel which works fine but I cannot call any removePanel or hidePanel to remove/hide original UserPanel. The only possible way is to hide it through css.

Thanks a lot in advance.

**Comment by mabar** [comment]
Assuming that you have most common setup with nette/bootstrap:

```
security:
	debugger: false
```

**Comment by milsorm** [comment]
This works but also hide all descendants of UserPanel (also my enhanced version) :-(

**Comment by mabar** [comment]
How do you register your panel? The `debugger: false` option will just not add the original panel, no way it could affect other panels. https://github.com/nette/security/blob/79b2dfb0f3f6d0c19d45ab1f43cf5851c6aa3c58/src/Bridges/SecurityDI/SecurityExtension.php#L134-L141

**Comment by milsorm** [comment]
tracy:
  bar:
    - App\Utils\MyUserPanel

and MyUserPanel extends UserPanel (and has to create new $user inside because original $user is not protected (and that mean that it is hard to extend UserPanel).

My recommendation is to make $user in UserPanel protected (not private).

I will try to recognize why debugger: false did not work.

**Comment by milsorm** [comment]
My bad - old CSS in browser cache... :-) Sorry for that and thanks for answer.
