### ISSUE TITLE
Detection of the place where the redirect occurred

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#478]
Hello,

Tracy can show on the Bar that there has been a redirect. However, in complex applications, there is no easy way to know where a redirect has occurred. So find out the file and line number. This can be useful information for debugging.

The display of the file and the line where the redirect took place could be sent in a special HTTP header. The default sending of the header could be `nette/http`, while it would be sent only when the debug mode is active.

> Pro tip:
>
> The path to the file could be sent as `md5($filename)` to hide it. The bar can use the `get_included_files()` function when overwriting md5 to a filename.

Thanks!

**Comment by dg** [comment]
How can this be determined?

**Comment by janbarasek** [comment]
I wrote it right at the beginning of the issue.

Unfortunately, there is no way to detect a redirect site, but Tracy can provide an interface to proactively submit a path. A package like `nette/http` can capture the path of the `->redirect()` call via `debug_backtrace()` and automatically pass it to Tracy via a bridge.

It will not work for all cases, but for Nette applications it will.

**Comment by dg** [comment]
And why should it send an HTTP header? You don't need to have that information in your browser.

**Comment by dg** [comment]
If you find a general solution, feel free to reopen it, but I don't think there is one.
