### ISSUE TITLE
Broken Tracy bar when used with BrowserSync

### ISSUE THREAD

**Issue by adamkudrna** [nette/tracy#48]
When using Tracy together with [BrowserSync](http://www.browsersync.io/), Tracy bar produces invalid HTML code at the end of file like this:

```
<!-- Tracy Debug Bar -->
<script>
(function(onloadOrig) {
    window.onload = function() {
        if (typeof onloadOrig === 'function') onloadOrig();
        var debug = document.body.appendChild(document.createElement('div'));
        debug.id = 'tracy-debug';
        debug.innerHTML = "&nbsp;\n\n<style id=\"tracy-debug-style\"

// …
// Tracy's code continues.
// …

doc = win.document;\n\t\tdoc.write('<!DOCTYPE html><meta charset=\"utf-8\"><style>' + $('#tracy-debug-style').dom().innerHTML + '<\\\/style><script>' + $('#tracy-debug-script').dom().innerHTML + '<\\\/script><body id=\"tracy-debug\">
<script type='text/javascript'>//<![CDATA[
;document.write("<script defer src='//HOST:3000/socket.io/socket.io.js'><\/script><script defer src='//HOST:3001/client/browser-sync-client.0.9.1.js'><\/script>".replace(/HOST/g, location.hostname));
//]]></script>
');\n\t\tdoc.body.innerHTML = '<div class="\&quot;tracy-panel" tracy-mode-window\"=""

// Unescaped HTML continues.
// …
```

BrowserSync also injects JS a HTML into DOM which seems to be the cause of conflict. You may notice socket.io script injected by BrowserSync close to the end. However, since BrowserSync itself works fine with Tracy and does not seem to be affected by this error, it looks like it is Tracy's issue. If not, please let me know to report the issue at BrowserSync.

**Comment by hrach** [comment]
Have somebody solve this? cc @enzy

**Comment by enzy** [comment]
We have some sort of workaround in [mango-cli watch task](https://github.com/manGoweb/mango-cli/blob/master/lib/tasks/watch_reload.js#L23) which works for us...
