### ISSUE TITLE
Dumper::toHtml() in snippet - Uncaught TypeError: dest is null

### ISSUE THREAD

**Issue by BigOHenry** [nette/tracy#482]
Version: 
PHP 8.0
TRACY 2.8

### Bug Description
When using `\Tracy\Dumper::toHtml($array)` in snippet you cannot open 2nd level in array. There is an error in console `Uncaught TypeError: dest is null `

### Steps To Reproduce
1. Latte code
```
    <div n:snippet="show_data">
        {if $show_data}
            {\Tracy\Dumper::toHtml(['test' => ['x' => ['y' => ['z' => 'test']]]])|noescape}
        {/if}
    </div>
```
2. After redraw a snippet it render this:
![obrazek](https://user-images.githubusercontent.com/15823552/116368049-3e199200-a808-11eb-86f6-5101b114dace.png)

3. If you click on arrow to expand 'x' key, there is an error in console log `Uncaught TypeError: dest is null` at this code:
![obrazek](https://user-images.githubusercontent.com/15823552/116368416-994b8480-a808-11eb-8790-ccf03b98c92c.png)

If the same code is used out of the snippet, it works:
![obrazek](https://user-images.githubusercontent.com/15823552/116368657-dd3e8980-a808-11eb-94ba-5ea5a51f1576.png)

If using much bigger array with more depth even first level cannot be opend. Same error.

Thank you!

**Comment by dg** [comment]
There you need to turn off JS used for dumping:

```php
Tracy\Dumper::toHtml($var, [Tracy\Dumper::LAZY => false])
```

**Comment by BigOHenry** [comment]
Thank you, workaround works.
