### ISSUE TITLE
Missing data in Tracy bar

### ISSUE THREAD

**Issue by Lumeriol** [nette/tracy#483]
Version: 2.8-dev

### Bug Description
Probably with resolving issue #482 there is a new problem. When I load a new page, all data in bar are visible (Nette sessions, logged user). But with page refresh data are missing and only empty boxes are visible.
Problem is somewhere in Tracy\Dumper\assets\dumper.js.

### Steps To Reproduce
Refresh page by F5.

![image](https://user-images.githubusercontent.com/3526195/117110989-3ec1a380-ad87-11eb-8282-3411bc17b716.png)

**Comment by dg** [comment]
can you check to see if it's working yet?

**Comment by Lumeriol** [comment]
Yes, now all is working correctly, thanks.
