### ISSUE TITLE
Fetch request not triggering AJAX bar

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#485]
Version: 2.7.8

### Bug Description
Making a `fetch()` request doesn't trigger the AJAX bar to load as it would with a traditional XMLHttpRequest ajax call.

### Steps To Reproduce

```
	<script>
	fetch(
		'/test.php',
		{
			method: 'GET',
			headers: {
				'Content-Type': 'application/json',
				'Accept':       'application/json',
				'X-Requested-With': 'XMLHttpRequest'
			}
		}
	)
	.then( response => response.json() )
	.then( json => console.log(json) );
	</script>
```

### Expected Behavior
I would expect an AJAX bar to load with details about that request

The browser Network tab shows that the `X-Requested-With': 'XMLHttpRequest` was correctly included and if I check `$_SERVER['HTTP_X_REQUESTED_WITH']` in the test.php file, it returned `XMLHttpRequest`.

Sorry if I am missing something obvious - it's my first time working with `fetch()`.

**Comment by dg** [comment]
I have added a working example to `examples/`. Please try to find out why it doesn't work for you.

**Comment by adrianbj** [comment]
Thanks @dg - your example works fine. Turns out the issue with my example is not specific to `fetch()`. The issue is that the call was automatically, rather than being a user triggered event. If I wrap the `fetch()` in a `document.addEventListener('DOMContentLoaded', (event) => {` then it works as expected.

Sorry to waste your time.
