### ISSUE TITLE
CLI error should be rendered directly to Terminal

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#490]
I think CLI errors should be rendered directly to Terminal for better debug.

Concept:

![Screenshot from 2021-06-03 14-57-26](https://user-images.githubusercontent.com/4738758/120648579-17d8b900-c47c-11eb-8c70-29137b2d531f.png)

Inspired by: https://github.com/baraja-core/nette-symfony-console/blob/master/src/Console.php#L67

Thanks.

**Comment by dg** [comment]
duplicated to #486 ?

**Comment by janbarasek** [comment]
A little yes. I would also add the file name and line number (for easy copying) and snippet code where the exception was thrown.

What do you think?

**Comment by dg** [comment]
So it's about dumping a snippet of source code in debug mode? Yeah, that can be useful.

**Comment by janbarasek** [comment]
Yes, it will. I can try implement it.

**Comment by janbarasek** [comment]
Closed by #494.
