### ISSUE TITLE
PHAR release possibly corrupted?

### ISSUE THREAD

**Issue by dmitriypavlov** [nette/tracy#491]
Version: 2.8.5

### Bug Description
In 2.8.5 PHAR release the use of `?_tracy_bar=js` parameter fetches corrupted javascript with some kind of Java stacktrace inside which renders Tracy inoperable.

![tracy](https://user-images.githubusercontent.com/3692969/121010746-7664a680-c79e-11eb-8458-3c95aa29aaed.png)

### Steps To Reproduce
Use 2.8.5, add `?_tracy_bar=js` url parameter

### Expected Behavior
Javascript should not be corrupted with Java stacktrace

### Possible Solution
PHAR compilation problem?

**Comment by dg** [comment]
It looks like a problem with the Google Closure compiler, I built tracy.phar again.
