### ISSUE TITLE
BlueScreen displays "\r\n" and "\t" in exception's message

### ISSUE THREAD

**Issue by EvilKraft** [nette/tracy#492]
Version: 2.8.4

### Bug Description
... BlueScreen displays "\r\n" and "\t" in exception's message

### Steps To Reproduce
... Make an SQL error.

[https://ibb.co/16GJ69D](https://ibb.co/16GJ69D)

### Expected Behavior
... Expected clear message text

### Possible Solution
in Tracy/BlueScreen/BlueScreen->formatMessage()
line 375
Add: 
`$msg = str_replace('<i>\r\n</i>', '', $msg);`
`$msg = str_replace('<i>\t</i>', '', $msg);`

**Comment by JanTvrdik** [comment]
Try 2.8.5 https://github.com/nette/tracy/commit/ad87baaaf1a16dfb6723efab7d8d90efdca2cf32
