### ISSUE TITLE
Debugger reserved str_repeat() can be too slow

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#493]
Hello,

In some cases, evaluating the `str_repeat()` function for reserved memory can be relatively slow and take up to tens of milliseconds.

https://github.com/nette/tracy/blob/b23da41363546aa750d9f698f21e14815bd78913/src/Tracy/Debugger/Debugger.php#L163

Runtime example from the profiler:

![Screenshot from 2021-06-08 09-49-28](https://user-images.githubusercontent.com/4738758/121148701-4b339300-c842-11eb-98a5-e917c030b47f.png)

Test script:

```php
\Tracy\Debugger::timer('repeat');
for($i=1;$i<=10;$i++) {
    $a = str_repeat('t', 500000*$i);
    dump([
        $i,
        strlen($a),
        \Tracy\Debugger::timer('repeat') * 1000
    ]);
}
```

Profiler results:

![Screenshot from 2021-06-08 09-49-54](https://user-images.githubusercontent.com/4738758/121148762-58508200-c842-11eb-96c4-e421a4eacbd1.png)

Now I don't know how to save time effectively. This problem bothers me, because in some cases it slows down the processing of all requests.

Thanks.

**Comment by jakubvojacek** [comment]
I've noticed the same in blackfire but never really thought about it since thats in vendor and not my code. Nevertheless, it'd be nice to speed it up :)

**Comment by janbarasek** [comment]
I analyzed the problem and the reason for the slowdown is that PHP has to dynamically expand the memory used when storing a long string in a variable.

One of the possible solutions is to fill the variable directly, for example:

```php
/** @var string|null reserved memory; also prevents double rendering */
public static $reserved = 'tttt....';
```

Or fill the memory in another way and not use the variable.

**Comment by dg** [comment]
That's the price of memory allocation, and there's no way to speed it up.

**Comment by JanTvrdik** [comment]
The `str_repeat` function with single byte string is heavily optimized in php-engine to a single `memset` call.
https://github.com/php/php-src/blob/php-8.0.7/ext/standard/string.c#L5184

@janbarasek You can always set `$reservedMemorySize` to zero if you wanto effectively disable this feature.
