### ISSUE TITLE
Bluescreen: show thrown exception class name even when the exception has no message

### ISSUE THREAD

**Issue by dakur** [nette/tracy#500]
Version: 2.8.4

### Bug Description
When an exception is thrown without a message, Tracy doesn't show its class name in the bluescreen header. When it has message, both class name and the message is displayed.

|Without message|With message|
|---|---|
|![image](https://user-images.githubusercontent.com/9862581/128819431-0414eac9-ece0-4833-876a-53b823bf39cf.png)|![image](https://user-images.githubusercontent.com/9862581/128824807-d68992e9-285b-4916-8bc8-ec4683821bdc.png)|

### Steps To Reproduce
Throw an exception with and without a message.

### Expected Behavior
Always show class name – no matter if message is provided or not.

### Possible Solution
To remove [this condition](https://github.com/nette/tracy/blob/v2.8.5/src/Tracy/BlueScreen/assets/content.phtml#L31). It was introduced in https://github.com/nette/tracy/commit/64f15214b0c4f4278d872421a01296c48c4ec65a I can't see any reason why it has to be there.

**Comment by dakur** [comment]
Just a note: I undestand, that class name has no sense if one uses only one or two types of exceptions for everything. But when you try to use exceptions to be self-descriptive, the name makes sense on its own and it doesn't need a message.

**Comment by dg** [comment]
Is master afected too?

**Comment by dakur** [comment]
Looks like: https://github.com/nette/tracy/blob/master/src/Tracy/BlueScreen/assets/content.phtml#L31

**Comment by dakur** [comment]
@dg Did you close it accidentally? There is no change in master..

**Comment by dg** [comment]
I understand it works in master. Or does it?

**Comment by dakur** [comment]
You've asked if master is affected, I've answered "looks like". So it doesn't work. 🙂 I've posted links to source code to both latest tag and master – the code is the same – hiding exception name.

**Comment by dg** [comment]
So please try it and feel free to reopen.

**Comment by dakur** [comment]
I don't know if there was a reason for such condition or not. Can I safely remove it? https://github.com/nette/tracy/blob/master/src/Tracy/BlueScreen/assets/content.phtml#L31

Also, I don't have permission for reopening issues.

**Comment by dg** [comment]
Zkusím to česky :) Můžeš prosím ověřit, že tvůj problém existuje i v masteru? Pokud ne, není co řešit. Pokud ano, hoď sem kód, abych mohl chybu zreplikovat.

**Comment by dakur** [comment]
No vycházel jsem z toho, že v masteru je pořád stejný kód jako v affected version co do toho inkriminovaného místa - proto jsem pořád psal, že to nefunguje. Nicméně koukám, že v masteru to opravdu funguje, tomu teda nerozumím. Přece `$exception->getMessage()` nemůže být najednou non-empty.

Nicméně díky za opravu. 🙂👍
