### ISSUE TITLE
Debugger::$keysToHide not functional

### ISSUE THREAD

**Issue by dmitriypavlov** [nette/tracy#502]
Version: 2.8.6

### Bug Description
`Debugger::$keysToHide = ['foo'];`

causes

**Fatal error: Uncaught Error: Access to undeclared static property Tracy\Debugger::$keysToHide**

**Comment by mabar** [comment]
`BlueScreen::$keysToHide = ['foo'];`

https://github.com/nette/tracy/blob/f3d2d6a1230a0a1a7b116c071ae4937e5e30101a/src/Tracy/BlueScreen/BlueScreen.php#L36

**Comment by dmitriypavlov** [comment]
Could this problem be caused by my misconfiguration?


require_once('../library/vendor/tracy-2.8.6.phar');
use Tracy\Debugger;
Debugger::$strictMode = true;
Debugger::$keysToHide = ['foo'];
Debugger::enable(Debugger::DEVELOPMENT);

**Comment by mabar** [comment]
`$keysToHide` property is in `BlueScreen`, not `Debugger`.

**Comment by dmitriypavlov** [comment]
According to docs it is in Debugger or am I missing something?

![Screenshot 2021-08-19 at 13 28 34](https://user-images.githubusercontent.com/3692969/130053739-d235bcb4-8fc4-4b82-8d3c-31f34c40e392.png)

**Comment by dmitriypavlov** [comment]
I am sorry. I just realized my mistake. Documentation seems confusing on this point.

`BlueScreen::$keysToHide = ['foo'];`

**Comment by dg** [comment]
Fixed in 2.8.7
