### ISSUE TITLE
Missing Blue screen

### ISSUE THREAD

**Issue by Lumeriol** [nette/tracy#521]
Version: 2.9.x (currently RC2)

### Bug Description
In Presenter, if try to access ActiveRow to wrong column via magic call ($entity->wrong_column), there is only white screen with error stack text and created log file (on localhost).
Logged is Warning - Undefined array key "file" with error ...\vendor\tracy\tracy\src\Bridges\Nette\Bridge.php:100 with Call stack  ...\tracy\tracy\src\Tracy\BlueScreen\BlueScreen.php:211

But when I use method offsetGet() on ActiveRow, there is correct blue screen with Nette\MemberAccessException "Cannot read an undeclared column 'wrong_column', did you mean 'correct_column'?"

Problem is only in presenters, when I try same code in component (extended Control), I got correct exception.

### Steps To Reproduce
Any DB access via ActiveRow to non-existing column

```
$category = $this->categoryFacade->getCategory($url);

bdump($category->si_primary); // should be is_primary
```

### Expected Behavior
Get MemberAccessException instead warning about undefined array key.

**Comment by dg** [comment]
I tried to fix it. Can you please verify that it's working properly now?
