### ISSUE TITLE
Error when trying to check session storage

### ISSUE THREAD

**Issue by andrei-dascalu** [nette/tracy#528]
Version: 2.9.0

### Bug Description

When enabling Tracy on an environment where sessions are stored in Redis (aka, `session_storage_path = tcp://redis.host`) then method `Debugger::getSessionStorage()` will result in a fatal error `is_dir(): Unable to find the wrapper "tcp" - did you forget to enable it when you configured PHP?` as is_dir will not work over tcp

### Steps To Reproduce

PHP environment set to store session in Redis

### Expected Behavior

Tracy should work without a fatal error

### Possible Solution

I am not entirely sure why Tracy needs to check session storage at all. It's not possible in all environments, depending on configuration.

**Comment by JanTvrdik** [comment]
This should be already fixed in master https://github.com/nette/tracy/commit/b917af66e7498b226a91ca9d3ee9def92e36d138
Can you check if it works for you?

**Comment by andrei-dascalu** [comment]
Hi, 

I've updated to "dev-master" but this doesn't (always) help.

While it does silence the error, it doesn't apply when there's a customer error handler involved (for example to transform php's errors to exceptions).

As a workaround though, in case there are other people using customer error handlers, you can probably check the message to match the string and ignore the error - but that's not exactly the best practice.

Ideally there should be a better way to check storage than using is_dir.

**Comment by dg** [comment]
The custom error handler must be written correctly:

```php
		set_error_handler(function (int $severity, string $message, string $file, int $line) {
			if (!(error_reporting() & $severity)) {
				return;
			}

			// do something...
			throw new \ErrorException($message, 0, $severity, $file, $line);
		});
```

Is there some other problem with is_dir?

**Comment by dg** [comment]
Unfortunately, the documentation does not tell the truth. I sent a fix, but it's still not merged :( https://github.com/php/doc-en/pull/1196

**Comment by dg** [comment]
I'm closing this up there's really no reason to use realpath to verify existence of directory or to resolve path. If you came across a specific real case, feel free to reopen.

**Comment by andrei-dascalu** [comment]
@dg at the moment, the severity sent in this case when using @ is 2, so checking the severity doesn't work in a custom error handler.

We have a workaround matching the error message by string but this is not a proper way.

**Comment by dg** [comment]
Yes, is was 2 always, since PHP 4. https://3v4l.org/9Umsd
