### ISSUE TITLE
White Screen after upgrade

### ISSUE THREAD

**Issue by masonjo** [nette/tracy#536]
Version: 2.9.1

### Bug Description
Would get a White Screen of Death with 2.9.1.  Could not find any errors in my log or on the screen.
 
### Steps To Reproduce
Commented out lines until I get 2.9.1 to work to some degree by removing the dispatch function from Debugger.php

I saw this in the release notes **Debugger: enable() calls dispatch() always** I think it is my problem.

### Possible Solution
I changed my composer.json to hold at 2.9 and everything is fine.

**Comment by dg** [comment]
Does this also apply to the latest version 2.9.3?

**Comment by Lukzat** [comment]
I think I have the same problem, see screen. But it only happens to me on Chrome. Tracy displays correctly on Firefox. The screens are with tracy 2.9.3, but I also tried an older project with 2.7.5 and there is the same problem. It should be noted that this only happens to me inside the chrome console, if I open the script in a new tab, then tracy will display correctly.

Chrome:
![image](https://user-images.githubusercontent.com/15264154/173763406-ba9c3108-d0a5-4e65-9804-361dca072720.png)
Firefox:
![image](https://user-images.githubusercontent.com/15264154/173763483-3936f379-383e-4d2e-8676-746715f77511.png)

<html>
<body>
<div class="panel" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">HTTP response</a></h2><div class="tracy-collapsed inner"><h3>Headers</h3><div class="outer">

Content-Type | text/html; charset=UTF-8
-- | --


</div></div></div><footer style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><ul><li><b><a href="https://nette.org/make-donation?to=tracy" target="_blank" rel="noreferrer noopener">Please support Tracy via a donation 💙️</a></b></li><li>Report generated at 2022/06/15 09:02:47</li><li>PHP 7.4.7</li><li>Apache/2.4.25 (Debian)</li><li>Tracy 2.7.5</li></ul></footer>
</body>
</html>HTTP response
Headers
Content-Type	text/html; charset=UTF-8
[Please support Tracy via a donation 💙️](https://nette.org/make-donation?to=tracy)
Report generated at 2022/06/15 09:02:47
PHP 7.4.7
Apache/2.4.25 (Debian)
Tracy 2.7.5

**Comment by dg** [comment]
Did you find anything? If the problem still persists, write.
