### ISSUE TITLE
Error line is not highlighted on CLI mode

### ISSUE THREAD

**Issue by janbarasek** [nette/tracy#539]
Version: v2.9.1

### Bug Description

When rendering the code snippet to Terminal, the line where the error occurred is not highlighted.

For example:

![Snímek obrazovky 2022-04-10 v 19 30 22](https://user-images.githubusercontent.com/4738758/162634148-acccbcf0-4801-4d1c-af38-034e6ccbfafa.png)

### Steps To Reproduce

Throw exception in debug and CLI mode.

### Expected Behavior

Render line with red background.

**Comment by dg** [comment]
What are you offering in return?

**Comment by janbarasek** [comment]
The more happy programmers who now have to look for exactly where the wrong line is in the text.

Highlighting the active row (including the column) could be implemented in the CLI like this:

![Snímek obrazovky 2022-04-11 v 9 04 51](https://user-images.githubusercontent.com/4738758/162682817-c2bb1494-0f3d-4332-a2c3-4de0779f131e.png)

**Comment by mabar** [comment]
I assumed you expected money in exchange for help, not someone else's happiness. It doesn't work the other way around? Where's the quid pro quo?

**Comment by dg** [comment]
This isn't working for me as motivation. But if it does for you, send a PR.

**Comment by janbarasek** [comment]
Ok.
