### ISSUE TITLE
`Content-Length` warning is reported even when sending `FileResponse` 

### ISSUE THREAD

**Issue by kukulich** [nette/tracy#541]
Version: 2.9.2

### Bug Description
`LogicException: Tracy cannot display the Bar because the Content-Length header is being sent` is reported even when sending `FileResponse`, eg. generating `sitemap.xml`.

### Expected Behavior
No warning :)

### Possible Solution
Check `Helpers::isHtmlMode()` ?

**Comment by dg** [comment]
Yeah, that should be checked elsewhere.
