### ISSUE TITLE
Tracy causes scrollbars after the update

### ISSUE THREAD

**Issue by lubomirblazekcz** [nette/tracy#545]
Version: 2.9.3

### Bug Description
https://github.com/nette/tracy/commit/ef2e060a8885cba834fb793e20dab9b6ee24260b
Resets styles that are meant to be `overflow: hidden` by design. This added unexpected scrollbars for some of our projects.

What is the reason behind this change?

**Comment by dg** [comment]
cc @Rixafy

**Comment by Rixafy** [comment]
I thought it will be used only when bluescreen is thrown 🤔 because there were a bug that if you had bootstrap modal open and send an ajax form, following bluescreen error will be not scrollable, since modal will disable body overflow.
