### ISSUE TITLE
After expand services in DI panel opened in new window there is nothing rendered

### ISSUE THREAD

**Issue by petrparolek** [nette/tracy#554]
Versions: all 2.9.x ( 2.9.0 - 2.9.x-dev), 2.8.x are ok.

### Bug Description
After expand services in DI panel opened in new window there is nothing rendered.

![obrazek](https://user-images.githubusercontent.com/6066243/218322216-8f4c6a59-f5f1-4813-a7d0-c1c7bce93a59.png)

### Expected Behavior
Show object dump

**Comment by dg** [comment]
Could you find out which commit broke it?

**Comment by petrparolek** [comment]
I checked out v2.9.0. I hard reseted each commit by commit. I found out 8aea3ae187d535729018526c8e321e6b1aafec65 breaks it.

**Comment by dg** [comment]
I don't think that's gonna be it. I'm guessing it hasn't been working for too long.

**Comment by petrparolek** [comment]
I don't know

**Comment by dg** [comment]
Anyway, it's a lot of work to fix it, try offering some financial motivation.
