### ISSUE TITLE
2.10 regresion - contents of DateTime is not dumped in log

### ISSUE THREAD

**Issue by janlanger** [nette/tracy#558]
Version: 2.10.0

### Bug Description
Since 2.10 there is no internal info from DateTimeImmutable showed in log file.

### Steps To Reproduce
2.10:
![image](https://user-images.githubusercontent.com/415695/224991879-144f1d05-afed-4e66-b7b5-06f937a35074.png)

### Expected Behavior
2.9.7:
![image](https://user-images.githubusercontent.com/415695/224992023-3f321f75-3da0-412e-b65d-07813d13d082.png)

**Comment by dg** [comment]
Fixed
