### ISSUE TITLE
PSR adapters: swap names

### ISSUE THREAD

**Issue by dakur** [nette/tracy#564]
I've got confused a lot about the names of adapters to/from PSR. When I read `PsrToTracyLoggerAdapter`, I would definitely expect that such adapter implements PSR interface and forward passed error/log to tracy logger. But it does the opposite! That's super confusing from developer's point of view.

Can it be changed please?

**Comment by dg** [comment]
No :-)

**Comment by JanTvrdik** [comment]
Unfortunately the name make sense both ways. It's a known issue.

PsrToTracyLoggerAdapter converts "PSR logger" to "Tracy logger". So if you have a PSR logger and want to have Tracy logger, this is the adapter you would use.

**Comment by dakur** [comment]
Thanks for elaboration. I still don't really see it but maybe it's because I didn't encounter it from the other side.

**Comment by MartinMystikJonas** [comment]
It is question if you look at direction of data flow (convert Tracy log to PSR log) or direction of type change by adapter (adapt PSR logger to Tracy logger). For Adapter later makes more sense IMHO.
