### ISSUE TITLE
PHP 8.2: ErrorException::$skippable is deprecated

### ISSUE THREAD

**Issue by petrf89** [nette/tracy#570]
Version: 2.10.3
- PHP version: 8.2
- nette/application 3.1.11
- nette/bootstrap 3.2.0

### Bug Description
```
Creation of dynamic property ErrorException::$skippable is deprecated
/app/vendor/tracy/tracy/src/Tracy/Debugger/DevelopmentStrategy.php:87
```

### Steps To Reproduce
call Debugger::shutdownHandler 

### Expected Behavior
no deprectaed notice :)

**Comment by dg** [comment]
Are you using a custom error handler or something non-standard?

**Comment by dg** [comment]
no response
