### ISSUE TITLE
bar.css is missing background-repeat for #tracy-debug-bar

### ISSUE THREAD

**Issue by srigi** [nette/tracy#574]
Version: 2.10.5

### Bug Description
I noticed, that Tracy bar is being transparent completely, which is annoying on a dark background. See the screenshot below:

![Screenshot 2024-01-20 at 19 55 27](https://github.com/nette/tracy/assets/295197/1d7d142f-caa6-4867-9997-636587c3dcf9)

I also noticed, that element `#tracy-debug-bar` has a background image set, which is a 1px strip. However, the CSS is missing the `background-repeat: repeat-x`, which makes this image ineffective. Adding this CSS rule will fix this issue:

### Expected Behavior
![Screenshot 2024-01-20 at 19 59 59](https://github.com/nette/tracy/assets/295197/7df573f9-83c5-4075-a24f-2cbc1da638b1)

### Possible Solution
Add `background-repeat: repeat-x` to [bar.css · #tracy-debug-bar](https://github.com/nette/tracy/blob/e26bb832ae7ff97b0bb2981d93d03a124fd7971a/src/Tracy/Bar/assets/bar.css#L94C1-L94C17)

**Comment by dg** [comment]
It is not transparent because it has a set color, and repeat is the default value.
