### ISSUE TITLE
Tracy\Bar cannot be disabled

### ISSUE THREAD

**Issue by hranicka** [nette/tracy#82]
It would be nice to have an option for disabling Tracy\Bar's output.

The output is very long JavaScript and eg. on mobile devices it can breaks other JavaScript processing.

Also, see:

* http://forum.nette.org/cs/20733-jak-vypnout-debug-bar-pro-response
* https://www.google.cz/search?q=nette+disable+debug+bar+site:forum.nette.org

**Comment by bazo** [comment]
pretty please add the option to disable the bar output

**Comment by JanTvrdik** [comment]
@bazo That help with implementation https://github.com/nette/tracy/pull/83
