### ISSUE TITLE
New Bar icons

### ISSUE THREAD

**Issue by medhi** [nette/tracy#97]
Are you open to change the bar icons? I would suggest to use Fontawesome font to generate bigger icons to look good on retina.

My suggestions:

Execution time: http://fontawesome.io/icon/clock-o/
Memory: http://fontawesome.io/icon/bar-chart/
Routes: http://fontawesome.io/icon/road/
Database: http://fontawesome.io/icon/database/
Identity: http://fontawesome.io/icon/user/

I suppose, 32x32px should be enough for retina displays.

License allows use icons without attribution, but i would suggest to mention it somewhere.

**Comment by dg** [comment]
Do you have any preview, how it will look?

**Comment by medhi** [comment]
![snimek obrazovky 2015-02-07 v 22 08 37](https://cloud.githubusercontent.com/assets/522848/6093988/f078cab2-af15-11e4-9be9-024222133dac.png)

**Comment by dg** [comment]
Thank you!

**Comment by enumag** [comment]
@medhi I like that. Especially the routing icon. :-)

**Comment by dg** [comment]
As with the redesign of the operating system, the 3rd party addons will now look ugly.

**Comment by fprochazka** [comment]
:+1: lovely

**Comment by solcik** [comment]
:+1:

**Comment by milo** [comment]
Looks nice but colors needed. Isn't purpose of icons to make searching things faster?

**Comment by dg** [comment]
For comparsion:

![2015-02-07_22-50-47](https://cloud.githubusercontent.com/assets/194960/6094102/f072d610-af1b-11e4-8d45-7cec1cd8fe86.png)

**Comment by medhi** [comment]
I'll try make coloured preview.

**Comment by dg** [comment]
My font is not as bold as your, probably cause I am using Windows, can you place here screenshot of current design?

**Comment by Majkl578** [comment]
@dg: Easy solution, CSS grayscale filter. http://davidwalsh.name/convert-images-grayscale

**Comment by dg** [comment]
Ad icons: why to generate bitmaps from fonts? SVG is fine.

**Comment by soundake** [comment]
:+1:

**Comment by kacer** [comment]
:-1: I prefer coloured icons. It is easier to distinguish them.

**Comment by fprochazka** [comment]
It would be nice to have icons gray and colored on hover (which can be done by css filter).

**Comment by TomPastyrik** [comment]
Really like it but I have to agree with the colors. Colors on hover are kinda pointless considering their HCI function in this case - to quickly find requested data only by looking (no mouse movement). Finding the place for my mouse to hover is a secondary goal, the look should be considered as  a primary one.

**Comment by fprochazka** [comment]
@milo @TomPastyrik good poin

**Comment by hrach** [comment]
:+1: for grayscaled. Colors do not help in this case ;) Actually, it makes it harder to read, because of the noise. the most important is the shape.

**Comment by JanTvrdik** [comment]
:-1: I prefer colors because I have seen what happened to Visual Studio when they turn all icons to grayscale.

**Comment by hrach** [comment]
@JanTvrdik but you are comparing different things. Icon without label is useless. Actually, here - icons function are much more to separate things than to identify. Every visualized entry is totally understandable without icons. Menu icons without icons would be nothing ...

**Comment by Grelek** [comment]
:+1: for new icons. I don't care if they're grey or colored. :)

**Comment by enumag** [comment]
@hrach :+1: I also prefer non-colored version. But it should be pretty easy to make this configurable via local-config.neon - I don't care which version would be default.

**Comment by JanTvrdik** [comment]
@hrach Not all bar panel uses labels.

**Comment by kacer** [comment]
As of colors, the proposed screen by @medhi is maybe the worst approach that I can imagine - light gray icons on light gray background. Have you tried it on a crappy TN display? Even new ThinkPads have these…

**Comment by dg** [comment]
Colors are really important for quick orientation, and maybe single color icons are better than current icons.

**Comment by medhi** [comment]
Coloured version

![snimek obrazovky 2015-02-08 v 0 00 14](https://cloud.githubusercontent.com/assets/522848/6094326/8dfb490e-af25-11e4-9b13-6acad8230b6d.png)

**Comment by hrach** [comment]
Shut up and take my money. I love colored version.

**Comment by OzzyCzech** [comment]
:+1:

**Comment by medhi** [comment]
@dg What do you mean by "current design"?

**Comment by dg** [comment]
Colored version is great! Will you prepare PR?

**Comment by TomPastyrik** [comment]
:+1:  Awesome!

**Comment by JanTvrdik** [comment]
Now we just need the Tracy logo in higher resolution.

**Comment by fprochazka** [comment]
The https://github.com/nette/tracy/issues/97#issuecomment-73387635 is awesome :+1:

**Comment by medhi** [comment]
@dg yep

**Comment by dg** [comment]
@medhi without bitmaps, yes?

**Comment by medhi** [comment]
@dg yes, coloured SVG files linked as images. Other version can be SVGs right in HTML, it means less requests. What is better?

**Comment by JanTvrdik** [comment]
I would prefer putting the images to external files and just readfile them (because base64 is not required according to http://css-tricks.com/probably-dont-base64-svg/)

**Comment by dg** [comment]
Requests are not possible, it must be inlined.

**Comment by medhi** [comment]
OK, I put them into templates/icons folder and readfile() them.

**Comment by dg** [comment]
:+1:

**Comment by JanTvrdik** [comment]
I do not recommend this, but I remembered that in PHP you can do this :smile: 
~~~php
readfile('php://filter/read=convert.base64-encode/resource=icon.svg');
~~~

**Comment by dg** [comment]
ad used colors: what about to use skin color for human icon, asphalt color for route, etc?

**Comment by dg** [comment]
see http://tools.ietf.org/html/rfc2397, base64 is optional and will be not efficient in this case, urlencoding() is IMHO better.

**Comment by medhi** [comment]
@dg skin of whom? European, Asian or African? :) Asphalt is dark grey. And other other icons? I'll try different version, but these colours could be quite insignificant.

**Comment by dg** [comment]
Red (and also green) icons can have false associations, so person with european skin color is neutral, it does not create the impression that an authentization error has occurred. Red color is great for error panel.

**Comment by dg** [comment]
Btw, in Tracy Bar man can see what progress are doing browsers. In first version everything was bitmap, all shadows, gradients etc ;)

**Comment by medhi** [comment]
I tried to avoid colours, which can associate error or success statuses and tried to keep the icons still distinguishable.
![snimek obrazovky 2015-02-08 v 1 02 16](https://cloud.githubusercontent.com/assets/522848/6094534/2edd70ba-af2e-11e4-8eed-ed3e2c2df4be.png)

**Comment by medhi** [comment]
Maybe the pink one could be more pinkish :)

**Comment by vysinsky** [comment]
:+1: awesome! I like the latest version

**Comment by Northys** [comment]
I liked the previous version more. 

Ad colors: you don't even know there are any icons you remember order of data like anything else you see everyday for thousand hours.

**Comment by vojtech-dobes** [comment]
Haha, I apologize for such a terrible contribution to this discussion :) - but the [latest version](https://github.com/nette/tracy/issues/97#issuecomment-73389868) seems to me too bluish. Semantic colors are great, but diverse enough palette is also valuable. (anyway, great stuff @medhi)

**Comment by medhi** [comment]
One more...
![snimek obrazovky 2015-02-08 v 1 26 23](https://cloud.githubusercontent.com/assets/522848/6094611/91c0a37a-af31-11e4-9326-33e924f15c6b.png)

**Comment by dg** [comment]
User icon from previous version was better, because bright color is required to distinguish it from unlogged state.

Green clock was IMHO ok, but it should be tested.

**Comment by dg** [comment]
What about to use different icon for memory, something like this http://www.flaticon.com/free-icon/computer-cpu_63990 or this http://fontawesome.io/icon/tachometer/ …

**Comment by Northys** [comment]
dg: don't like it

**Comment by vysinsky** [comment]
@dg processor has nothing to do with memory and tachometer is for speed - I like what is currently used in proposed design

**Comment by Northys** [comment]
@vysinsky :+1:

**Comment by dg** [comment]
It looks like memory chip, not CPU.

**Comment by vysinsky** [comment]
<ot>
Than the designer sucks when he calls it CPU and someone sees something else.
</ot>

**Comment by dg** [comment]
[ot] Complete nonsense. Btw it is in data-storage package. [/ot]

**Comment by JanTvrdik** [comment]
This looks like RAM but I still prefer the current icon:
http://www.flaticon.com/free-icon/data-storage_64321

**Comment by medhi** [comment]
Beside, we need also the "dump variables" icon. Suggestions:

http://fontawesome.io/icon/book/
http://fontawesome.io/icon/file-text-o/
http://fontawesome.io/icon/list/
http://fontawesome.io/icon/bullhorn/

**Comment by dg** [comment]
And this?
http://fontawesome.io/icon/binoculars/
http://fontawesome.io/icon/eye-slash/

**Comment by dg** [comment]
Suggestions for error icon:
http://fontawesome.io/icon/bug/
http://fontawesome.io/icon/exclamation-triangle/

**Comment by medhi** [comment]
@dg I am for fa-exclamation-triangle, because error doesn't mean bug. Why slashed eye? What about normal http://fontawesome.io/icon/eye/ ?

**Comment by medhi** [comment]
(for testing purposes - how can I induce error tab? I tried exception, but nothing show)

**Comment by JanTvrdik** [comment]
@medhi notice + disabled strict mode

**Comment by dg** [comment]
„Error doesn't mean bug“ the idea of which I will have to think deeper about :-)

**Comment by medhi** [comment]
@dg There can be bugs in an application, but it could still produce no errors :) I think bug can mean error, but also just unexpected behaviour.

**Comment by dg** [comment]
I agree that bugs could not produce errors, but the opposite implication isn't clear to me.

**Comment by medhi** [comment]
@dg It's not opposite implication. Just saying, that bug can be an error or an unexpected behaviour.

So are we settled about chosen icons?

Memory - keeping old one.
Dump - http://fontawesome.io/icon/eye/
Error - http://fontawesome.io/icon/exclamation-triangle/

Or should I give it some rest for few days to hear more opinions?

**Comment by dg** [comment]
Eye and exclamation are great.

Column graph as memory is not good…

**Comment by dg** [comment]
ot: today it is question whether memory tab is still important and should be always displayed.

**Comment by medhi** [comment]
I never use it.
If you decide to keep it, tachometer icon is little bit better than a column graph.

**Comment by Aurielle** [comment]
Kinda late for to party, but @medhi's redesign suggestion is awesome, little polishing (already in progress or so it seems) and I'd be happy to see it go live! :+1:

**Comment by medhi** [comment]
What about green user icon if logged in, and gray if logged out?

**Comment by kukulich** [comment]
I like the idea, however I think it will be much harder to create own panel icon that fits the new design.

**Comment by MartinSadovy** [comment]
[Last revision](https://github.com/nette/tracy/issues/97#issuecomment-73390483) is very pretty. But if you look, Tracy logo is still pixelated.

**Comment by kubinpetr** [comment]
:+1: for https://github.com/nette/tracy/issues/97#issuecomment-73390483

**Comment by medhi** [comment]
- user icons (logged, not logged), green color should be OK in this context
- new close icon
- new memory icon
- added variables icon
- added error icon

![snimek obrazovky 2015-02-08 v 13 05 26](https://cloud.githubusercontent.com/assets/522848/6096488/30f29122-af93-11e4-919c-11234ac4860a.png)

**Comment by kubinpetr** [comment]
@medhi :+1: This is the best solution!! https://github.com/nette/tracy/issues/97#issuecomment-73408118

**Comment by Northys** [comment]
still I don't like chip for memory, the graph was much better (memory *PEAK*)

**Comment by vysinsky** [comment]
What about some pie graph instead of bar graph?

**Comment by dg** [comment]
Allocated memory has nothing to do with pie graph - this is cargo effect. You are thinking about graph because there was graph for years. And there was graph just because Silk icons was very limited.

**Comment by nechutny** [comment]
Memory http://fortawesome.github.io/Font-Awesome/icon/line-chart/ ?
Arrow up as peak

**Comment by JanTvrdik** [comment]
I like the icons, not so much the colors. And we still need the logo in higher resolution,  @dg

**Comment by ddx32** [comment]
I really enjoy this discussion, debugbar could use a little visual refresh.

I made following adjustments to @medhi's mockup:

* I understand the need for colors, but I still find them distracting, so I propose a slight desaturation.
* The icons and data seem cluttered to me. I added paddings around so it's clearer to distinguish which icon represents which information and adjusted the sizes of icons. I think it's worth the extra pixels.
* I like @medhi's icon for memory better, but I couldn't find it.
* I suggest using an SVG Tracy logo. I just made this one using the Nasalization font (but the logo seems customized)
* What about using a dollar sign icon for variables? Stupid?

![debugbar](https://cloud.githubusercontent.com/assets/7354970/6096969/dc571c6a-afaa-11e4-8a1f-c2a66dde6bcd.png)

**Comment by fprochazka** [comment]
I'm against the padding, I have a lot of panels and I don't want the Debug Bar to wrap on my 24" display.

**Comment by dg** [comment]
This is Tracy logo in SVG (I simplified curves to make it as small as possible):

```svg
<svg viewBox="0 0 1561 333" xmlns="http://www.w3.org/2000/svg">
<path d="M176 327l-57 0 0 -269 -119 0 0 -57 291 0 0 57 -115 0 0 269zm208 -191l0 0 114 0c50,0 47,-78 0,-78l-114 0 0 78zm106 -135l0 0c17,0 33,2 46,7 75,30 75,144 1,175 -13,6 -29,8 -47,8l-27 0 132 74 0 68 -211 -128 0 122 -57 0 0 -326 163 0zm300 57l0 0c-5,0 -9,3 -11,9l-56 156 135 0 -55 -155c-2,-7 -6,-10 -13,-10zm-86 222l0 0 -17 47 -61 0 102 -285c20,-56 107,-56 126,0l102 285 -61 0 -17 -47 -174 0zm410 47l0 0c-98,0 -148,-55 -148,-163l0 -2c0,-107 50,-161 149,-161l118 0 0 57 -133 0c-26,0 -45,8 -58,25 -12,17 -19,44 -19,81 0,71 26,106 77,106l133 0 0 57 -119 0zm270 -145l0 0 -121 -181 68 0 81 130 81 -130 68 0 -121 178 0 148 -56 0 0 -145z"/>
</svg>
```

**Comment by dg** [comment]
Name of panel `variables` is misleading, it should be renamed to `dumps` or something like that.

**Comment by hrach** [comment]
I really like the padding. I understand Filip's problem, but ... I would personally
- removed the memory info
- hide the current route (to need a click), (or hide modules part)
- implement @Mikulas's database panel proposal,
- and other custom panels should deal with the size and could provide some shorter versions.

**Comment by zaxxx** [comment]
Abit late but guess I can throw my opinion here..

- memory icon is fine either way, it's like non-issue at all. For long time there's been bar graph icon, but suddenly it's "bad", WTF? Who cares?
- colors: I prefer the desaturated version by @ddx32
- padding sucks, eats too much space. If you really feel the need to divide the informations, I'd suggest using some kind of vertical hr, or middot or whatever. Just.. don't expand the bar too much, please.
- why not making this stuff configurable in neon? Everyone loves options, right? And you can never choose colors that will fit everyone, it's simply not gonna happen.
- the new routing icon is awesome.

**Comment by ddx32** [comment]
Further experiments and ideas based on some feedback.

I like the idea of collapsible data within the bar, but probably not in this form, it needs to integrate nicely with the hover information.

I guess we need to decide which information needs to be displayed by default and what's not so important (but it's there if you need it).

![debugbar](https://cloud.githubusercontent.com/assets/7354970/6097342/04226f3c-afbb-11e4-8bff-0324e0d8ef14.png)

**Comment by JanTvrdik** [comment]
The desaturated version is depressive and sad. It should look cheerful.

**Comment by kubinpetr** [comment]
Please no padding & with names near by icons.

**Comment by ddx32** [comment]
These are some more ideas to separate data visually as I progressed over time. The last option would represent a clean new site with no db connection, no errors and no dumps. I think it looks neat.

I reused @medhi's first color set as I liked it the most, what do you think?

![debugbar](https://cloud.githubusercontent.com/assets/7354970/6097558/d01f7f1a-afc2-11e4-9a7c-b51a4a3622e1.png)

**Comment by Aurielle** [comment]
I like the idea of visualizing more important information the way you did in the third example. The second example is a bit confusing for me, because it looks like the number of queries and time spent on them don't belong together. As for colours, I like this set better than the desaturated version.

**Comment by kubinpetr** [comment]
@ddx32 From last examples is 3. the best, but CPU, or what it is the last orange image, is not good. :)
Nice tip with removing "queries" and show only number. ;)

**Comment by dg** [comment]
#98 Removed memory (or time) tab

**Comment by ddx32** [comment]
Good, now that Memory is gone things look cleaner as there won't be a need for toggling data on/off. Here are some refinements and ideas.

What do you think of this Router icon?

I thought of moving the variables out of the main bar as it would be a good practice to use this feature only temporarily.

![debugbar](https://cloud.githubusercontent.com/assets/7354970/6098381/aca80a2e-afdc-11e4-9a09-feca1a77f4b3.png)

**Comment by hrach** [comment]
I like:
- more "visiual" errors here: https://github.com/nette/tracy/issues/97#issuecomment-73421986
- striping "queries", visual solution here: https://github.com/nette/tracy/issues/97#issuecomment-73431224
- bar border & close button

I dislike:
- left blue tracy logo background
- dumped variables above
- icon in routing

**Comment by Vrtak-CZ** [comment]
:+1: https://github.com/nette/tracy/issues/97#issuecomment-73408118

**Comment by JanJakes** [comment]
While speaking about redesign what about a possibility (could be optional) to snap the panel to the bottom/top (or right/left) of the screen? While Tracy in general is way better than the Symfony Debug component, their debug panel's design is a few steps ahead Tracy (see the attached image and notice the responsiveness).

![screen shot 2012-04-13 at 4 39 20 pm](https://cloud.githubusercontent.com/assets/141436/6102530/7199592c-b038-11e4-8131-76751dde35d4.png)

![guzzle_bundle](https://cloud.githubusercontent.com/assets/141436/6102539/9832594e-b038-11e4-9aa1-072cae9b315d.png)

**Comment by foxycode** [comment]
I like the snap idea, looks great on image above.

And please don't remove memory from bar, I actually use it.

**Comment by kubinpetr** [comment]
My definitiv :+1: is for @hrach version https://github.com/nette/tracy/issues/97#issuecomment-73432460 
So please try merge it to 2.3. :)

**Comment by dg** [comment]
Bar with vector icons is here https://github.com/nette/tracy/pull/99
